import { high, inferBrand } from "./helpers";
import type { MarriottProperty } from "./types";

// Source: Marriott hotel sitemap property codes, July 2026.
const unitedArabEmiratesMarriottOfficialRows = [
  { id: "AUHEB", officialName: "The Abu Dhabi EDITION" },
  { id: "DXBED", officialName: "The Dubai EDITION" },
  { id: "AUHLC", officialName: "Al Wathba, a Luxury Collection Desert Resort & Spa, Abu Dhabi" },
  { id: "DXBGL", officialName: "Grosvenor House, a Luxury Collection Hotel, Dubai" },
  { id: "DXBAM", officialName: "Al Maha, a Luxury Collection Desert Resort & Spa, Dubai" },
  { id: "SHJLC", officialName: "Ajman Saray, a Luxury Collection Resort, Ajman" },
  { id: "DXBJW", officialName: "JW Marriott Marquis Hotel Dubai" },
  { id: "DXBJM", officialName: "JW Marriott Hotel Marina" },
  { id: "AUHRX", officialName: "The St. Regis Abu Dhabi" },
  { id: "AUHXR", officialName: "The St. Regis Saadiyat Island Resort, Abu Dhabi" },
  { id: "DXBPX", officialName: "The St. Regis Dubai, The Palm" },
  { id: "DXBDX", officialName: "The St. Regis Downtown Dubai" },
  { id: "AUHWH", officialName: "W Abu Dhabi - Yas Island" },
  { id: "DXBTP", officialName: "W Dubai - The Palm" },
  { id: "DXBMW", officialName: "W Dubai – Mina Seyahi" },
  { id: "DXBLV", officialName: "La Ville Hotel & Suites CITY WALK, Dubai, Autograph Collection" },
  { id: "DXBDZ", officialName: "The Heritage Hotel, Autograph Collection" },
  { id: "DXBAK", officialName: "Lapita, Dubai Parks and Resorts, Autograph Collection" },
  { id: "DXBHG", officialName: "Al Habtoor Grand Resort, Autograph Collection" },
  { id: "DXBDD", officialName: "Hotel Boulevard, Autograph Collection" },
  { id: "DXBCH", officialName: "The Canvas Hotel, Dubai, Autograph Collection" },
  { id: "DXBJK", officialName: "Hotel Local Dubai, Jumeirah Village Triangle, Autograph Collection" },
  { id: "DXBGC", officialName: "Delta Hotels, Dubai Investment Park" },
  { id: "DXBDS", officialName: "FORM Hotel Al Jaddaf, Dubai, a Member of Design Hotels™" },
  { id: "AUHDM", officialName: "Le Royal Méridien Abu Dhabi" },
  { id: "AUHMD", officialName: "Le Méridien Abu Dhabi Resort" },
  { id: "DXBBM", officialName: "Le Royal Méridien Beach Resort & Spa" },
  { id: "DXBMD", officialName: "Le Méridien Dubai Hotel & Conference Centre" },
  { id: "DXBMS", officialName: "Le Méridien Mina Seyahi Beach Resort & Waterpark" },
  { id: "FJRMD", officialName: "Le Méridien Al Aqah Beach Resort" },
  { id: "AUHMC", officialName: "Marriott Hotel Downtown, Abu Dhabi" },
  { id: "AUHAL", officialName: "Marriott Hotel Al Forsan, Abu Dhabi" },
  { id: "DXBHR", officialName: "Dubai Marriott Harbour Hotel & Suites" },
  { id: "DXBMH", officialName: "Marriott Hotel Al Jaddaf, Dubai" },
  { id: "DXBPJ", officialName: "Marriott Resort Palm Jumeirah, Dubai" },
  { id: "DXBMJ", officialName: "Marriott Marquis Dubai Creek" },
  { id: "DXBPM", officialName: "Marriott Hotel Production City, Dubai" },
  { id: "DXBRB", officialName: "Renaissance Business Bay Hotel, Dubai" },
  { id: "AUHSI", officialName: "Sheraton Abu Dhabi Hotel & Resort" },
  { id: "DXBGH", officialName: "Sheraton Grand Hotel, Dubai" },
  { id: "DXBJS", officialName: "Sheraton Jumeirah Beach Resort" },
  { id: "DXBML", officialName: "Sheraton Mall of the Emirates Hotel, Dubai" },
  { id: "DXBSI", officialName: "Sheraton Dubai Creek Hotel & Towers" },
  { id: "DXBSJ", officialName: "Sheraton The Walk, Dubai" },
  { id: "DXBSG", officialName: "Sheraton Dubai Investment Park" },
  { id: "SHJSI", officialName: "Sheraton Sharjah Beach Resort & Spa" },
  { id: "DXBBT", officialName: "The First Collection Waterfront, Dubai, a Tribute Portfolio Hotel" },
  { id: "DXBMT", officialName: "The First Collection Marina, Dubai, a Tribute Portfolio Hotel" },
  { id: "DXBJV", officialName: "The First Collection at Jumeirah Village Circle, a Tribute Portfolio Hotel" },
  { id: "DXBTB", officialName: "The First Collection Business Bay, Dubai, a Tribute Portfolio Hotel" },
  { id: "DXBMB", officialName: "The Westin Dubai Mina Seyahi Beach Resort & Marina" },
  { id: "AANLO", officialName: "Aloft by Marriott Al Ain" },
  { id: "AUHNL", officialName: "Aloft by Marriott Abu Dhabi" },
  { id: "DXBAD", officialName: "Aloft by Marriott Dubai Airport" },
  { id: "DXBAP", officialName: "Aloft by Marriott Palm Jumeirah" },
  { id: "DXBAS", officialName: "Aloft by Marriott Dubai South" },
  { id: "DXBDE", officialName: "Aloft by Marriott Dubai Creek" },
  { id: "DXBIZ", officialName: "Aloft by Marriott Me'aisam, Dubai" },
  { id: "DXBRA", officialName: "Aloft by Marriott Al Mina, Dubai" },
  { id: "AUHCY", officialName: "Courtyard by Marriott World Trade Center, Abu Dhabi" },
  { id: "DXBCB", officialName: "Courtyard by Marriott Al Barsha, Dubai" },
  { id: "DXBCT", officialName: "Courtyard by Marriott World Trade Centre, Dubai" },
  { id: "DXBCV", officialName: "Courtyard by Marriott Culture Village, Dubai" },
  { id: "AANFP", officialName: "Four Points by Sheraton Al Ain" },
  { id: "DXBDF", officialName: "Four Points by Sheraton Bur Dubai" },
  { id: "DXBSF", officialName: "Four Points by Sheraton Sheikh Zayed Road, Dubai" },
  { id: "DXBPC", officialName: "Four Points by Sheraton Production City, Dubai" },
  { id: "SHJFP", officialName: "Four Points by Sheraton Sharjah" },
  { id: "DXBEJ", officialName: "Element by Marriott Al Jaddaf, Dubai" },
  { id: "DXBEL", officialName: "Element by Marriott Me'aisam, Dubai" },
  { id: "DXBEP", officialName: "Element by Marriott Dubai Airport" },
  { id: "DXBRE", officialName: "Element by Marriott Al Mina, Dubai" },
  { id: "AUHER", officialName: "Marriott Executive Apartments Downtown Abu Dhabi" },
  { id: "DXBER", officialName: "Marriott Executive Apartments Dubai Creek" },
  { id: "DXBHC", officialName: "Marriott Executive Apartments Al Jaddaf, Dubai" },
  { id: "DXBPR", officialName: "Vintage Grand Hotel Apartments Dubai" },
  { id: "DXBVJ", officialName: "Marriott Executive Apartments Jumeirah Lakes Towers, Dubai" },
  { id: "DXBSZ", officialName: "Residence Inn by Marriott Sheikh Zayed Road, Dubai" },
] as const;

export const unitedArabEmiratesMarriottProperties: MarriottProperty[] = unitedArabEmiratesMarriottOfficialRows.map(
  ({ id, officialName }) => ({
    id,
    country: "AE",
    region: "overseas",
    officialName,
    brand: inferBrand(officialName),
    ...high,
    aliases: [],
  })
);
