import { high, inferBrand, propertyId } from "./helpers";
import type { MarriottProperty } from "./types";

const australiaOfficialNames = [
  "Adelaide Marriott Hotel",
  "The Westin Brisbane",
  "Four Points by Sheraton Brisbane",
  "Courtyard by Marriott Brisbane South Bank",
  "Brisbane Marriott Hotel",
  "W Brisbane",
  "Midnight Hotel, Autograph Collection",
  "Courtyard by Marriott Darwin",
  "Sheraton Grand Mirage Resort, Gold Coast",
  "The Tasman, a Luxury Collection Hotel, Hobart",
  "Moxy Sydney Airport",
  "Sheraton Melbourne Hotel",
  "Element by Marriott Melbourne Richmond",
  "Melbourne Marriott Hotel",
  "Melbourne Marriott Hotel Docklands",
  "AC Hotel Melbourne Southbank",
  "Adelphi Hotel, a Member of Design Hotels",
  "Le Méridien Melbourne",
  "The Ritz-Carlton, Melbourne",
  "The Westin Melbourne",
  "W Melbourne",
  "Courtyard by Marriott Melbourne Flagstaff Gardens",
  "Aloft by Marriott Perth",
  "The Ritz-Carlton, Perth",
  "The Westin Perth",
  "Four Points by Sheraton Perth",
  "Courtyard by Marriott Perth, Murdoch",
  "Sheraton Grand Mirage Resort, Port Douglas",
  "Marriott Vacation Club at Surfers Paradise",
  "JW Marriott Gold Coast Resort & Spa",
  "Pier One Sydney Harbour, Autograph Collection",
  "Sydney Harbour Marriott Hotel at Circular Quay",
  "W Sydney",
  "Four Points by Sheraton Sydney, Central Park",
  "Sheraton Grand Sydney Hyde Park",
];

export const australiaMarriottProperties: MarriottProperty[] =
  australiaOfficialNames.map((officialName) => ({
    id: propertyId("AU", officialName),
    country: "AU",
    region: "overseas",
    officialName,
    brand: inferBrand(officialName),
    brandGroup: high.brandGroup,
    confidence: high.confidence,
    status: high.status,
    aliases: [],
    reason: `${officialName}은 Marriott Bonvoy 계열 호텔로 확인된 호주 호텔입니다.`,
  }));
