import { high, inferBrand } from "./helpers";
import type { MarriottPropertySeed } from "./types";

// Source: Marriott destination page property codes, July 2026.
const australiaOfficialRows = [
  { id: "ADLMC", officialName: "Adelaide Marriott Hotel" },
  { id: "BNEWI", officialName: "The Westin Brisbane" },
  { id: "BNEFP", officialName: "Four Points by Sheraton Brisbane" },
  { id: "BNECY", officialName: "Courtyard by Marriott Brisbane South Bank" },
  { id: "BNEDT", officialName: "Brisbane Marriott Hotel" },
  { id: "BNEWH", officialName: "W Brisbane" },
  { id: "CBRAK", officialName: "Midnight Hotel, Autograph Collection" },
  { id: "DRWCY", officialName: "Courtyard by Marriott Darwin" },
  { id: "OOLGS", officialName: "Sheraton Grand Mirage Resort, Gold Coast" },
  { id: "HBALC", officialName: "The Tasman, a Luxury Collection Hotel, Hobart" },
  { id: "SYDXP", officialName: "Moxy Sydney Airport" },
  { id: "MELSI", officialName: "Sheraton Melbourne Hotel" },
  { id: "MELEL", officialName: "Element by Marriott Melbourne Richmond" },
  { id: "MELMC", officialName: "Melbourne Marriott Hotel" },
  { id: "MELDL", officialName: "Melbourne Marriott Hotel Docklands" },
  { id: "MELAC", officialName: "AC Hotel Melbourne Southbank" },
  { id: "MELAH", officialName: "Adelphi Hotel, a Member of Design Hotels" },
  { id: "MELMD", officialName: "Le Méridien Melbourne" },
  { id: "MELRZ", officialName: "The Ritz-Carlton, Melbourne" },
  { id: "MELWI", officialName: "The Westin Melbourne" },
  { id: "MELWH", officialName: "W Melbourne" },
  { id: "MELCY", officialName: "Courtyard by Marriott Melbourne Flagstaff Gardens" },
  { id: "PERAL", officialName: "Aloft by Marriott Perth" },
  { id: "PERRZ", officialName: "The Ritz-Carlton, Perth" },
  { id: "PERWI", officialName: "The Westin Perth" },
  { id: "PERFP", officialName: "Four Points by Sheraton Perth" },
  { id: "PERMC", officialName: "Courtyard by Marriott Perth, Murdoch" },
  { id: "CNSSI", officialName: "Sheraton Grand Mirage Resort, Port Douglas" },
  { id: "OOLMV", officialName: "Marriott Vacation Club at Surfers Paradise" },
  { id: "OOLSP", officialName: "JW Marriott Gold Coast Resort & Spa" },
  { id: "SYDAK", officialName: "Pier One Sydney Harbour, Autograph Collection" },
  { id: "SYDMC", officialName: "Sydney Harbour Marriott Hotel at Circular Quay" },
  { id: "SYDWH", officialName: "W Sydney" },
  { id: "SYDCF", officialName: "Four Points by Sheraton Sydney, Central Park" },
  { id: "SYDSI", officialName: "Sheraton Grand Sydney Hyde Park" },
];

export const australiaMarriottProperties: MarriottPropertySeed[] =
  australiaOfficialRows.map(({ id, officialName }) => ({
    id: `au-${id.toLowerCase()}`,
    country: "AU",
    region: "overseas",
    officialName,
    brand: inferBrand(officialName),
    brandGroup: high.brandGroup,
    confidence: high.confidence,
    status: high.status,
    aliases: [],
    reason: `${officialName}은 Marriott Bonvoy 계열 호텔로 확인된 호주 호텔입니다.`,
  }));
