import { high, inferBrand } from "./helpers";
import type { MarriottProperty } from "./types";

// Source: Marriott hotel sitemap property codes, July 2026.
const canadaMarriottOfficialRows = [
  { id: "YYZLD", officialName: "BISHA, a Luxury Collection Hotel, Toronto" },
  { id: "YHZLC", officialName: "Muir, a Luxury Collection Hotel, Halifax" },
  { id: "YEGJW", officialName: "JW Marriott Edmonton ICE District" },
  { id: "YQAJW", officialName: "JW Marriott The Rosseau Muskoka Resort & Spa" },
  { id: "YVRJW", officialName: "JW Marriott Parq Vancouver" },
  { id: "YYZXR", officialName: "The St. Regis Toronto" },
  { id: "YULWH", officialName: "W Montreal" },
  { id: "YYZWH", officialName: "W Toronto" },
  { id: "YVRPS", officialName: "the DOUGLAS, Autograph Collection" },
  { id: "YQRAK", officialName: "The Hotel Saskatchewan, Autograph Collection" },
  { id: "YSJAK", officialName: "The Algonquin Resort St. Andrews by-the-Sea, Autograph Collection" },
  { id: "YVRAK", officialName: "Civic Hotel, Autograph Collection" },
  { id: "YYCKK", officialName: "Kananaskis Mountain Lodge, Autograph Collection" },
  { id: "YYCAK", officialName: "The Dorian, Autograph Collection" },
  { id: "YZZAK", officialName: "The Josie Hotel, Autograph Collection" },
  { id: "YHMAK", officialName: "The Pearle Hotel & Spa, Autograph Collection" },
  { id: "YULAK", officialName: "Humaniti Hotel Montreal, Autograph Collection" },
  { id: "YFCDF", officialName: "Delta Hotels Fredericton" },
  { id: "YKADE", officialName: "Delta Hotels Kamloops" },
  { id: "YQTDE", officialName: "Delta Hotels Thunder Bay" },
  { id: "YYZDE", officialName: "Delta Hotels Toronto Mississauga" },
  { id: "YYGDP", officialName: "Delta Hotels Prince Edward" },
  { id: "YQMDR", officialName: "Delta Hotels Beausejour" },
  { id: "YOWDM", officialName: "Delta Hotels Ottawa City Centre" },
  { id: "YHZDM", officialName: "Delta Hotels Dartmouth" },
  { id: "YAMDS", officialName: "Delta Hotels Sault Ste. Marie Waterfront" },
  { id: "YBGJS", officialName: "Delta Hotels Saguenay Conference Centre" },
  { id: "YEGEC", officialName: "Delta Hotels Edmonton Centre Suites" },
  { id: "YEGES", officialName: "Delta Hotels Edmonton South Conference Centre" },
  { id: "YGKDK", officialName: "Delta Hotels Kingston Waterfront" },
  { id: "YKFDG", officialName: "Delta Hotels Guelph Conference Centre" },
  { id: "YKFDW", officialName: "Delta Hotels Waterloo" },
  { id: "YQBDR", officialName: "Delta Hotels Quebec" },
  { id: "YQRDR", officialName: "Delta Hotels Regina" },
  { id: "YQUDE", officialName: "Delta Hotels Grande Prairie Airport" },
  { id: "YRQDR", officialName: "Delta Hotels Trois Rivieres Conference Centre" },
  { id: "YSCDR", officialName: "Delta Hotels Sherbrooke Conference Centre" },
  { id: "YSEWV", officialName: "Delta Hotels Whistler Village Suites" },
  { id: "YSJDB", officialName: "Delta Hotels Saint John" },
  { id: "YULDB", officialName: "Delta Hotels Montreal" },
  { id: "YVRDB", officialName: "Delta Hotels Burnaby Conference Centre" },
  { id: "YWGDW", officialName: "Delta Hotels Winnipeg" },
  { id: "YXEDB", officialName: "Delta Hotels Bessborough" },
  { id: "YXEDS", officialName: "Delta Hotels Saskatoon Downtown" },
  { id: "YXUDL", officialName: "Delta Hotels London Armouries" },
  { id: "YYCCA", officialName: "Delta Hotels Calgary Airport In-Terminal" },
  { id: "YYCDC", officialName: "Delta Hotels Calgary South" },
  { id: "YYTDS", officialName: "Delta Hotels St. John's Conference Centre" },
  { id: "YYZDA", officialName: "Delta Hotels Toronto Airport & Conference Centre" },
  { id: "YYZSB", officialName: "Delta Hotels Toronto East" },
  { id: "YLWOK", officialName: "Delta Hotels Grand Okanagan Resort" },
  { id: "YVRDD", officialName: "Delta Hotels Vancouver Delta" },
  { id: "YYZDH", officialName: "Delta Hotels Toronto Markham" },
  { id: "YQBDM", officialName: "Delta Hotels, Mont Sainte-Anne, Resort & Convention Center" },
  { id: "YVRDV", officialName: "Delta Hotels Vancouver Downtown Suites" },
  { id: "YYZDL", officialName: "Delta Hotels Toronto" },
  { id: "YYJVO", officialName: "Delta Hotels Victoria Ocean Pointe Resort" },
  { id: "YYCBV", officialName: "Delta Hotels Calgary Downtown" },
  { id: "YHZDD", officialName: "Delta Hotels Halifax Downtown" },
  { id: "YULDS", officialName: "Hotel St. Paul, Montreal, a Member of Design Hotels™" },
  { id: "YYZLM", officialName: "Le Méridien Toronto Pinnacle Hotel" },
  { id: "YVRRL", officialName: "Le Méridien Richmond Pinnacle Hotel" },
  { id: "IAGNF", officialName: "Niagara Falls Marriott Fallsview Hotel & Spa" },
  { id: "IAGMC", officialName: "Niagara Falls Marriott on the Falls" },
  { id: "YOWMC", officialName: "Ottawa Marriott Hotel" },
  { id: "YYCXA", officialName: "Calgary Airport Marriott In-Terminal Hotel" },
  { id: "YYJMC", officialName: "Victoria Marriott Inner Harbour" },
  { id: "YYZOT", officialName: "Toronto Airport Marriott Hotel" },
  { id: "YYZMR", officialName: "Toronto Marriott Markham" },
  { id: "YYZCC", officialName: "Toronto Marriott City Centre Hotel" },
  { id: "YYZEC", officialName: "Marriott Downtown at CF Toronto Eaton Centre" },
  { id: "YULCC", officialName: "Montreal Marriott Chateau Champlain" },
  { id: "YULMA", officialName: "Montreal Airport Marriott In-Terminal Hotel" },
  { id: "YVRSA", officialName: "Vancouver Airport Marriott Hotel" },
  { id: "YGKMC", officialName: "Kingston Marriott" },
  { id: "YYCDT", officialName: "Calgary Marriott Downtown Hotel" },
  { id: "YQBMC", officialName: "Quebec City Marriott Downtown" },
  { id: "YVRDT", officialName: "Vancouver Marriott Pinnacle Downtown Hotel" },
  { id: "YHZMC", officialName: "Halifax Marriott Harbourfront Hotel" },
  { id: "YEGBR", officialName: "Renaissance Edmonton Airport Hotel" },
  { id: "YULMD", officialName: "Renaissance Montreal Downtown Hotel" },
  { id: "YVRBR", officialName: "Metropolitan Hotel Vancouver" },
  { id: "IAGSI", officialName: "Sheraton Fallsview Hotel" },
  { id: "YHMSI", officialName: "Sheraton Hamilton Hotel" },
  { id: "YXESI", officialName: "Sheraton Cavalier Saskatoon Hotel" },
  { id: "YYZTC", officialName: "Sheraton Centre Toronto Hotel" },
  { id: "YOWSI", officialName: "Sheraton Ottawa Hotel" },
  { id: "YULHY", officialName: "Sheraton Saint-Hyacinthe Hotel" },
  { id: "YULLS", officialName: "Sheraton Laval Hotel" },
  { id: "YULSA", officialName: "Sheraton Montreal Airport Hotel" },
  { id: "YVRVS", officialName: "Sheraton Vancouver Airport Hotel" },
  { id: "YYCES", officialName: "Sheraton Suites Calgary Eau Claire" },
  { id: "YYCSC", officialName: "Sheraton Cavalier Calgary Hotel" },
  { id: "YYTSI", officialName: "Sheraton Hotel Newfoundland" },
  { id: "YYZDS", officialName: "Sheraton Toronto Airport Hotel & Conference Centre" },
  { id: "YYZSI", officialName: "Sheraton Parkway Toronto North Hotel & Suites" },
  { id: "YYZGS", officialName: "Sheraton Gateway Hotel in Toronto International Airport" },
  { id: "YVRWS", officialName: "Sheraton Vancouver Wall Centre" },
  { id: "YVRSI", officialName: "Sheraton Vancouver Guildford Hotel" },
  { id: "YULSI", officialName: "Le Centre Sheraton Montreal Hotel" },
  { id: "YQGTX", officialName: "The Insignia Hotel, Sarnia, a Tribute Portfolio Hotel" },
  { id: "YULTX", officialName: "HONEYROSE Hotel, Montreal, a Tribute Portfolio Hotel" },
  { id: "YQBPU", officialName: "Hotel PUR, Quebec, a Tribute Portfolio Hotel" },
  { id: "YULSB", officialName: "Mont Gabriel, Sainte-Adèle, a Tribute Portfolio Resort" },
  { id: "YULLB", officialName: "Ômage Hotel, Montreal Laval, a Tribute Portfolio Hotel" },
  { id: "YXUSX", officialName: "The Queen’s Cue, Stratford, A Tribute Portfolio Hotel" },
  { id: "YOWWI", officialName: "The Westin Ottawa" },
  { id: "YVRWI", officialName: "The Westin Bayshore, Vancouver" },
  { id: "YYCWI", officialName: "The Westin Calgary" },
  { id: "YYZTH", officialName: "The Westin Trillium House, Blue Mountain" },
  { id: "YYZWI", officialName: "The Westin Harbour Castle, Toronto" },
  { id: "YEGWI", officialName: "The Westin Edmonton" },
  { id: "YHZWI", officialName: "The Westin Nova Scotian" },
  { id: "YMYWI", officialName: "Le Westin Tremblant" },
  { id: "YULLE", officialName: "Le Westin Montreal" },
  { id: "YVRWC", officialName: "The Westin Wall Centre, Vancouver Airport" },
  { id: "YYCWA", officialName: "The Westin Calgary Airport" },
  { id: "YYJWI", officialName: "The Westin Bear Mountain Golf Resort & Spa, Victoria" },
  { id: "YYZBW", officialName: "The Westin Toronto Airport" },
  { id: "YSEWI", officialName: "The Westin Resort & Spa, Whistler" },
  { id: "YULAC", officialName: "Hôtel AC Montréal Centre-ville" },
  { id: "YOWAC", officialName: "AC Hotel Ottawa Downtown" },
  { id: "YULOM", officialName: "AC Hotel Old Montreal" },
  { id: "YULAL", officialName: "Aloft by Marriott Montreal Airport" },
  { id: "YYCUL", officialName: "Aloft by Marriott Calgary University" },
  { id: "YYZAL", officialName: "Aloft by Marriott Vaughan Mills" },
  { id: "YYZPX", officialName: "City Express by Marriott Port Hope" },
  { id: "IAGCY", officialName: "Courtyard by Marriott Niagara Falls" },
  { id: "YYCAP", officialName: "Courtyard by Marriott Calgary Airport" },
  { id: "YYZCY", officialName: "Courtyard by Marriott Toronto Downtown" },
  { id: "YEGCY", officialName: "Courtyard by Marriott Edmonton Downtown" },
  { id: "YEGEW", officialName: "Courtyard by Marriott Edmonton West" },
  { id: "YGKCY", officialName: "Courtyard by Marriott Kingston Highway 401/Division Street" },
  { id: "YHMBU", officialName: "Courtyard by Marriott Burlington" },
  { id: "YHMCY", officialName: "Courtyard by Marriott Hamilton" },
  { id: "YHZCD", officialName: "Courtyard by Marriott Halifax Dartmouth" },
  { id: "YHZCY", officialName: "Courtyard by Marriott Halifax Downtown" },
  { id: "YKFCY", officialName: "Courtyard by Marriott Waterloo St. Jacobs" },
  { id: "YOOCY", officialName: "Courtyard by Marriott Oshawa" },
  { id: "YOWCY", officialName: "Courtyard by Marriott Ottawa Downtown" },
  { id: "YOWOE", officialName: "Courtyard by Marriott Ottawa East" },
  { id: "YQBCQ", officialName: "Courtyard by Marriott Quebec City" },
  { id: "YULAP", officialName: "Courtyard by Marriott Montreal Airport" },
  { id: "YULBC", officialName: "Courtyard by Marriott Montreal Brossard" },
  { id: "YULBD", officialName: "Courtyard by Marriott Montreal West Island/Baie D’Urfe" },
  { id: "YULDT", officialName: "Courtyard by Marriott Montreal Downtown" },
  { id: "YWGAP", officialName: "Courtyard by Marriott Winnipeg Airport" },
  { id: "YXECY", officialName: "Courtyard by Marriott Saskatoon Airport" },
  { id: "YXSCY", officialName: "Courtyard by Marriott Prince George" },
  { id: "YXUCY", officialName: "Courtyard by Marriott London" },
  { id: "YYCCS", officialName: "Courtyard by Marriott Calgary South" },
  { id: "YYTCY", officialName: "Courtyard by Marriott St. John's Newfoundland" },
  { id: "YYZAP", officialName: "Courtyard by Marriott Toronto Airport" },
  { id: "YYZBM", officialName: "Courtyard by Marriott Toronto Brampton" },
  { id: "YYZMD", officialName: "Courtyard by Marriott Toronto Mississauga/West" },
  { id: "YYZMK", officialName: "Courtyard by Marriott Toronto Markham" },
  { id: "YYZMQ", officialName: "Courtyard by Marriott Mississauga-Airport Corporate Centre West" },
  { id: "YYZMS", officialName: "Courtyard by Marriott Toronto Mississauga/Meadowvale" },
  { id: "YYZMT", officialName: "Courtyard by Marriott Toronto Northeast/Markham" },
  { id: "YYZVN", officialName: "Courtyard by Marriott Toronto Vaughan" },
  { id: "YYCXD", officialName: "Courtyard by Marriott Calgary Downtown" },
  { id: "YULND", officialName: "Courtyard by Marriott Montreal Midtown" },
  { id: "YULLC", officialName: "Courtyard by Marriott Montreal Laval" },
  { id: "YKFCK", officialName: "Courtyard by Marriott Kitchener" },
  { id: "YCDCY", officialName: "Courtyard by Marriott Nanaimo" },
  { id: "YQRCY", officialName: "Courtyard by Marriott Regina Downtown" },
  { id: "IAGIF", officialName: "Fairfield by Marriott Niagara Falls, Canada" },
  { id: "RQSFO", officialName: "Fairfield by Marriott Inn & Suites Orillia" },
  { id: "RQSFI", officialName: "Fairfield by Marriott Inn & Suites Barrie" },
  { id: "YYCFI", officialName: "Fairfield by Marriott Inn & Suites Calgary Downtown" },
  { id: "YAMFI", officialName: "Fairfield by Marriott Inn & Suites Sault Ste. Marie" },
  { id: "YEGFA", officialName: "Fairfield by Marriott Edmonton International Airport" },
  { id: "YEGFI", officialName: "Fairfield by Marriott Inn & Suites Edmonton North" },
  { id: "YGKFI", officialName: "Fairfield by Marriott Inn & Suites Belleville" },
  { id: "YKAFI", officialName: "Fairfield by Marriott Inn & Suites Kamloops" },
  { id: "YKFFI", officialName: "Fairfield by Marriott Inn & Suites Guelph" },
  { id: "YLWFI", officialName: "Fairfield by Marriott Inn & Suites Kelowna" },
  { id: "YOWFA", officialName: "Fairfield by Marriott Inn & Suites Ottawa Airport" },
  { id: "YOWFI", officialName: "Fairfield by Marriott Inn & Suites Ottawa Kanata" },
  { id: "YQLFI", officialName: "Fairfield by Marriott Inn & Suites Lethbridge" },
  { id: "YQMFI", officialName: "Fairfield by Marriott Inn & Suites Moncton" },
  { id: "YQRFI", officialName: "Fairfield by Marriott Regina" },
  { id: "YRVFI", officialName: "Fairfield by Marriott Inn & Suites Revelstoke" },
  { id: "YSBFI", officialName: "Fairfield by Marriott Inn & Suites Sudbury" },
  { id: "YSNFI", officialName: "Fairfield by Marriott Inn & Suites Salmon Arm" },
  { id: "YULFD", officialName: "Fairfield by Marriott Montreal Downtown" },
  { id: "YULFI", officialName: "Fairfield by Marriott Inn & Suites Montreal Airport" },
  { id: "YVEFI", officialName: "Fairfield by Marriott Inn & Suites Vernon" },
  { id: "YWGFI", officialName: "Fairfield by Marriott Inn & Suites Winnipeg" },
  { id: "YYTFI", officialName: "Fairfield by Marriott Inn & Suites St. John's Newfoundland" },
  { id: "YYZBP", officialName: "Fairfield by Marriott Inn & Suites Toronto Brampton" },
  { id: "YYZFS", officialName: "Fairfield by Marriott Inn & Suites Toronto Airport" },
  { id: "YYZTM", officialName: "Fairfield by Marriott Inn & Suites Toronto Mississauga" },
  { id: "YYZTO", officialName: "Fairfield Inn Toronto Oakville" },
  { id: "YLWFE", officialName: "Fairfield by Marriott Inn & Suites Penticton" },
  { id: "YYBFI", officialName: "Fairfield by Marriott Inn & Suites North Bay" },
  { id: "YLWFW", officialName: "Fairfield by Marriott Inn & Suites West Kelowna" },
  { id: "YYCAD", officialName: "Fairfield by Marriott Inn & Suites Airdrie" },
  { id: "YYZFO", officialName: "Fairfield by Marriott Inn & Suites Newmarket" },
  { id: "YQAGF", officialName: "Fairfield by Marriott Inn & Suites Gravenhurst Muskoka" },
  { id: "YXXCF", officialName: "Fairfield by Marriott Inn & Suites Chilliwack" },
  { id: "YYZBF", officialName: "Fairfield by Marriott Inn & Suites Bradford" },
  { id: "IAGFP", officialName: "Four Points by Sheraton St. Catharines Niagara Suites" },
  { id: "RQSFP", officialName: "Four Points by Sheraton Barrie" },
  { id: "YEGAF", officialName: "Four Points by Sheraton Edmonton International Airport" },
  { id: "YEGEF", officialName: "Four Points by Sheraton Edmonton Gateway" },
  { id: "YEGFP", officialName: "Four Points by Sheraton Edmonton South" },
  { id: "YEGFW", officialName: "Four Points by Sheraton Edmonton West" },
  { id: "YEGWF", officialName: "Four Points by Sheraton Sherwood Park" },
  { id: "YHMFP", officialName: "Four Points by Sheraton Hamilton - Stoney Creek" },
  { id: "YHZFP", officialName: "Four Points by Sheraton Halifax" },
  { id: "YKFFP", officialName: "Four Points by Sheraton Cambridge Kitchener, Ontario" },
  { id: "YLWFP", officialName: "Four Points by Sheraton Kelowna Airport" },
  { id: "YOWFP", officialName: "Four Points by Sheraton Hotel & Conference Centre Gatineau-Ottawa" },
  { id: "YQBEP", officialName: "Four Points by Sheraton Edmundston Hotel & Conference Center" },
  { id: "YQBLF", officialName: "Four Points by Sheraton Lévis Convention Centre" },
  { id: "YQMFP", officialName: "Four Points by Sheraton Moncton" },
  { id: "YQGFP", officialName: "Four Points by Sheraton Windsor Downtown" },
  { id: "YQRFP", officialName: "Four Points by Sheraton Regina" },
  { id: "YQUFP", officialName: "Four Points by Sheraton Grande Prairie" },
  { id: "YVRSF", officialName: "Four Points by Sheraton Surrey" },
  { id: "YWGWF", officialName: "Four Points by Sheraton Winnipeg South" },
  { id: "YXEFP", officialName: "Four Points by Sheraton Saskatoon" },
  { id: "YXUFP", officialName: "Four Points by Sheraton London" },
  { id: "YYCCF", officialName: "Four Points by Sheraton Calgary Airport" },
  { id: "YYCFP", officialName: "Four Points by Sheraton Hotel & Suites Calgary West" },
  { id: "YYJFP", officialName: "Four Points by Sheraton Victoria Gateway" },
  { id: "YYZAE", officialName: "Four Points by Sheraton Toronto Airport East" },
  { id: "YYZFP", officialName: "Four Points by Sheraton Toronto Mississauga" },
  { id: "YYZFV", officialName: "Four Points by Sheraton Vaughan" },
  { id: "YYZPA", officialName: "Four Points by Sheraton Toronto Airport" },
  { id: "YYZVF", officialName: "Four Points by Sheraton Mississauga Meadowvale" },
  { id: "YYFFP", officialName: "Four Points by Sheraton Penticton at the Convention Centre" },
  { id: "YQGFS", officialName: "Four Points by Sheraton Point Edward Sarnia" },
  { id: "YYZVP", officialName: "Four Points by Sheraton Oakville" },
  { id: "YHZOX", officialName: "Moxy Halifax Downtown" },
  { id: "YYCBM", officialName: "Moxy Banff" },
  { id: "YULOX", officialName: "Moxy Montreal Downtown" },
  { id: "YOWOX", officialName: "Moxy Ottawa Downtown" },
  { id: "YYZSV", officialName: "SpringHill Suites by Marriott Toronto Vaughan" },
  { id: "YEGEL", officialName: "Element by Marriott Edmonton West" },
  { id: "YVREL", officialName: "Element by Marriott Vancouver Metrotown" },
  { id: "YYCEL", officialName: "Element by Marriott Calgary Airport" },
  { id: "YYZEA", officialName: "Element by Marriott Toronto Airport" },
  { id: "YYZEL", officialName: "Element by Marriott Vaughan Southwest" },
  { id: "YYCED", officialName: "Element by Marriott Calgary Downtown" },
  { id: "YQARI", officialName: "Residence Inn by Marriott Gravenhurst Muskoka Wharf" },
  { id: "YULRI", officialName: "Residence Inn by Marriott Montreal Downtown" },
  { id: "YGKRI", officialName: "Residence Inn by Marriott Kingston Water's Edge" },
  { id: "YHZRD", officialName: "Residence Inn by Marriott Halifax Dartmouth" },
  { id: "YHZRI", officialName: "Residence Inn by Marriott Halifax Downtown" },
  { id: "YMYMT", officialName: "Residence Inn by Marriott Mont Tremblant Manoir Labelle" },
  { id: "YOWAP", officialName: "Residence Inn by Marriott Ottawa Airport" },
  { id: "YQMRI", officialName: "Residence Inn by Marriott Moncton" },
  { id: "YQRRI", officialName: "Residence Inn by Marriott Regina" },
  { id: "YULRA", officialName: "Residence Inn by Marriott Montreal Airport" },
  { id: "YVRDR", officialName: "Residence Inn by Marriott Vancouver Downtown" },
  { id: "YWGRI", officialName: "Residence Inn by Marriott Winnipeg" },
  { id: "YXURI", officialName: "Residence Inn by Marriott London Downtown" },
  { id: "YYCBL", officialName: "Residence Inn by Marriott Calgary Downtown/Beltline District" },
  { id: "YYCCR", officialName: "Residence Inn by Marriott Calgary South" },
  { id: "YYCRI", officialName: "Residence Inn by Marriott Calgary Airport" },
  { id: "YYZMH", officialName: "Residence Inn by Marriott Toronto Markham" },
  { id: "YYZMU", officialName: "Residence Inn by Marriott Mississauga-Airport Corporate Centre West" },
  { id: "YYZMX", officialName: "Residence Inn by Marriott Toronto Mississauga West" },
  { id: "YYZRI", officialName: "Residence Inn by Marriott Toronto Airport" },
  { id: "YYZRU", officialName: "Residence Inn by Marriott Toronto Mississauga Southwest" },
  { id: "YYZTD", officialName: "Residence Inn by Marriott Toronto Downtown/Entertainment District" },
  { id: "YYZTV", officialName: "Residence Inn by Marriott Toronto Vaughan" },
  { id: "YYZWY", officialName: "Residence Inn by Marriott Whitby" },
  { id: "YULRG", officialName: "Residence Inn by Marriott Montreal Midtown" },
  { id: "YULRL", officialName: "Residence Inn by Marriott Laval" },
  { id: "YEGRW", officialName: "Residence Inn by Marriott Edmonton West" },
  { id: "YULRB", officialName: "Residence Inn by Marriott Bromont" },
  { id: "IAGTR", officialName: "TownePlace Suites by Marriott Niagara Falls Canada" },
  { id: "YEGTS", officialName: "TownePlace Suites by Marriott Edmonton South" },
  { id: "YEGWO", officialName: "TownePlace Suites by Marriott Edmonton Sherwood Park" },
  { id: "YHMBF", officialName: "TownePlace Suites by Marriott Brantford and Conference Centre" },
  { id: "YHMTS", officialName: "TownePlace Suites by Marriott Hamilton" },
  { id: "YKDTS", officialName: "TownePlace Suites by Marriott Kincardine" },
  { id: "YMMTS", officialName: "TownePlace Suites by Marriott Fort McMurray" },
  { id: "YOOTS", officialName: "TownePlace Suites by Marriott Oshawa" },
  { id: "YOWTS", officialName: "TownePlace Suites by Marriott Ottawa Kanata" },
  { id: "YQFTS", officialName: "TownePlace Suites by Marriott Red Deer" },
  { id: "YQGTS", officialName: "TownePlace Suites by Marriott Windsor" },
  { id: "YQTTS", officialName: "TownePlace Suites by Marriott Thunder Bay" },
  { id: "YSBTS", officialName: "TownePlace Suites by Marriott Sudbury" },
  { id: "YTRTS", officialName: "TownePlace Suites by Marriott Belleville" },
  { id: "YWATS", officialName: "TownePlace Suites by Marriott Petawawa" },
  { id: "YXETS", officialName: "TownePlace Suites by Marriott Saskatoon" },
  { id: "YXHTS", officialName: "TownePlace Suites by Marriott Medicine Hat" },
  { id: "YXUTS", officialName: "TownePlace Suites by Marriott London" },
  { id: "YYZTS", officialName: "TownePlace Suites by Marriott Mississauga-Airport Corporate Centre" },
  { id: "YYZXM", officialName: "TownePlace Suites by Marriott Toronto Northeast/Markham" },
  { id: "YLWWK", officialName: "TownePlace Suites by Marriott West Kelowna" },
  { id: "YYZTL", officialName: "TownePlace Suites by Marriott Toronto Oakville" },
  { id: "YXXCT", officialName: "TownePlace Suites by Marriott Chilliwack" },
  { id: "YQGTT", officialName: "TownePlace Suites by Marriott Tecumseh Windsor" },
  { id: "YXUWT", officialName: "TownePlace Suites by Marriott Woodstock" },
  { id: "YYJST", officialName: "TownePlace Suites by Marriott Victoria Airport Sidney" },
  { id: "YULTS", officialName: "TownePlace Suites by Marriott Montreal Airport" },
  { id: "YYZVT", officialName: "TownePlace Suites by Marriott Vaughan" },
] as const;

export const canadaMarriottProperties: MarriottProperty[] = canadaMarriottOfficialRows.map(
  ({ id, officialName }) => ({
    id,
    country: "CA",
    region: "overseas",
    officialName,
    brand: inferBrand(officialName),
    ...high,
    aliases: [],
  })
);
