import { applyCuratedMarriottPropertyAliases } from "../marriottPropertyOverrides";
import { high, inferBrand } from "./helpers";
import type {
  MarriottPropertySeed,
  SharedMarriottMerchantRule,
} from "./types";

// Source: Marriott destination page property codes, July 2026.
const chinaOfficialRows = [
  { id: "AATFF", officialName: "Fairfield by Marriott Altay Fuhai" },
  { id: "AATJP", officialName: "Four Points by Sheraton Altay City" },
  { id: "AATFI", officialName: "Fairfield By Marriott Altay City" },
  { id: "HGHAJ", officialName: "JW Marriott Hotel Zhejiang Anji" },
  { id: "AVAHU", officialName: "Four Points by Sheraton Anshun, Huangguoshu" },
  { id: "LHWFB", officialName: "Fairfield by Marriott Baiyin Downtown" },
  { id: "BJSXF", officialName: "Fairfield by Marriott Xiong'an" },
  { id: "SJWFI", officialName: "Fairfield by Marriott Baoding High-Tech Zone" },
  { id: "BAVMC", officialName: "Baotou Marriott Hotel" },
  { id: "BHYMC", officialName: "Beihai Marriott Resort" },
  { id: "BHYSI", officialName: "Sheraton Beihai Resort" },
  { id: "BJSFW", officialName: "The Westin Beijing Financial Street" },
  { id: "BJSHE", officialName: "Element Beijing Huairou" },
  { id: "BJSRZ", officialName: "The Ritz-Carlton, Beijing" },
  { id: "BJSCP", officialName: "Beijing Marriott Hotel Changping" },
  { id: "BJSJD", officialName: "JW Marriott Hotel Beijing Dongzhimen" },
  { id: "BJSMQ", officialName: "Beijing Marriott Marquis Hotel" },
  { id: "BJSBP", officialName: "Courtyard by Marriott Beijing Changping" },
  { id: "BJSHL", officialName: "Aloft Beijing Huairou" },
  { id: "BJSWS", officialName: "Four Points by Sheraton Beijing West Station" },
  { id: "BJSHR", officialName: "Renaissance Beijing Haidian Hotel" },
  { id: "BJSXR", officialName: "The St. Regis Beijing" },
  { id: "BJSYC", officialName: "Courtyard By Marriott Beijing Yanqing" },
  { id: "BJSZN", officialName: "The Ritz-Carlton Beijing, North" },
  { id: "BJSDO", officialName: "Sheraton Grand Beijing Dongcheng Hotel" },
  { id: "BJSPE", officialName: "Fairfield by Marriott Beijing Capital Airport" },
  { id: "BJSFP", officialName: "Four Points by Sheraton Beijing, Haidian Hotel & Serviced Apartments" },
  { id: "BJSSH", officialName: "Sheraton Beijing Huairou Hotel" },
  { id: "BJSSL", officialName: "Sheraton Beijing Lize Hotel" },
  { id: "BJSPS", officialName: "Four Points by Sheraton Beijing Sanlitun Workers Stadium" },
  { id: "BJSRP", officialName: "Four Points by Sheraton Beijing, South Railway Station" },
  { id: "BJSSP", officialName: "Four Points by Sheraton Beijing South Railway Station, The Temple of Heaven Park" },
  { id: "BJSHM", officialName: "Beijing Marriott Hotel Huairou" },
  { id: "BJSWF", officialName: "Renaissance Beijing Wangfujing Hotel" },
  { id: "BJSDA", officialName: "Fairfield by Marriott Beijing Daxing Airport" },
  { id: "BJSAL", officialName: "Aloft Beijing, Haidian" },
  { id: "BJSBG", officialName: "Bvlgari Hotel Beijing" },
  { id: "BJSES", officialName: "Beijing Marriott Hotel Northeast" },
  { id: "BJSFO", officialName: "Fairfield by Marriott Beijing Olympic Sports Center" },
  { id: "BJSIP", officialName: "Four Points by Sheraton Beijing Xidan" },
  { id: "BJSFS", officialName: "The Ritz-Carlton Beijing, Financial Street" },
  { id: "BJSJW", officialName: "JW Marriott Hotel Beijing" },
  { id: "BJSFH", officialName: "Fairfield by Marriott Beijing Haidian" },
  { id: "BJSIM", officialName: "The Imperial Mansion, Beijing Marriott Executive Apartments" },
  { id: "BJSPF", officialName: "Four Points by Sheraton Beijing Fangshan" },
  { id: "BJSSW", officialName: "The Sandalwood, Beijing - Marriott Executive Apartments" },
  { id: "BJSBC", officialName: "Renaissance Beijing Capital Hotel" },
  { id: "BJSJC", officialName: "JW Marriott Hotel Beijing Central" },
  { id: "HFEBL", officialName: "Fairfield by Marriott Bengbu Longzihu" },
  { id: "BFJFI", officialName: "Fairfield by Marriott Bijie" },
  { id: "BPLAC", officialName: "AC Hotel Xinjiang Sayram Lake" },
  { id: "YNJSI", officialName: "Sheraton Changbaishan Resort" },
  { id: "TNHWI", officialName: "The Westin Changbaishan Resort" },
  { id: "CGQUW", officialName: "Four Points by Sheraton Changchun West" },
  { id: "CGQCY", officialName: "Courtyard by Marriott Changchun" },
  { id: "CGQJF", officialName: "Fairfield by Marriott Changchun Jingyue High-Tech Zone" },
  { id: "CGQCF", officialName: "Fairfield by Marriott Changchun Chaoyang" },
  { id: "CGQSI", officialName: "Sheraton Changchun Jingyuetan Hotel" },
  { id: "CGQFP", officialName: "Four Points by Sheraton Changchun, Hi-Tech Zone" },
  { id: "CGDSI", officialName: "Sheraton Changde Wuling Hotel" },
  { id: "CSXLC", officialName: "Meixi Lake Hotel, a Luxury Collection Hotel, Changsha" },
  { id: "CSXER", officialName: "The Meixi Lake, Changsha Marriott Executive Apartments" },
  { id: "CSXYF", officialName: "Fairfield by Marriott Changsha Yuelu" },
  { id: "CSXCY", officialName: "Courtyard by Marriott Changsha South" },
  { id: "CSXCW", officialName: "Changsha Marriott Hotel West" },
  { id: "CSXSI", officialName: "Sheraton Changsha Hotel" },
  { id: "CSXFP", officialName: "Four Points by Sheraton Changsha, Meixi Lake" },
  { id: "CSXJC", officialName: "JW Marriott Hotel Changsha" },
  { id: "CSXNF", officialName: "Fairfield By Marriott Ningxiang" },
  { id: "CSXXR", officialName: "The St. Regis Changsha" },
  { id: "CSXCT", officialName: "Four Points by Sheraton Changsha, Tianxin" },
  { id: "CSXSW", officialName: "The Westin Changsha" },
  { id: "CSXTF", officialName: "Fairfield by Marriott Changsha Tianxin" },
  { id: "CSXWH", officialName: "W Changsha" },
  { id: "WUXCF", officialName: "Fairfield by Marriott Changshu Hi-Tech Zone" },
  { id: "CZXMJ", officialName: "Changzhou Marriott Hotel Jintan" },
  { id: "CZXCM", officialName: "Le Méridien Changzhou" },
  { id: "CZXQL", officialName: "The QuchanInner Liyang, Autograph Collection" },
  { id: "CZXSX", officialName: "Sheraton Changzhou Xinbei Hotel" },
  { id: "CZXYC", officialName: "Courtyard by Marriott Changzhou China" },
  { id: "CZXWS", officialName: "Sheraton Changzhou Wujin Hotel" },
  { id: "CZXFJ", officialName: "Fairfield by Marriott Changzhou Jintan" },
  { id: "CZXLF", officialName: "Fairfield by Marriott Changzhou Liyang" },
  { id: "CZXFP", officialName: "Four Points by Sheraton Changzhou Economic Development Zone" },
  { id: "CZXBR", officialName: "Renaissance Changzhou Wujin Hotel" },
  { id: "CZXMC", officialName: "Changzhou Marriott Hotel" },
  { id: "CTUKM", officialName: "Four Points by Sheraton Chengdu Kuanzhai Alley" },
  { id: "CTUEP", officialName: "Four Points by Sheraton Chengdu East Station" },
  { id: "CTUPH", officialName: "Four Points by Sheraton Chengdu, High-Tech Zone Exhibition Center" },
  { id: "CTULS", officialName: "Sheraton Chengdu Lido Hotel" },
  { id: "CTUTF", officialName: "Fairfield by Marriott Chengdu Tianfu Square" },
  { id: "CTURZ", officialName: "The Ritz-Carlton, Chengdu" },
  { id: "CTUSP", officialName: "Sheraton Chengdu Pidu" },
  { id: "CTUFP", officialName: "Four Points by Sheraton Chengdu, Pujiang Resort" },
  { id: "CTUMC", officialName: "Chengdu Marriott Hotel Financial Centre" },
  { id: "CTUAF", officialName: "Four Points by Sheraton Chengdu, Anren" },
  { id: "CTUCS", officialName: "Courtyard by Marriott Chengdu South" },
  { id: "CTUBR", officialName: "Renaissance Chengdu Hotel" },
  { id: "CTUAC", officialName: "AC Hotel Chengdu North" },
  { id: "CTUFH", officialName: "Fairfield by Marriott Chengdu Hi-Tech Zone" },
  { id: "CTUXR", officialName: "The St. Regis Chengdu" },
  { id: "CTUWH", officialName: "W Chengdu" },
  { id: "CTUUC", officialName: "Four Points by Sheraton Chengdu, Chunxi Road" },
  { id: "CTUMJ", officialName: "JW Marriott Hotel Chengdu" },
  { id: "CTUFT", officialName: "Four Points by Sheraton Chengdu Tianfu New Area" },
  { id: "CKGFP", officialName: "Four Points by Sheraton Chongqing" },
  { id: "CKGJP", officialName: "Four Points by Sheraton Chongqing Jiulongpo" },
  { id: "CKGGB", officialName: "MajesTang Hotel, Chongqing, a Tribute Portfolio Hotel" },
  { id: "CKGMD", officialName: "Le Méridien Chongqing, Nan'an" },
  { id: "CKGJU", officialName: "Four Points by Sheraton Chongqing Jiangjin" },
  { id: "CKGFY", officialName: "Four Points by Sheraton Chongqing, Yongchuan" },
  { id: "CKGER", officialName: "Marriott Executive Apartments Chongqing" },
  { id: "CKGFI", officialName: "Fairfield by Marriott Chongqing Yongchuan" },
  { id: "CKGFN", officialName: "Fairfield by Marriott Chongqing Nan’an District" },
  { id: "CKGNP", officialName: "Four Points by Sheraton Chongqing Nanchuan" },
  { id: "CKGNU", officialName: "Four Points by Sheraton Chongqing North Railway Station" },
  { id: "CKGOX", officialName: "Moxy Chongqing" },
  { id: "CKGYF", officialName: "Fairfield by Marriott Chongqing Yubei" },
  { id: "CKGCY", officialName: "Courtyard by Marriott Chongqing Jiangjin" },
  { id: "CKGJW", officialName: "JW Marriott Hotel Chongqing" },
  { id: "CKGWI", officialName: "The Westin Chongqing Liberation Square" },
  { id: "CKGMC", officialName: "Chongqing Marriott Hotel" },
  { id: "CKGLN", officialName: "Four Points by Sheraton Chongqing Liangjiang New Area Jinkai Avenue" },
  { id: "CKGYP", officialName: "Four Points by Sheraton Chongqing Yuzhong Peninsula" },
  { id: "CKGSI", officialName: "Sheraton Chongqing Hotel" },
  { id: "NKGZS", officialName: "Sheraton Chuzhou Hotel" },
  { id: "NKGCF", officialName: "Fairfield by Marriott Chuzhou Railway Station" },
  { id: "CMHFB", officialName: "Fairfield by Marriott Inn & Suites Columbus New Albany" },
  { id: "DLUEU", officialName: "Four Points by Sheraton Dali, Erhai" },
  { id: "DLUEB", officialName: "The Dali EDITION" },
  { id: "DLCLC", officialName: "The Castle Hotel, a Luxury Collection Hotel, Dalian" },
  { id: "DLCJF", officialName: "Fairfield by Marriott Dalian Jinpu New Area" },
  { id: "DLCAL", officialName: "Aloft Dalian" },
  { id: "DLCDP", officialName: "Four Points by Sheraton Dalian Donggang" },
  { id: "CZXFD", officialName: "Fairfield by Marriott Danyang" },
  { id: "CGDFP", officialName: "Four Points by Sheraton Danzhou" },
  { id: "DQASI", officialName: "Sheraton Daqing Hotel" },
  { id: "DATFP", officialName: "Four Points by Sheraton Datong Pingcheng" },
  { id: "DATFI", officialName: "Fairfield by Marriott Datong" },
  { id: "SZXAL", officialName: "Aloft Dongguan Songshan Lake" },
  { id: "SZXFI", officialName: "Fairfield by Marriott Dongguan Changping" },
  { id: "SZXDM", officialName: "Dongguan Marriott Hotel" },
  { id: "SZXSI", officialName: "Sheraton Dongguan Hotel" },
  { id: "DNHFP", officialName: "Four Points by Sheraton Dunhuang" },
  { id: "CTUMD", officialName: "Le Méridien Emei Mountain Resort" },
  { id: "SHAFN", officialName: "Courtyard by Marriott Shanghai Fengxian" },
  { id: "FUOCF", officialName: "Courtyard by Marriott Foshan" },
  { id: "FUOAL", officialName: "Aloft Nanhai, Foshan" },
  { id: "FUOGA", officialName: "Courtyard by Marriott Foshan Gaoming" },
  { id: "FUOFI", officialName: "Fairfield by Marriott Foshan Nanhai" },
  { id: "CANSM", officialName: "Shunde Marriott Hotel" },
  { id: "FUOMC", officialName: "Foshan Marriott Hotel" },
  { id: "SZXTX", officialName: "Midea Shunde, a Tribute Portfolio Hotel" },
  { id: "FUOSC", officialName: "Courtyard by Marriott Shunde" },
  { id: "FUOCY", officialName: "Courtyard by Marriott Shunde Longjiang" },
  { id: "FUOSI", officialName: "Sheraton Shunde Hotel" },
  { id: "FUOFU", officialName: "Fairfield by Marriott Shunde" },
  { id: "FOCSF", officialName: "Sheraton Fuqing Hotel" },
  { id: "FOCCP", officialName: "Four Points by Sheraton Fuzhou Changle" },
  { id: "FOCSI", officialName: "Sheraton Fuzhou Hotel" },
  { id: "FOCMC", officialName: "Fuzhou Marriott Hotel Riverside" },
  { id: "FOCFI", officialName: "The Westin Fuzhou Minjiang" },
  { id: "FOCJP", officialName: "Four Points by Sheraton Fuzhou, Jin’an" },
  { id: "FOCTF", officialName: "Fairfield by Marriott Fuzhou Taijiang" },
  { id: "KOWAC", officialName: "AC Hotel Ganzhou Quannan" },
  { id: "CANTI", officialName: "Guangzhou Marriott Hotel Tianhe" },
  { id: "CANMN", officialName: "Guangzhou Marriott Hotel Nansha" },
  { id: "CANHN", officialName: "Four Points by Sheraton Guangzhou, Huangpu New City" },
  { id: "CANSS", officialName: "Four Points by Sheraton Guangzhou South Station" },
  { id: "CANSP", officialName: "Sheraton Guangzhou Panyu" },
  { id: "CANUL", officialName: "Aloft Guangzhou University Park" },
  { id: "CANHF", officialName: "Fairfield by Marriott Guangzhou Huadu" },
  { id: "CANKF", officialName: "Fairfield by Marriott Guangzhou Konggang" },
  { id: "CANRZ", officialName: "The Ritz-Carlton, Guangzhou" },
  { id: "CANBP", officialName: "Four Points by Sheraton Guangzhou, Baiyun" },
  { id: "CANBE", officialName: "Element Guangzhou Baiyun" },
  { id: "CANFP", officialName: "Four Points by Sheraton Guangzhou Financial City, Tianhe" },
  { id: "CANBM", officialName: "Guangzhou Marriott Hotel Baiyun" },
  { id: "CANBU", officialName: "Four Points by Sheraton Guangzhou Bai’e Tan" },
  { id: "CANCW", officialName: "Four Points by Sheraton Guangzhou Changlong Wanbo Business District" },
  { id: "CANFI", officialName: "Fairfield by Marriott Guangzhou Tianhe Park" },
  { id: "CANSI", officialName: "Sheraton Guangzhou Hotel" },
  { id: "CANWI", officialName: "The Westin Pazhou" },
  { id: "CANYP", officialName: "Courtyard by Marriott Guangzhou Pazhou" },
  { id: "CANGN", officialName: "Sheraton Guangzhou Nansha Hotel" },
  { id: "CANGW", officialName: "The Westin Guangzhou" },
  { id: "CANWG", officialName: "W Guangzhou" },
  { id: "CANHP", officialName: "Four Points by Sheraton Guangzhou Huangpu" },
  { id: "KWLAY", officialName: "Aurua Yangshuo Sugar House, a Member of Design Hotels" },
  { id: "KWLCD", officialName: "Courtyard by Marriott Guilin Downtown" },
  { id: "KWLFP", officialName: "Four Points by Sheraton Guilin, Lingui" },
  { id: "KWLDP", officialName: "Four Points by Sheraton Guilin Central" },
  { id: "KWLSI", officialName: "Sheraton Guilin Hotel" },
  { id: "KWLYF", officialName: "Fairfield by Marriott Yangshuo" },
  { id: "KWESI", officialName: "Sheraton Guiyang Hotel" },
  { id: "KWEBR", officialName: "Renaissance Guiyang Hotel" },
  { id: "KWEHP", officialName: "Four Points by Sheraton Guiyang Shilihetan" },
  { id: "KWEFI", officialName: "Fairfield by Marriott Guiyang Guanshanhu" },
  { id: "KWEGG", officialName: "Four Points by Sheraton Guiyang Guanshanhu" },
  { id: "KWEFH", officialName: "Four Points by Sheraton Guiyang, Huaxi" },
  { id: "XNNFH", officialName: "Fairfield by Marriott Haidong" },
  { id: "HAKRZ", officialName: "The Ritz-Carlton, Haikou" },
  { id: "HAKSI", officialName: "Sheraton Haikou Hotel" },
  { id: "HAKMC", officialName: "Haikou Marriott Hotel" },
  { id: "HAKMF", officialName: "Fairfield by Marriott Haikou Meilan" },
  { id: "HAKWI", officialName: "The Westin Haikou" },
  { id: "HAKMH", officialName: "Renaissance Haikou Hotel" },
  { id: "HAKAP", officialName: "Four Points by Sheraton Haikou International Airport" },
  { id: "HGHXP", officialName: "Four Points by Sheraton Hangzhou Xihu District Xixi Wetland" },
  { id: "HGHYF", officialName: "Fairfield by Marriott Hangzhou Yuhang" },
  { id: "HGHSI", officialName: "Sheraton Grand Hangzhou Binjiang Hotel" },
  { id: "HGHQJ", officialName: "Courtyard by Marriott Hangzhou Qianjiang" },
  { id: "HGHSF", officialName: "Sheraton Hangzhou Fuyang" },
  { id: "HGHML", officialName: "Hangzhou Marriott Hotel Lin'an" },
  { id: "HGHQF", officialName: "Fairfield by Marriott Hangzhou Qiandao Lake" },
  { id: "HGHQI", officialName: "Hangzhou Marriott Hotel Qianjiang" },
  { id: "HGHWB", officialName: "Wonderland Resort, Hangzhou Jiande, A Tribute Portfolio Resort" },
  { id: "HGHLC", officialName: "The Azure Qiantang, a Luxury Collection Hotel, Hangzhou" },
  { id: "HGHXC", officialName: "Courtyard by Marriott Hangzhou Xihu" },
  { id: "HGHJW", officialName: "JW Marriott Hotel Hangzhou" },
  { id: "HGHMD", officialName: "Le Méridien Hangzhou, Binjiang" },
  { id: "HGHNE", officialName: "Renaissance Hangzhou Northeast Hotel" },
  { id: "HGHAC", officialName: "AC Hotel by Marriott Hangzhou" },
  { id: "HGHBA", officialName: "AC Hotels by Marriott Hangzhou Binjiang" },
  { id: "HGHBF", officialName: "Fairfield by Marriott Hangzhou Binjiang Puyan" },
  { id: "HGHCW", officialName: "Courtyard by Marriott Hangzhou West" },
  { id: "HGHCX", officialName: "Courtyard by Marriott Hangzhou Xiaoshan" },
  { id: "HGHBL", officialName: "Renaissance Hangzhou Lin'an Hotel" },
  { id: "HGHHF", officialName: "Fairfield by Marriott Hangzhou Xihu District" },
  { id: "HGHCC", officialName: "Renaissance Hangzhou Qianjiang Century City Hotel" },
  { id: "HGHEZ", officialName: "Marriott Executive Apartments Hangzhou" },
  { id: "HGHFW", officialName: "Fairfield by Marriott Hangzhou Wulin Square, China" },
  { id: "HGHCY", officialName: "Courtyard by Marriott Hangzhou Wulin" },
  { id: "HGHFP", officialName: "Four Points by Sheraton Hangzhou, Binjiang" },
  { id: "HGHER", officialName: "Marriott Executive Apartments Hangzhou Yuhang" },
  { id: "HGHGB", officialName: "Grand New Century Hotel, Hangzhou Boao, A Tribute Portfolio Hotel" },
  { id: "HGHJF", officialName: "Fairfield by Marriott Hangzhou Qiantang" },
  { id: "HGHFF", officialName: "Fairfield by Marriott Hangzhou Future Sci-tech City" },
  { id: "HGHFQ", officialName: "Four Points by Sheraton Qiandao Lake" },
  { id: "HGHGF", officialName: "Fairfield by Marriott Hangzhou Gongshu" },
  { id: "HGHHS", officialName: "Sheraton Grand Hangzhou Wetland Park Resort" },
  { id: "HGHFG", officialName: "Fairfield by Marriott Hangzhou Xiaoshan" },
  { id: "HGHZF", officialName: "Fairfield by Marriott Hangzhou Zhuantang" },
  { id: "HZGFP", officialName: "Four Points by Sheraton Hanzhong Riverside" },
  { id: "HRBJW", officialName: "JW Marriott Hotel Harbin River North" },
  { id: "HRBFP", officialName: "Four Points by Sheraton Harbin City Center" },
  { id: "HRBFI", officialName: "Fairfield by Marriott Harbin Downtown" },
  { id: "HRBXS", officialName: "Sheraton Harbin Xiangfang Hotel" },
  { id: "HRBRZ", officialName: "The Ritz-Carlton, Harbin" },
  { id: "HFEPF", officialName: "Four Points by Sheraton Hefei, Feidong" },
  { id: "HFEFP", officialName: "Four Points by Sheraton Hefei, Shushan" },
  { id: "HFEHF", officialName: "Four Points by Sheraton Hefei, Baohe" },
  { id: "HFESI", officialName: "Sheraton Hefei Xinzhan Hotel" },
  { id: "HFEPH", officialName: "Four Points by Sheraton Hefei High-Tech Zone" },
  { id: "HFEWI", officialName: "The Westin Hefei" },
  { id: "HNYFP", officialName: "Four Points by Sheraton Hengyang Zhengxiang" },
  { id: "CANFG", officialName: "Four Points by Sheraton Guangdong, Heshan" },
  { id: "HUZFP", officialName: "Four Points by Sheraton Heyuan Resort" },
  { id: "HETSI", officialName: "Sheraton Hohhot Hotel" },
  { id: "HKGAP", officialName: "Hong Kong SkyCity Marriott Hotel" },
  { id: "HKGXR", officialName: "The St. Regis Hong Kong" },
  { id: "HKGSC", officialName: "Sheraton Hong Kong Tung Chung Hotel" },
  { id: "HKGSI", officialName: "Sheraton Hong Kong Hotel & Towers" },
  { id: "HKGCY", officialName: "Courtyard by Marriott Hong Kong" },
  { id: "HKGHV", officialName: "Renaissance Hong Kong Harbour View Hotel" },
  { id: "HKGDT", officialName: "JW Marriott Hotel Hong Kong" },
  { id: "HKGKW", officialName: "The Ritz-Carlton, Hong Kong" },
  { id: "HKGAK", officialName: "The Park Lane Hong Kong, Autograph Collection" },
  { id: "HKGWH", officialName: "W Hong Kong" },
  { id: "HKGFP", officialName: "Four Points by Sheraton Hong Kong, Tung Chung" },
  { id: "HKGOP", officialName: "Hong Kong Ocean Park Marriott Hotel" },
  { id: "HKGST", officialName: "Courtyard by Marriott Hong Kong Sha Tin" },
  { id: "HKGMM", officialName: "Mira Moon Hong Kong, a Member of Design Hotels™" },
  { id: "HKGMR", officialName: "The Mira Hong Kong, a Member of Design Hotels™" },
  { id: "HKGMD", officialName: "Le Méridien Hong Kong, Cyberport" },
  { id: "HOURN", officialName: "Residence Inn by Marriott Houston Northwest/Cypress" },
  { id: "HIAFD", officialName: "Fairfield by Marriott Huai'an Downtown" },
  { id: "EHUDF", officialName: "Fairfield by Marriott Huangshi Development Zone" },
  { id: "HUZSB", officialName: "Sheraton Huizhou Bailuhu" },
  { id: "HUZBR", officialName: "Renaissance Huizhou Hotel" },
  { id: "HUZLM", officialName: "Le Méridien Xiaojing Bay" },
  { id: "WUXSI", officialName: "Sheraton Huzhou Taihu Lake Hot Spring Resort & Spa" },
  { id: "HGHAY", officialName: "Courtyard by Marriott Anji" },
  { id: "HGHHA", officialName: "Aloft Huzhou" },
  { id: "HGHCG", officialName: "Grand New Century Resort, Changxing, A Tribute Portfolio Resort" },
  { id: "HGHDM", officialName: "Deqing Marriott Hotel" },
  { id: "HGHDF", officialName: "Fairfield by Marriott Deqing" },
  { id: "WUXHF", officialName: "Fairfield by Marriott Huzhou Nanxun" },
  { id: "WUXHM", officialName: "Huzhou Marriott Hotel Nanxun" },
  { id: "WUXHP", officialName: "Four Points by Sheraton Huzhou" },
  { id: "WUXNP", officialName: "Four Points by Sheraton Huzhou, Nanxun" },
  { id: "ZFLFP", officialName: "Four Points by Sheraton Zhaosu" },
  { id: "JGSJP", officialName: "Four Points by Sheraton Ji’an" },
  { id: "JGSFI", officialName: "Fairfield By Marriott Jian Anfu" },
  { id: "FUOJP", officialName: "Four Points by Sheraton Jiangmen Downtown" },
  { id: "FUOTF", officialName: "Fairfield by Marriott Taishan" },
  { id: "CZXCJ", officialName: "Courtyard by Marriott Jiangyin" },
  { id: "WUXJS", officialName: "Sheraton Jiangyin Hotel" },
  { id: "HGHPJ", officialName: "Four Points by Sheraton Jiaxing" },
  { id: "HGHJP", officialName: "Four Points by Sheraton Haiyan" },
  { id: "HGHJX", officialName: "Jiaxing Marriott Hotel" },
  { id: "SWAJM", officialName: "Jieyang Marriott Hotel" },
  { id: "TNAJS", officialName: "Sheraton Jinan Hotel" },
  { id: "TNAPH", officialName: "Four Points by Sheraton Jinan, High-Tech Zone" },
  { id: "JDZFI", officialName: "Fairfield by Marriott Jingdezhen" },
  { id: "JHGXP", officialName: "Four Points by Sheraton Xishuangbanna" },
  { id: "JHGSI", officialName: "Sheraton Grand Xishuangbanna Hotel" },
  { id: "WHAXP", officialName: "Four Points by Sheraton Xuancheng, Jingxian" },
  { id: "SHSJP", officialName: "Four Points by Sheraton Jingzhou Downtown" },
  { id: "YIHFI", officialName: "Fairfield by Marriott Jingzhou" },
  { id: "YIWSI", officialName: "Sheraton Pujiang" },
  { id: "YIWFI", officialName: "Fairfield by Marriott Pujiang" },
  { id: "YIWMJ", officialName: "Jinhua Marriott Hotel" },
  { id: "YIWHF", officialName: "Fairfield by Marriott Hengdian" },
  { id: "TYNJS", officialName: "Sheraton Jinzhong" },
  { id: "JNZSI", officialName: "Sheraton Jinzhou Hotel" },
  { id: "JIUSI", officialName: "Sheraton Jiujiang" },
  { id: "JZHDE", officialName: "Delta Hotels Jiuzhaigou" },
  { id: "JZHRZ", officialName: "Rissai Valley, a Ritz-Carlton Reserve" },
  { id: "JZHCY", officialName: "Courtyard by Marriott Jiuzhaigou" },
  { id: "CGOSK", officialName: "Sheraton Kaifeng" },
  { id: "KHGFP", officialName: "Four Points by Sheraton Kashgar" },
  { id: "KRLBR", officialName: "Renaissance Hotel Korla" },
  { id: "KRLCY", officialName: "Courtyard by Marriott Korla" },
  { id: "KMGPI", officialName: "Four Points by Sheraton Kunming, International Convention & Exhibition Center" },
  { id: "KMGDE", officialName: "Delta Hotels Kunming" },
  { id: "KMGFI", officialName: "Fairfield by Marriott Kunming Xinying" },
  { id: "KMGCP", officialName: "Four Points by Sheraton Kunming Chenggong" },
  { id: "KMGDU", officialName: "Four Points by Sheraton Kunming Dongfeng Square" },
  { id: "KMGGU", officialName: "Four Points by Sheraton Kunming Guandu" },
  { id: "KMGPD", officialName: "Four Points by Sheraton Kunming, Downtown" },
  { id: "KMGXF", officialName: "Fairfield by Marriott Kunming Xishan" },
  { id: "KMGAP", officialName: "Four Points by Sheraton Kunming Changshui Airport" },
  { id: "KMGSK", officialName: "Sheraton Kunming" },
  { id: "SHAKA", officialName: "Aloft Kunshan Dianshan Lake" },
  { id: "SHAKH", officialName: "Sheraton Kunshan Dianshan Lake" },
  { id: "SHAKP", officialName: "Four Points by Sheraton Kunshan" },
  { id: "SHAKS", officialName: "Courtyard by Marriott Kunshan" },
  { id: "SHAFU", officialName: "Fairfield by Marriott Kunshan" },
  { id: "BJSLY", officialName: "Courtyard by Marriott Langfang" },
  { id: "BJSLF", officialName: "Sheraton Langfang Chaobai River Hotel" },
  { id: "BJSFL", officialName: "Four Points by Sheraton Langfang, Guan" },
  { id: "LHWAS", officialName: "Sheraton Lanzhou Anning" },
  { id: "CTULW", officialName: "Four Points by Sheraton Leshan" },
  { id: "LXAXR", officialName: "The St. Regis Lhasa Resort" },
  { id: "LJGAL", officialName: "The ArcadiaPlace, Lugu Lake, a Member of Design Hotels" },
  { id: "LJGJP", officialName: "Jinmao Pureal Mountain Lijiang, a Member of Design Hotels™" },
  { id: "LYGDP", officialName: "Four Points by Sheraton Lianyungang Downtown" },
  { id: "LYGFP", officialName: "Four Points by Sheraton Lianyungang" },
  { id: "TNAFD", officialName: "Fairfield by Marriott Liaocheng Dongchangfu" },
  { id: "LJGFI", officialName: "Fairfield by Marriott Lijiang Ancient Town" },
  { id: "SYXWI", officialName: "The Westin Blue Bay Resort & Spa" },
  { id: "SYXXB", officialName: "Marriott Resort Xiangshui Bay" },
  { id: "HYNLU", officialName: "Four Points by Sheraton Linhai" },
  { id: "LYIPC", officialName: "​Four Points by Sheraton Linyi City Center" },
  { id: "LYIBF", officialName: "Fairfield by Marriott Linyi Beicheng New District" },
  { id: "LYIHP", officialName: "Four Points by Sheraton Linyi Hedong" },
  { id: "YIWLE", officialName: "Element Lishui" },
  { id: "WNZFP", officialName: "Four Points by Sheraton Qingtian" },
  { id: "YIWLM", officialName: "Lishui Marriott Hotel" },
  { id: "LPFFP", officialName: "Four Points by Sheraton Liupanshui" },
  { id: "LZHCY", officialName: "Courtyard by Marriott Liuzhou Sanjiang" },
  { id: "NKGML", officialName: "Liyang Marriott Hotel" },
  { id: "LYABP", officialName: "Four Points by Sheraton Luoyang Central Business District" },
  { id: "LYAFP", officialName: "Four Points by Sheraton Luohe" },
  { id: "LYASI", officialName: "Sheraton Luoyang" },
  { id: "LYACY", officialName: "Courtyard by Marriott Luoyang" },
  { id: "LYAMC", officialName: "Luoyang Marriott Hotel" },
  { id: "MFMWH", officialName: "W Macau - Studio City" },
  { id: "MFMLC", officialName: "Londoner Grand, a Luxury Collection Hotel, Macao" },
  { id: "MFMMR", officialName: "The Ritz-Carlton, Macau" },
  { id: "MFMXR", officialName: "The St. Regis Macao" },
  { id: "MFMJW", officialName: "JW Marriott Hotel Macau" },
  { id: "ZHASM", officialName: "Sheraton Maoming Romantic Beach Resort" },
  { id: "ZHAMP", officialName: "Four Points by Sheraton Maoming" },
  { id: "ZHAMS", officialName: "Sheraton Maoming Hot Spring Resort" },
  { id: "MIGFP", officialName: "Four Points by Sheraton Mianyang" },
  { id: "MIGSI", officialName: "Sheraton Mianyang" },
  { id: "KMGEL", officialName: "Element Mile" },
  { id: "KMGSI", officialName: "Sheraton Mile Hotel" },
  { id: "KHNYC", officialName: "Courtyard by Marriott Nanchang" },
  { id: "KHNSI", officialName: "Sheraton Nanchang Hotel" },
  { id: "KHNXF", officialName: "Four Points by Sheraton Nanchang, Xihu" },
  { id: "NKGNJ", officialName: "Courtyard by Marriott Nanjing Jiangning" },
  { id: "NKGAR", officialName: "Nanjing, Jiangning, Autograph Collection" },
  { id: "NKGAK", officialName: "The Sifang Hotel Nanjing, Autograph Collection" },
  { id: "NKGSC", officialName: "Marriott Nanjing South Hotel" },
  { id: "NKGWN", officialName: "The Westin Nanjing Resort & Spa" },
  { id: "NKGYF", officialName: "Fairfield by Marriott Nanjing Yuhuatai" },
  { id: "NKGGP", officialName: "Four Points by Sheraton Nanjing, Gulou District" },
  { id: "NKGBR", officialName: "Renaissance Nanjing Olympic Centre Hotel" },
  { id: "NKGSI", officialName: "Sheraton Nanjing Kingsley Hotel & Towers" },
  { id: "NKGWI", officialName: "The Westin Nanjing Xuanwu Lake" },
  { id: "NKGOX", officialName: "Moxy Nanjing Jiangning" },
  { id: "NKGRZ", officialName: "The Ritz-Carlton, Nanjing" },
  { id: "NNGBR", officialName: "Renaissance Nanning Hotel" },
  { id: "NNGCY", officialName: "Courtyard by Marriott Nanning Wuxiang" },
  { id: "NNGFP", officialName: "Four Points by Sheraton Nanning, Wuxiang" },
  { id: "NNGMC", officialName: "Nanning Marriott Hotel" },
  { id: "NNGLC", officialName: "Na Lotus Hotel, a Luxury Collection Hotel, Nanning" },
  { id: "NTGMC", officialName: "Nantong Marriott Hotel" },
  { id: "NTGCY", officialName: "Courtyard by Marriott Nantong" },
  { id: "NTGMD", officialName: "Le Meridien Nantong" },
  { id: "NTGFP", officialName: "Four Points by Sheraton Nantong, Haimen" },
  { id: "NGBWI", officialName: "The Westin Ningbo" },
  { id: "NGBMC", officialName: "Ningbo Marriott Hotel" },
  { id: "NGBNG", officialName: "Sheraton Ninghai" },
  { id: "NGBOX", officialName: "Moxy Ningbo Old Bund" },
  { id: "NGBSI", officialName: "Sheraton Ningbo Hotel" },
  { id: "NGBYS", officialName: "Sheraton Ningbo Yinzhou" },
  { id: "NGBXI", officialName: "Sheraton Ningbo Xiangshan Resort" },
  { id: "NGBFI", officialName: "Fairfield by Marriott Ningbo Yinzhou" },
  { id: "FOCXY", officialName: "Courtyard by Marriott Xiapu" },
  { id: "FOCNF", officialName: "Fairfield by Marriott Ningde Xiapu" },
  { id: "SHAPC", officialName: "Courtyard by Marriott Pinghu" },
  { id: "HGHQS", officialName: "Sheraton Qiandao Lake Resort" },
  { id: "TAOQS", officialName: "Sheraton Qingdao Licang Hotel" },
  { id: "TAOQJ", officialName: "Sheraton Qingdao Jiaozhou Hotel" },
  { id: "TAOWI", officialName: "The Westin Qingdao" },
  { id: "TAOQF", officialName: "Four Points by Sheraton Qingdao, West Coast" },
  { id: "TAOWQ", officialName: "The Westin Qingdao West Coast" },
  { id: "TAOBR", officialName: "Renaissance Qingdao Hotel" },
  { id: "TAOCE", officialName: "Four Points by Sheraton Qingdao, Chengyang East" },
  { id: "TAOXR", officialName: "The St. Regis Qingdao" },
  { id: "TAOAK", officialName: "Flow and Co. Qingdao, Autograph Collection" },
  { id: "TAOZY", officialName: "Qingdao Zhanqiao Yours Hotel, a Member of Design Hotels™" },
  { id: "TAOMD", officialName: "Le Méridien Qingdao" },
  { id: "TAOFP", officialName: "Four Points by Sheraton Qingdao, Chengyang" },
  { id: "TAODM", officialName: "Le Méridien Qingdao West Coast" },
  { id: "TAOCF", officialName: "Fairfield by Marriott Qingdao West Coast" },
  { id: "TAOMC", officialName: "Qingdao Marriott Hotel Jiaozhou" },
  { id: "TNAHU", officialName: "Sheraton Qingdao West Coast" },
  { id: "TAOEL", officialName: "Element Qingdao" },
  { id: "TAOJP", officialName: "Four Points by Sheraton Qingdao, Jiaozhou" },
  { id: "TAOSI", officialName: "Sheraton Qingyuan Lion Lake Resort" },
  { id: "BPEMC", officialName: "Qinhuangdao Marriott Resort" },
  { id: "SHPCY", officialName: "Courtyard by Marriott Qinhuangdao West" },
  { id: "SHPSI", officialName: "Sheraton Qinhuangdao Beidaihe Hotel" },
  { id: "SHPFI", officialName: "Fairfield by Marriott Qinhuangdao Haigang" },
  { id: "SYXFQ", officialName: "Four Points by Sheraton Hainan, Qiongzhong" },
  { id: "JJNFF", officialName: "Fairfield by Marriott Quanzhou Fengze" },
  { id: "JJNHP", officialName: "Four Points by Sheraton Quanzhou Huian" },
  { id: "JNGJW", officialName: "JW Marriott Hotel Qufu" },
  { id: "RIZPC", officialName: "Four Points by Sheraton Rizhao Central Activities Zone" },
  { id: "RIZCY", officialName: "Courtyard by Marriott Rizhao" },
  { id: "TNASR", officialName: "Sheraton Rizhao Hotel" },
  { id: "RIZFP", officialName: "Four Points by Sheraton Rizhao" },
  { id: "SYXRZ", officialName: "The Ritz-Carlton Sanya, Yalong Bay" },
  { id: "SYXXR", officialName: "The St. Regis Sanya Yalong Bay Resort" },
  { id: "SYXHS", officialName: "Sheraton Sanya Haitang Bay Resort" },
  { id: "SYXEB", officialName: "The Sanya EDITION" },
  { id: "SYXJW", officialName: "JW Marriott Sanya Haitang Bay Resort & Spa" },
  { id: "SYXDB", officialName: "JW Marriott Hotel Sanya Dadonghai Bay" },
  { id: "SYXFP", officialName: "Four Points by Sheraton Hainan, Sanya" },
  { id: "SYXAK", officialName: "The Shanhaitian Resort Sanya, Autograph Collection" },
  { id: "SYXBR", officialName: "Renaissance Sanya Haitang Bay Resort" },
  { id: "SYXBW", officialName: "The Westin Sanya Haitang Bay Resort" },
  { id: "SYXSS", officialName: "Sheraton Sanya Resort" },
  { id: "SYXTX", officialName: "The Taikang Sanya, a Tribute Portfolio Resort" },
  { id: "SYXMC", officialName: "Sanya Marriott Yalong Bay Resort & Spa" },
  { id: "SHAPR", officialName: "Sheraton Shanghai Pudong Riverside" },
  { id: "SHAFG", officialName: "Four Points by Sheraton Shanghai Fengjing" },
  { id: "SHAPX", officialName: "Courtyard by Marriott Shanghai Central" },
  { id: "SHAFJ", officialName: "Four Points by Sheraton Shanghai Jiading" },
  { id: "SHAMJ", officialName: "JW Marriott Marquis Hotel Shanghai Pudong" },
  { id: "SHALM", officialName: "Le Méridien Shanghai, Minhang" },
  { id: "SHAWH", officialName: "W Shanghai - The Bund" },
  { id: "SHASH", officialName: "Sheraton Shanghai Chongming Hotel" },
  { id: "SHAMC", officialName: "Shanghai Marriott Marquis City Centre" },
  { id: "SHAXS", officialName: "Aqua Caeli Hotel, Shanghai Fengjing, a Tribute Portfolio Hotel" },
  { id: "SHARZ", officialName: "The Portman Ritz-Carlton, Shanghai" },
  { id: "SHAJS", officialName: "Sheraton Shanghai Jiading Hotel" },
  { id: "SHAZR", officialName: "Marriott Executive Apartments Shanghai, Zhangjiang" },
  { id: "SHAWI", officialName: "The Westin Bund Center, Shanghai" },
  { id: "SHAMP", officialName: "Shanghai Marriott Hotel Parkview" },
  { id: "SHAAL", officialName: "Aloft Shanghai Zhangjiang Haike" },
  { id: "SHAWS", officialName: "Sheraton Shanghai Waigaoqiao Hotel" },
  { id: "SHAFO", officialName: "Fairfield by Marriott Shanghai Hongqiao NECC" },
  { id: "SHAHF", officialName: "Fairfield by Marriott Shanghai Hongqiao" },
  { id: "SHANS", officialName: "Sheraton Shanghai North Bund" },
  { id: "SHAOX", officialName: "Moxy Shanghai Hongqiao NECC" },
  { id: "SHAXR", officialName: "The St. Regis Shanghai Jingan" },
  { id: "SHACJ", officialName: "Courtyard by Marriott Shanghai Songjiang" },
  { id: "SHAFP", officialName: "Courtyard by Marriott Shanghai Changfeng Park" },
  { id: "SHADF", officialName: "Four Points by Sheraton Shanghai, Daning" },
  { id: "SHAEB", officialName: "The Shanghai EDITION" },
  { id: "SHAPD", officialName: "Shanghai Marriott Hotel Pudong East" },
  { id: "SHABZ", officialName: "Renaissance Shanghai Zhongshan Park Hotel" },
  { id: "SHAJD", officialName: "Courtyard by Marriott Shanghai Jiading" },
  { id: "SHAHR", officialName: "Renaissance Shanghai Hongqiao" },
  { id: "SHASF", officialName: "Sheraton Shanghai Fengxian" },
  { id: "SHAFD", officialName: "Fairfield by Marriott Shanghai Pudong" },
  { id: "SHAFK", officialName: "Four Points by Sheraton Shanghai, Kangqiao" },
  { id: "SHATR", officialName: "Courtyard by Marriott Shanghai International Tourism and Resorts Zone" },
  { id: "SHAHA", officialName: "Aloft Shanghai Hongqiao" },
  { id: "SHACA", officialName: "Renaissance Shanghai Caohejing Hotel" },
  { id: "SHAPH", officialName: "Renaissance Shanghai Putuo Hotel" },
  { id: "SHAPI", officialName: "Fairfield by Marriott Shanghai Pudong South" },
  { id: "SHASX", officialName: "Courtyard by Marriott Shanghai Xujiahui" },
  { id: "SHAOS", officialName: "Moxy Shanghai Xuhui" },
  { id: "SHAFQ", officialName: "Four Points by Sheraton Shanghai Hongqiao" },
  { id: "SHAPF", officialName: "Four Points by Sheraton Shanghai, Pudong" },
  { id: "SHAQP", officialName: "Four Points by Sheraton Shanghai Qingpu New City" },
  { id: "SHARN", officialName: "Renaissance Shanghai Pudong Hotel" },
  { id: "SHAHL", officialName: "The Hongta Hotel, a Luxury Collection Hotel, Shanghai" },
  { id: "SHAHO", officialName: "Courtyard by Marriott Shanghai Hongqiao" },
  { id: "SHAFL", officialName: "Fairfield by Marriott Shanghai Lingang Special Area" },
  { id: "SHAFI", officialName: "Fairfield by Marriott Shanghai Jingan" },
  { id: "SHAXB", officialName: "The St. Regis on the Bund, Shanghai" },
  { id: "SHAXX", officialName: "Moxy Shanghai Putuo" },
  { id: "SHAJW", officialName: "JW Marriott Hotel Shanghai at Tomorrow Square" },
  { id: "SHAYM", officialName: "Shanghai Marriott Hotel Yangpu Riverside" },
  { id: "SHABS", officialName: "Delta Hotels Shanghai Baoshan" },
  { id: "SHAJF", officialName: "JW Marriott Hotel Shanghai Fengxian" },
  { id: "SHAQF", officialName: "Fairfield by Marriott Shanghai Qingpu" },
  { id: "SHASP", officialName: "Sheraton Grand Shanghai Pudong Hotel & Residences" },
  { id: "SHAHC", officialName: "Courtyard by Marriott Shanghai Hongkou" },
  { id: "SHAZH", officialName: "Shanghai Marriott Hotel Kangqiao" },
  { id: "SHASZ", officialName: "The Ritz-Carlton Shanghai, Pudong" },
  { id: "SHAMS", officialName: "Le Méridien Shanghai Sheshan" },
  { id: "SHAHH", officialName: "Habo Hotel Shanghai, a Member of Design Hotels™" },
  { id: "SHAPS", officialName: "Shanghai Marriott Hotel Pudong South" },
  { id: "SHASY", officialName: "Renaissance Shanghai Yu Garden Hotel" },
  { id: "SHABG", officialName: "Bvlgari Hotel Shanghai" },
  { id: "SHAXF", officialName: "Fairfield by Marriott Shanghai Xuhui Center" },
  { id: "SHAIP", officialName: "Four Points by Sheraton Shanghai International Tourism and Resorts Zone" },
  { id: "SHAMG", officialName: "Courtyard by Marriott Shanghai Minhang" },
  { id: "SHASM", officialName: "Shanghai Marriott Hotel Songjiang" },
  { id: "JDZWP", officialName: "Four Points by Sheraton Wuyuan" },
  { id: "SQDFI", officialName: "Fairfield by Marriott Shangrao Xinzhou" },
  { id: "SWAMS", officialName: "Shantou Marriott Hotel" },
  { id: "SWASI", officialName: "Sheraton Shantou Hotel" },
  { id: "HUZLP", officialName: "Four Points by Sheraton Shanwei Lufeng" },
  { id: "HUZCS", officialName: "Courtyard by Marriott Shanwei Haifeng" },
  { id: "SZXFZ", officialName: "Fairfield by Marriott Shenzhen Shenshan Special Cooperation Zone" },
  { id: "HGHXN", officialName: "Courtyard by Marriott Xinchang" },
  { id: "HGHSM", officialName: "Le Meridien Shaoxing Yuecheng" },
  { id: "HGHSS", officialName: "Sheraton Shaoxing Shangyu" },
  { id: "HGHMC", officialName: "Shaoxing Marriott Hotel Shangyu" },
  { id: "SHESI", officialName: "Sheraton Shenyang South City Hotel" },
  { id: "SHEWI", officialName: "The Westin Shenyang" },
  { id: "SHESW", officialName: "Renaissance Shenyang West Hotel" },
  { id: "SHEFR", officialName: "Fairfield by Marriott Shenyang Railway Station" },
  { id: "SHEMD", officialName: "Le Méridien Shenyang, Heping" },
  { id: "SHEMR", officialName: "Shenyang Marriott Hotel" },
  { id: "SZXDF", officialName: "Fairfield by Marriott Shenzhen Dameisha" },
  { id: "SZXCY", officialName: "Courtyard by Marriott Shenzhen Bao'an" },
  { id: "SZXBR", officialName: "Renaissance Shenzhen Luohu" },
  { id: "SZXBA", officialName: "JW Marriott Hotel Shenzhen Bao'an" },
  { id: "SZXFL", officialName: "Fairfield by Marriott Shenzhen Longgang" },
  { id: "SZXWT", officialName: "Shenzhen Marriott Hotel Nanshan" },
  { id: "SZXNH", officialName: "NOA Hotel Shenzhen, a Member of Design Hotels" },
  { id: "SZXFP", officialName: "Four Points by Sheraton Shenzhen" },
  { id: "SZXGU", officialName: "Four Points by Sheraton Shenzhen Guangming" },
  { id: "SZXLP", officialName: "Four Points by Sheraton Shenzhen Longhua" },
  { id: "SZXPB", officialName: "Four Points by Sheraton Shenzhen Bay" },
  { id: "SZXQF", officialName: "Fairfield by Marriott Shenzhen Qianhai" },
  { id: "SZXJW", officialName: "JW Marriott Hotel Shenzhen" },
  { id: "SZXNB", officialName: "The Mercury Garden Shenzhen Nanshan, A Tribute Portfolio Hotel" },
  { id: "SZXBF", officialName: "Fairfield by Marriott Shenzhen Bao'an" },
  { id: "SZXXS", officialName: "The St. Regis Shenzhen Bao'an" },
  { id: "SZXAP", officialName: "Four Points by Sheraton Shenzhen Airport" },
  { id: "SZXTY", officialName: "The G Shenzhen, A Tribute Portfolio Hotel" },
  { id: "SZXGB", officialName: "Shenzhen Marriott Hotel Golden Bay" },
  { id: "SZXSN", officialName: "Sheraton Shenzhen Nanshan" },
  { id: "SZXWI", officialName: "The Westin Shenzhen Nanshan" },
  { id: "SZXER", officialName: "The OCT Harbour, Shenzhen - Marriott Executive Apartments" },
  { id: "SZXNP", officialName: "Four Points by Sheraton Shenzhen Nanshan" },
  { id: "SZXNW", officialName: "Courtyard by Marriott Shenzhen Northwest" },
  { id: "SZXSB", officialName: "Courtyard by Marriott Shenzhen Bay" },
  { id: "SZXRZ", officialName: "The Ritz-Carlton, Shenzhen" },
  { id: "SZXSF", officialName: "Sheraton Shenzhen Futian Hotel" },
  { id: "SZXXR", officialName: "The St. Regis Shenzhen" },
  { id: "SZXOX", officialName: "Moxy Shenzhen Bao'an" },
  { id: "SZXFB", officialName: "Four Points by Sheraton Shenzhen Bao'an" },
  { id: "SZXMD", officialName: "Le Méridien Shenzhen, Bao'an" },
  { id: "SZXRB", officialName: "Renaissance Shenzhen Bay Hotel" },
  { id: "SZXNS", officialName: "Moxy Shenzhen North Station" },
  { id: "PNXCY", officialName: "Courtyard by Marriott Sherman" },
  { id: "SJWDU", officialName: "Four Points by Sheraton Shijiazhuang Downtown" },
  { id: "SJWAL", officialName: "Aloft Shijiazhuang" },
  { id: "SJWFX", officialName: "Fairfield by Marriott Shijiazhuang High-Tech Zone" },
  { id: "SJWFF", officialName: "Fairfield by Marriott Shijiazhuang Station" },
  { id: "SCETS", officialName: "TownePlace Suites by Marriott State College" },
  { id: "WUXSS", officialName: "Sheraton Suzhou Yangcheng Lake" },
  { id: "NAOMC", officialName: "Suining Marriott Hotel" },
  { id: "SZVWH", officialName: "W Suzhou" },
  { id: "SZVMD", officialName: "Le Méridien Suzhou, Suzhou Bay" },
  { id: "WUXSK", officialName: "AC Hotel Suzhou Industrial Park" },
  { id: "WUXSF", officialName: "Fairfield Inn By Marriott Suzhou Xiangcheng" },
  { id: "WUXSJ", officialName: "Fairfield by Marriott Suzhou Jinji Lake" },
  { id: "WUXST", officialName: "Artik Suzhou, Apartments by Marriott Bonvoy" },
  { id: "SZVSF", officialName: "Four Points by Sheraton Suzhou" },
  { id: "SZVSW", officialName: "Renaissance Suzhou Wujiang Hotel" },
  { id: "SZVFI", officialName: "Fairfield by Marriott Suzhou High-Tech Zone" },
  { id: "SZVEL", officialName: "Element Suzhou Science and Technology Town" },
  { id: "SZVBR", officialName: "Renaissance Suzhou Hotel" },
  { id: "SZVFP", officialName: "Four Points by Sheraton Taicang" },
  { id: "SZVCY", officialName: "Courtyard by Marriott Suzhou" },
  { id: "WUXBR", officialName: "Renaissance Suzhou Taihu Lake Hotel" },
  { id: "WUXOX", officialName: "Moxy Suzhou City Centre" },
  { id: "SZVFS", officialName: "Four Points by Sheraton Suzhou, Wuzhong" },
  { id: "SHATM", officialName: "Taicang Marriott Hotel" },
  { id: "SHATY", officialName: "Courtyard by Marriott Taicang" },
  { id: "WUXTM", officialName: "Suzhou Marriott Hotel Yangcheng Lake" },
  { id: "WUXPS", officialName: "Four Points by Sheraton Suzhou South" },
  { id: "WUXSA", officialName: "AC Hotel Suzhou China" },
  { id: "WUXSM", officialName: "Courtyard by Marriott Suzhou Mudu" },
  { id: "WUXSR", officialName: "Marriott Executive Apartments Suzhou" },
  { id: "WUXTL", officialName: "Suzhou Marriott Hotel Taihu Lake" },
  { id: "WUXSP", officialName: "Four Points by Sheraton Suzhou Gusu" },
  { id: "WUXSZ", officialName: "The Ritz-Carlton, Suzhou" },
  { id: "SZVMC", officialName: "Suzhou Marriott Hotel" },
  { id: "TYNJW", officialName: "JW Marriott Hotel Taiyuan" },
  { id: "TYNDP", officialName: "Four Points by Sheraton Taiyuan Downtown" },
  { id: "TYNFI", officialName: "Fairfield by Marriott Taiyuan South" },
  { id: "TYNSI", officialName: "Sheraton Taiyuan" },
  { id: "TYNCY", officialName: "Courtyard by Marriott Taiyuan" },
  { id: "HYNFI", officialName: "Fairfield by Marriott Taizhou Bay" },
  { id: "HYNSI", officialName: "Sheraton Taizhou" },
  { id: "YTYCY", officialName: "Courtyard by Marriott Jiangsu Taizhou" },
  { id: "TSNTJ", officialName: "Renaissance Tianjin TEDA Convention Centre Hotel" },
  { id: "TSNER", officialName: "The Lakeview, Tianjin -- Marriott Executive Apartments" },
  { id: "TSNTW", officialName: "The Westin Tianjin" },
  { id: "TSNXR", officialName: "The St. Regis Tianjin" },
  { id: "TSNFN", officialName: "Four Points by Sheraton Tianjin National Convention and Exhibition Center" },
  { id: "TSNLV", officialName: "Renaissance Tianjin Lakeview Hotel" },
  { id: "TSNRZ", officialName: "The Ritz-Carlton, Tianjin" },
  { id: "TSNHO", officialName: "Courtyard by Marriott Tianjin Hongqiao" },
  { id: "TSNEX", officialName: "Tianjin Marriott Hotel National Convention and Exhibition Center" },
  { id: "TSNJP", officialName: "Four Points by Sheraton Tianjin Jiefang Bridge" },
  { id: "TSNTI", officialName: "TEDA, Tianjin-Marriott Executive Apartments" },
  { id: "THQFP", officialName: "Four Points by Sheraton Tianshui" },
  { id: "URCEP", officialName: "Four Points by Sheraton Urumqi Economic Development Zone" },
  { id: "URCFB", officialName: "Fairfield by Marriott Urumqi Beijing Road" },
  { id: "URCFP", officialName: "Four Points by Sheraton Urumqi" },
  { id: "SYXPF", officialName: "Four Points by Sheraton Shenzhou Peninsula" },
  { id: "SYXWS", officialName: "The Westin Shimei Bay Resort" },
  { id: "SYXMD", officialName: "Le Méridien Shimei Bay Beach Resort & Spa" },
  { id: "SYXPS", officialName: "Sheraton Shenzhou Peninsula Resort" },
  { id: "WNZWI", officialName: "The Westin Wenzhou" },
  { id: "WNZMC", officialName: "Wenzhou Marriott Hotel" },
  { id: "WNZAP", officialName: "Wenzhou Airport Marriott Hotel" },
  { id: "WNZGN", officialName: "Grand New Century Hotel, Wenzhou, A Tribute Portfolio Hotel" },
  { id: "ZHAFP", officialName: "Four Points by Sheraton Wuchuan, Loong Bay" },
  { id: "WUHWI", officialName: "The Westin Wuhan Wuchang" },
  { id: "WUHHK", officialName: "Wuhan Marriott Hotel Hankou" },
  { id: "WUHHP", officialName: "Four Points by Sheraton Wuhan Hankou" },
  { id: "WUHMW", officialName: "Wuhan Marriott Hotel Wuchang" },
  { id: "WUHPG", officialName: "Four Points by Sheraton Wuhan Optics Valley" },
  { id: "WUHBR", officialName: "Renaissance Wuhan Hotel" },
  { id: "WUHOV", officialName: "Wuhan Marriott Hotel Optics Valley" },
  { id: "WUHWS", officialName: "Sheraton Grand Wuhan Hankou Hotel" },
  { id: "WUHRZ", officialName: "The Ritz-Carlton, Wuhan" },
  { id: "WUHPO", officialName: "Four Points by Sheraton Wuhan Optics Valley Convention and Exhibition Center" },
  { id: "WUHCH", officialName: "AC Hotels By Marriott Wuhan Hankou" },
  { id: "WUHDU", officialName: "Four Points by Sheraton Wuhan, Dongxihu" },
  { id: "WUHFI", officialName: "Fairfield by Marriott Wuhan Wuchang" },
  { id: "WUHFP", officialName: "Four Points by Sheraton Wuhan, Jiangxia" },
  { id: "WUHHC", officialName: "Courtyard by Marriott Wuhan Hankou" },
  { id: "WUHHF", officialName: "Fairfield by Marriott Wuhan Hankou" },
  { id: "WUHWW", officialName: "The Westin Wuhan Hanyang" },
  { id: "WUHFJ", officialName: "Fairfield by Marriott Wuhan Jiangxia" },
  { id: "WUXJG", officialName: "Grand House, Jiangyin, a Tribute Portfolio Hotel" },
  { id: "WUXTP", officialName: "Four Points by Sheraton Wuxi High-tech Zone" },
  { id: "WUXMC", officialName: "Wuxi Marriott Hotel" },
  { id: "WUXML", officialName: "Wuxi Marriott Hotel Lihu Lake" },
  { id: "WUXLL", officialName: "Courtyard by Marriott Wuxi Lihu Lake" },
  { id: "WUXLP", officialName: "Four Points by Sheraton Wuxi Liangxi" },
  { id: "XIYFY", officialName: "Fairfield by Marriott Xi'an Dayan Pagoda" },
  { id: "XIYMH", officialName: "Xi'an Marriott Hotel High-Tech Zone" },
  { id: "XIYPH", officialName: "Four Points by Sheraton Xi'an High-Tech Zone" },
  { id: "XIYDO", officialName: "Moxy Xi'an Downtown" },
  { id: "XIYDP", officialName: "Four Points by Sheraton Xi'an Dayan Pagoda" },
  { id: "XIYCW", officialName: "Courtyard by Marriott Xi'an West" },
  { id: "XIYER", officialName: "The Fairway Place, Xi'an - Marriott Executive Apartments" },
  { id: "XIYFC", officialName: "Fairfield by Marriott Xi'an Chanba" },
  { id: "XIYJS", officialName: "JW Marriott Hotel Xi'an Southwest" },
  { id: "XIYNC", officialName: "Sheraton Xi'an North City Hotel" },
  { id: "XIYSS", officialName: "Sheraton Xi'an South" },
  { id: "XIYWF", officialName: "Fairfield By Marriott Xi'an Weiyang" },
  { id: "XIYWI", officialName: "The Westin Xi'an" },
  { id: "XIYJW", officialName: "JW Marriott Hotel Xi'an" },
  { id: "XIYOX", officialName: "Moxy Xi'an Beilin" },
  { id: "XIYMD", officialName: "Le Méridien Xi'an, Chanba" },
  { id: "XIYBP", officialName: "Four Points by Sheraton Xi'an Bell Tower" },
  { id: "XIYFI", officialName: "Fairfield by Marriott Xi'an North Station" },
  { id: "XIYSI", officialName: "Sheraton Xi'an Hotel" },
  { id: "XIYCY", officialName: "Courtyard by Marriott Xi'an North" },
  { id: "XIYSC", officialName: "Sheraton Xi'an Chanba" },
  { id: "XIYWH", officialName: "W Xi'an" },
  { id: "XIYRZ", officialName: "The Ritz-Carlton, Xi'an" },
  { id: "XIYDE", officialName: "Delta Hotels Xi'an" },
  { id: "XIYBR", officialName: "Renaissance Xi'an Hotel" },
  { id: "XMNBR", officialName: "Renaissance Xiamen Hotel" },
  { id: "XMNCY", officialName: "Courtyard by Marriott Xiamen" },
  { id: "XMNCH", officialName: "Courtyard by Marriott Xiamen Haicang" },
  { id: "XMNAX", officialName: "Aloft Xiamen Xiangan" },
  { id: "XMNCX", officialName: "Courtyard by Marriott Xiamen Xiang’an" },
  { id: "XMNET", officialName: "Element Xiamen Tong'an" },
  { id: "XMNXI", officialName: "Xiamen Marriott Hotel & Conference Centre" },
  { id: "XMNMJ", officialName: "Xiamen Marriott Hotel Jimei" },
  { id: "XMNSI", officialName: "Sheraton Xiamen Hotel" },
  { id: "XMNWH", officialName: "W Xiamen" },
  { id: "XMNMC", officialName: "Xiamen Marriott Hotel Haicang" },
  { id: "XMNMD", officialName: "Le Méridien Xiamen" },
  { id: "XMNSJ", officialName: "Sheraton Grand Xiamen Jimei" },
  { id: "XNNFI", officialName: "Fairfield by Marriott Xining North" },
  { id: "WUTXF", officialName: "Fairfield Inn by Marriott Xinzhou Xinfu" },
  { id: "TYNWM", officialName: "Wutai Mountain Marriott Hotel" },
  { id: "XUZSI", officialName: "Sheraton Xuzhou" },
  { id: "XUZLV", officialName: "Xuzhou Marriott Hotel Lakeview" },
  { id: "NBSFP", officialName: "Four Points by Sheraton Changbaishan" },
  { id: "YNZFP", officialName: "Four Points by Sheraton Yancheng, Jianhu" },
  { id: "YNZMC", officialName: "Yancheng Marriott Hotel" },
  { id: "YNZDF", officialName: "Fairfield by Marriott Yancheng Dafeng" },
  { id: "ZUHYP", officialName: "Four Points by Sheraton Yangjiang City Center" },
  { id: "ZUHEH", officialName: "Element Yangjiang Hailing Island" },
  { id: "YTYSF", officialName: "Fairfield by Marriott Yangzhou Slender West Lake" },
  { id: "YTYYC", officialName: "Courtyard by Marriott Yangzhou" },
  { id: "YNTSI", officialName: "Sheraton Yantai Golden Beach Resort" },
  { id: "YNTMC", officialName: "Yantai Marriott Hotel" },
  { id: "YNTFH", officialName: "Fairfield By Marriott Yantai" },
  { id: "YNTZP", officialName: "Four Points by Sheraton Yantai Zhifu" },
  { id: "YNTAY", officialName: "Aloft Yantai" },
  { id: "YNTWI", officialName: "The Westin Yantai" },
  { id: "YNTFP", officialName: "Four Points by Sheraton Yantai" },
  { id: "YBPCY", officialName: "Courtyard by Marriott Yibin" },
  { id: "YIHSM", officialName: "Le Méridien Yichang Sanxia" },
  { id: "YIHWI", officialName: "The Westin Yichang" },
  { id: "INCCY", officialName: "Courtyard by Marriott Yinchuan" },
  { id: "INCJW", officialName: "JW Marriott Hotel Yinchuan" },
  { id: "INCSI", officialName: "Sheraton Yinchuan" },
  { id: "INCXP", officialName: "Four Points by Sheraton Yinchuan Xingqing" },
  { id: "INCXF", officialName: "Fairfield by Marriott Yinchuan Xingqing" },
  { id: "YINFP", officialName: "Four Points by Sheraton Yining" },
  { id: "YINFI", officialName: "Fairfield by Marriott Yining" },
  { id: "YIWYF", officialName: "Fairfield by Marriott Yiwu" },
  { id: "YIWMC", officialName: "Yiwu Marriott Hotel" },
  { id: "YIWER", officialName: "The International Trade City, Yiwu - Marriott Executive Apartments" },
  { id: "CZXMD", officialName: "Le Méridien Yixing" },
  { id: "CSXYB", officialName: "Four Points by Sheraton Yiyang" },
  { id: "WNZCW", officialName: "Courtyard by Marriott Wenzhou Yueqing" },
  { id: "UYNFP", officialName: "Four Points by Sheraton Yulin High-Tech Zone" },
  { id: "UYNFI", officialName: "Fairfield by Marriott Yulin" },
  { id: "FUOSY", officialName: "Sheraton Yunfu Xinxing Hotel" },
  { id: "NGBYF", officialName: "Fairfield by Marriott Yuyao" },
  { id: "XUZTS", officialName: "Sheraton Tengzhou" },
  { id: "WUXZH", officialName: "Zhangjiagang Marriott Hotel" },
  { id: "DYGTF", officialName: "Fairfield by Marriott Zhangjiajie Tianmen Mountain" },
  { id: "DYGTP", officialName: "Four Points by Sheraton Zhangjiajie Tianmen Mountain" },
  { id: "DYGNF", officialName: "Four Points by Sheraton Zhangjiajie National Forest Park" },
  { id: "ZQZEL", officialName: "Element Chongli" },
  { id: "ZQZCY", officialName: "Courtyard by Marriott Chongli" },
  { id: "ZHAXP", officialName: "Four Points by Sheraton Zhanjiang Xiashan" },
  { id: "ZHASI", officialName: "Sheraton Zhanjiang Hotel" },
  { id: "FUOSZ", officialName: "Sheraton Zhaoqing Dinghu" },
  { id: "CGOBF", officialName: "Fairfield by Marriott Zhengzhou Beilonghu" },
  { id: "CGOGS", officialName: "Sheraton Grand Zhengzhou Hotel" },
  { id: "CGOSL", officialName: "Aloft Zhengzhou Shangjie" },
  { id: "CGOEP", officialName: "Four Points by Sheraton Zhengzhou East Railway Station" },
  { id: "CGOSF", officialName: "Fairfield by Marriott Zhengzhou Shuanghe Lake" },
  { id: "CGOJW", officialName: "JW Marriott Hotel Zhengzhou" },
  { id: "CGOAP", officialName: "Courtyard by Marriott Zhengzhou Airport" },
  { id: "CGOCY", officialName: "Courtyard by Marriott Zhengzhou East" },
  { id: "CGOMD", officialName: "Le Méridien Zhengzhou" },
  { id: "CZXSI", officialName: "Sheraton Zhenjiang Hotel" },
  { id: "CZXZM", officialName: "Zhenjiang Marriott Hotel" },
  { id: "ZISWZ", officialName: "The Westin Zhongshan Guzhen" },
  { id: "ZISMD", officialName: "Le Méridien Zhongshan" },
  { id: "ZISSI", officialName: "Sheraton Zhongshan Hotel" },
  { id: "HSNWI", officialName: "The Westin Zhujiajian Resort, Zhoushan" },
  { id: "HSNNF", officialName: "Fairfield by Marriott Zhoushan New City" },
  { id: "HSNDP", officialName: "Four Points by Sheraton Zhoushan Dinghai" },
  { id: "HSNZF", officialName: "Fairfield by Marriott Zhoushan Daishan" },
  { id: "HSNSI", officialName: "Sheraton Zhoushan Hotel" },
  { id: "HSNPF", officialName: "Fairfield by Marriott Zhoushan Putuo" },
  { id: "ZUHXA", officialName: "Aloft Zhuhai Xiangzhou" },
  { id: "ZUHXR", officialName: "The St. Regis Zhuhai" },
  { id: "ZUHBR", officialName: "Renaissance Zhuhai Hotel" },
  { id: "ZUHZS", officialName: "Sheraton Zhuhai Hotel" },
  { id: "ZUHNP", officialName: "Four Points by Sheraton Zhuhai Nanwan" },
  { id: "ZUHFI", officialName: "Fairfield by Marriott Zhuhai" },
  { id: "ZUHCY", officialName: "Courtyard by Marriott Zhuhai" },
  { id: "ZUHMC", officialName: "Zhuhai Marriott Hotel" },
  { id: "ZUHMJ", officialName: "Zhuhai Marriott Hotel Jinwan" },
  { id: "ZUHMZ", officialName: "Zhuhai Dong'ao Island Marriott Resort and Spa" },
  { id: "YIWZF", officialName: "Fairfield by Marriott Zhuji" },
  { id: "CSXZH", officialName: "Zhuzhou Marriott Hotel" },
  { id: "TNAZZ", officialName: "Four Points by Sheraton Zibo Zichuan" },
  { id: "TNAZF", officialName: "Fairfield by Marriott Zibo" },
  { id: "TNASI", officialName: "Sheraton Zibo Hotel" },
  { id: "BJSHS", officialName: "Sheraton Beijing Haidian" },
  { id: "CTUBX", officialName: "Renaissance Chengdu Tianfu New Area Hotel" },
  { id: "SYXSH", officialName: "Sheraton Sanya Bay Resort" },
  { id: "TSNBP", officialName: "Four Points Tianjin Binhai New Area" },
  { id: "YTYSP", officialName: "Four Points by Sheraton Yangzhou, Slender West Lake Road" },
];

/**
 * Some Chinese hotel operators use one statement merchant name for multiple
 * Marriott properties. Keep these outside property aliases so one property
 * does not win merely because it appears first in the index.
 */
export const chinaSharedMerchantRules: SharedMarriottMerchantRule[] = [
  {
    pattern: "QINGDAOQINGMAOIYEYOXINGON",
    normalizedName: "Renaissance Qingdao Hotel / Element Qingdao",
    propertyIds: ["cn-taobr", "cn-taoel"],
    region: "overseas",
    match: "contains",
    brandGroup: "marriott",
    confidence: "high",
    status: "active",
    reason:
      "QINGDAOQINGMAOIYEYOXINGON은 Renaissance Qingdao Hotel과 Element Qingdao에 공통으로 사용되는 가맹점명입니다. 명세서만으로 개별 호텔을 구분할 수 없어 두 호텔을 함께 표시합니다.",
  },
];

export const chinaMarriottProperties: MarriottPropertySeed[] =
  chinaOfficialRows.map(({ id, officialName }) =>
    applyCuratedMarriottPropertyAliases({
      id: `cn-${id.toLowerCase()}`,
      country: "CN",
      region: "overseas",
      officialName,
      brand: inferBrand(officialName),
      brandGroup: high.brandGroup,
      confidence: high.confidence,
      status: high.status,
      aliases: [],
      reason: `${officialName}은 Marriott Bonvoy 계열 호텔로 확인된 중국 호텔입니다.`,
    })
  );
