import { high, inferBrand, propertyId } from "./helpers";
import type { MarriottProperty } from "./types";

const chinaOfficialNames = [
  "Fairfield by Marriott Altay Fuhai",
  "Four Points by Sheraton Altay City",
  "Fairfield By Marriott Altay City",
  "JW Marriott Hotel Zhejiang Anji",
  "Four Points by Sheraton Anshun, Huangguoshu",
  "Fairfield by Marriott Baiyin Downtown",
  "Fairfield by Marriott Xiong'an",
  "Fairfield by Marriott Baoding High-Tech Zone",
  "Baotou Marriott Hotel",
  "Beihai Marriott Resort",
  "Sheraton Beihai Resort",
  "The Westin Beijing Financial Street",
  "Element Beijing Huairou",
  "The Ritz-Carlton, Beijing",
  "Beijing Marriott Hotel Changping",
  "JW Marriott Hotel Beijing Dongzhimen",
  "Beijing Marriott Marquis Hotel",
  "Courtyard by Marriott Beijing Changping",
  "Aloft Beijing Huairou",
  "Four Points by Sheraton Beijing West Station",
  "Renaissance Beijing Haidian Hotel",
  "The St. Regis Beijing",
  "Courtyard By Marriott Beijing Yanqing",
  "The Ritz-Carlton Beijing, North",
  "Sheraton Grand Beijing Dongcheng Hotel",
  "Fairfield by Marriott Beijing Capital Airport",
  "Four Points by Sheraton Beijing, Haidian Hotel & Serviced Apartments",
  "Sheraton Beijing Huairou Hotel",
  "Sheraton Beijing Lize Hotel",
  "Four Points by Sheraton Beijing Sanlitun Workers Stadium",
  "Four Points by Sheraton Beijing, South Railway Station",
  "Four Points by Sheraton Beijing South Railway Station, The Temple of Heaven Park",
  "Beijing Marriott Hotel Huairou",
  "Renaissance Beijing Wangfujing Hotel",
  "Fairfield by Marriott Beijing Daxing Airport",
  "Aloft Beijing, Haidian",
  "Bvlgari Hotel Beijing",
  "Beijing Marriott Hotel Northeast",
  "Fairfield by Marriott Beijing Olympic Sports Center",
  "Four Points by Sheraton Beijing Xidan",
  "The Ritz-Carlton Beijing, Financial Street",
  "JW Marriott Hotel Beijing",
  "Fairfield by Marriott Beijing Haidian",
  "The Imperial Mansion, Beijing Marriott Executive Apartments",
  "Four Points by Sheraton Beijing Fangshan",
  "The Sandalwood, Beijing - Marriott Executive Apartments",
  "Renaissance Beijing Capital Hotel",
  "JW Marriott Hotel Beijing Central",
  "Fairfield by Marriott Bengbu Longzihu",
  "Fairfield by Marriott Bijie",
  "AC Hotel Xinjiang Sayram Lake",
  "Sheraton Changbaishan Resort",
  "The Westin Changbaishan Resort",
  "Four Points by Sheraton Changchun West",
  "Courtyard by Marriott Changchun",
  "Fairfield by Marriott Changchun Jingyue High-Tech Zone",
  "Fairfield by Marriott Changchun Chaoyang",
  "Sheraton Changchun Jingyuetan Hotel",
  "Four Points by Sheraton Changchun, Hi-Tech Zone",
  "Sheraton Changde Wuling Hotel",
  "Meixi Lake Hotel, a Luxury Collection Hotel, Changsha",
  "The Meixi Lake, Changsha Marriott Executive Apartments",
  "Fairfield by Marriott Changsha Yuelu",
  "Courtyard by Marriott Changsha South",
  "Changsha Marriott Hotel West",
  "Sheraton Changsha Hotel",
  "Four Points by Sheraton Changsha, Meixi Lake",
  "JW Marriott Hotel Changsha",
  "Fairfield By Marriott Ningxiang",
  "The St. Regis Changsha",
  "Four Points by Sheraton Changsha, Tianxin",
  "The Westin Changsha",
  "Fairfield by Marriott Changsha Tianxin",
  "W Changsha",
  "Fairfield by Marriott Changshu Hi-Tech Zone",
  "Changzhou Marriott Hotel Jintan",
  "Le Méridien Changzhou",
  "The QuchanInner Liyang, Autograph Collection",
  "Sheraton Changzhou Xinbei Hotel",
  "Courtyard by Marriott Changzhou China",
  "Sheraton Changzhou Wujin Hotel",
  "Fairfield by Marriott Changzhou Jintan",
  "Fairfield by Marriott Changzhou Liyang",
  "Four Points by Sheraton Changzhou Economic Development Zone",
  "Renaissance Changzhou Wujin Hotel",
  "Changzhou Marriott Hotel",
  "Four Points by Sheraton Chengdu Kuanzhai Alley",
  "Four Points by Sheraton Chengdu East Station",
  "Four Points by Sheraton Chengdu, High-Tech Zone Exhibition Center",
  "Sheraton Chengdu Lido Hotel",
  "Fairfield by Marriott Chengdu Tianfu Square",
  "The Ritz-Carlton, Chengdu",
  "Sheraton Chengdu Pidu",
  "Four Points by Sheraton Chengdu, Pujiang Resort",
  "Chengdu Marriott Hotel Financial Centre",
  "Four Points by Sheraton Chengdu, Anren",
  "Courtyard by Marriott Chengdu South",
  "Renaissance Chengdu Hotel",
  "AC Hotel Chengdu North",
  "Fairfield by Marriott Chengdu Hi-Tech Zone",
  "The St. Regis Chengdu",
  "W Chengdu",
  "Four Points by Sheraton Chengdu, Chunxi Road",
  "JW Marriott Hotel Chengdu",
  "Four Points by Sheraton Chengdu Tianfu New Area",
  "Four Points by Sheraton Chongqing",
  "Four Points by Sheraton Chongqing Jiulongpo",
  "MajesTang Hotel, Chongqing, a Tribute Portfolio Hotel",
  "Le Méridien Chongqing, Nan'an",
  "Four Points by Sheraton Chongqing Jiangjin",
  "Four Points by Sheraton Chongqing, Yongchuan",
  "Marriott Executive Apartments Chongqing",
  "Fairfield by Marriott Chongqing Yongchuan",
  "Fairfield by Marriott Chongqing Nan’an District",
  "Four Points by Sheraton Chongqing Nanchuan",
  "Four Points by Sheraton Chongqing North Railway Station",
  "Moxy Chongqing",
  "Fairfield by Marriott Chongqing Yubei",
  "Courtyard by Marriott Chongqing Jiangjin",
  "JW Marriott Hotel Chongqing",
  "The Westin Chongqing Liberation Square",
  "Chongqing Marriott Hotel",
  "Four Points by Sheraton Chongqing Liangjiang New Area Jinkai Avenue",
  "Four Points by Sheraton Chongqing Yuzhong Peninsula",
  "Sheraton Chongqing Hotel",
  "Sheraton Chuzhou Hotel",
  "Fairfield by Marriott Chuzhou Railway Station",
  "Fairfield by Marriott Inn & Suites Columbus New Albany",
  "Four Points by Sheraton Dali, Erhai",
  "The Dali EDITION",
  "The Castle Hotel, a Luxury Collection Hotel, Dalian",
  "Fairfield by Marriott Dalian Jinpu New Area",
  "Aloft Dalian",
  "Four Points by Sheraton Dalian Donggang",
  "Fairfield by Marriott Danyang",
  "Four Points by Sheraton Danzhou",
  "Sheraton Daqing Hotel",
  "Four Points by Sheraton Datong Pingcheng",
  "Fairfield by Marriott Datong",
  "Aloft Dongguan Songshan Lake",
  "Fairfield by Marriott Dongguan Changping",
  "Dongguan Marriott Hotel",
  "Sheraton Dongguan Hotel",
  "Four Points by Sheraton Dunhuang",
  "Le Méridien Emei Mountain Resort",
  "Courtyard by Marriott Shanghai Fengxian",
  "Courtyard by Marriott Foshan",
  "Aloft Nanhai, Foshan",
  "Courtyard by Marriott Foshan Gaoming",
  "Fairfield by Marriott Foshan Nanhai",
  "Shunde Marriott Hotel",
  "Foshan Marriott Hotel",
  "Midea Shunde, a Tribute Portfolio Hotel",
  "Courtyard by Marriott Shunde",
  "Courtyard by Marriott Shunde Longjiang",
  "Sheraton Shunde Hotel",
  "Fairfield by Marriott Shunde",
  "Sheraton Fuqing Hotel",
  "Four Points by Sheraton Fuzhou Changle",
  "Sheraton Fuzhou Hotel",
  "Fuzhou Marriott Hotel Riverside",
  "The Westin Fuzhou Minjiang",
  "Four Points by Sheraton Fuzhou, Jin’an",
  "Fairfield by Marriott Fuzhou Taijiang",
  "AC Hotel Ganzhou Quannan",
  "Guangzhou Marriott Hotel Tianhe",
  "Guangzhou Marriott Hotel Nansha",
  "Four Points by Sheraton Guangzhou, Huangpu New City",
  "Four Points by Sheraton Guangzhou South Station",
  "Sheraton Guangzhou Panyu",
  "Aloft Guangzhou University Park",
  "Fairfield by Marriott Guangzhou Huadu",
  "Fairfield by Marriott Guangzhou Konggang",
  "The Ritz-Carlton, Guangzhou",
  "Four Points by Sheraton Guangzhou, Baiyun",
  "Element Guangzhou Baiyun",
  "Four Points by Sheraton Guangzhou Financial City, Tianhe",
  "Guangzhou Marriott Hotel Baiyun",
  "Four Points by Sheraton Guangzhou Bai’e Tan",
  "Four Points by Sheraton Guangzhou Changlong Wanbo Business District",
  "Fairfield by Marriott Guangzhou Tianhe Park",
  "Sheraton Guangzhou Hotel",
  "The Westin Pazhou",
  "Courtyard by Marriott Guangzhou Pazhou",
  "Sheraton Guangzhou Nansha Hotel",
  "The Westin Guangzhou",
  "W Guangzhou",
  "Four Points by Sheraton Guangzhou Huangpu",
  "Aurua Yangshuo Sugar House, a Member of Design Hotels",
  "Courtyard by Marriott Guilin Downtown",
  "Four Points by Sheraton Guilin, Lingui",
  "Four Points by Sheraton Guilin Central",
  "Sheraton Guilin Hotel",
  "Fairfield by Marriott Yangshuo",
  "Sheraton Guiyang Hotel",
  "Renaissance Guiyang Hotel",
  "Four Points by Sheraton Guiyang Shilihetan",
  "Fairfield by Marriott Guiyang Guanshanhu",
  "Four Points by Sheraton Guiyang Guanshanhu",
  "Four Points by Sheraton Guiyang, Huaxi",
  "Fairfield by Marriott Haidong",
  "The Ritz-Carlton, Haikou",
  "Sheraton Haikou Hotel",
  "Haikou Marriott Hotel",
  "Fairfield by Marriott Haikou Meilan",
  "The Westin Haikou",
  "Renaissance Haikou Hotel",
  "Four Points by Sheraton Haikou International Airport",
  "Four Points by Sheraton Hangzhou Xihu District Xixi Wetland",
  "Fairfield by Marriott Hangzhou Yuhang",
  "Sheraton Grand Hangzhou Binjiang Hotel",
  "Courtyard by Marriott Hangzhou Qianjiang",
  "Sheraton Hangzhou Fuyang",
  "Hangzhou Marriott Hotel Lin'an",
  "Fairfield by Marriott Hangzhou Qiandao Lake",
  "Hangzhou Marriott Hotel Qianjiang",
  "Wonderland Resort, Hangzhou Jiande, A Tribute Portfolio Resort",
  "The Azure Qiantang, a Luxury Collection Hotel, Hangzhou",
  "Courtyard by Marriott Hangzhou Xihu",
  "JW Marriott Hotel Hangzhou",
  "Le Méridien Hangzhou, Binjiang",
  "Renaissance Hangzhou Northeast Hotel",
  "AC Hotel by Marriott Hangzhou",
  "AC Hotels by Marriott Hangzhou Binjiang",
  "Fairfield by Marriott Hangzhou Binjiang Puyan",
  "Courtyard by Marriott Hangzhou West",
  "Courtyard by Marriott Hangzhou Xiaoshan",
  "Renaissance Hangzhou Lin'an Hotel",
  "Fairfield by Marriott Hangzhou Xihu District",
  "Renaissance Hangzhou Qianjiang Century City Hotel",
  "Marriott Executive Apartments Hangzhou",
  "Fairfield by Marriott Hangzhou Wulin Square, China",
  "Courtyard by Marriott Hangzhou Wulin",
  "Four Points by Sheraton Hangzhou, Binjiang",
  "Marriott Executive Apartments Hangzhou Yuhang",
  "Grand New Century Hotel, Hangzhou Boao, A Tribute Portfolio Hotel",
  "Fairfield by Marriott Hangzhou Qiantang",
  "Fairfield by Marriott Hangzhou Future Sci-tech City",
  "Four Points by Sheraton Qiandao Lake",
  "Fairfield by Marriott Hangzhou Gongshu",
  "Sheraton Grand Hangzhou Wetland Park Resort",
  "Fairfield by Marriott Hangzhou Xiaoshan",
  "Fairfield by Marriott Hangzhou Zhuantang",
  "Four Points by Sheraton Hanzhong Riverside",
  "JW Marriott Hotel Harbin River North",
  "Four Points by Sheraton Harbin City Center",
  "Fairfield by Marriott Harbin Downtown",
  "Sheraton Harbin Xiangfang Hotel",
  "The Ritz-Carlton, Harbin",
  "Four Points by Sheraton Hefei, Feidong",
  "Four Points by Sheraton Hefei, Shushan",
  "Four Points by Sheraton Hefei, Baohe",
  "Sheraton Hefei Xinzhan Hotel",
  "Four Points by Sheraton Hefei High-Tech Zone",
  "The Westin Hefei",
  "Four Points by Sheraton Hengyang Zhengxiang",
  "Four Points by Sheraton Guangdong, Heshan",
  "Four Points by Sheraton Heyuan Resort",
  "Sheraton Hohhot Hotel",
  "Hong Kong SkyCity Marriott Hotel",
  "The St. Regis Hong Kong",
  "Sheraton Hong Kong Tung Chung Hotel",
  "Sheraton Hong Kong Hotel & Towers",
  "Courtyard by Marriott Hong Kong",
  "Renaissance Hong Kong Harbour View Hotel",
  "JW Marriott Hotel Hong Kong",
  "The Ritz-Carlton, Hong Kong",
  "The Park Lane Hong Kong, Autograph Collection",
  "W Hong Kong",
  "Four Points by Sheraton Hong Kong, Tung Chung",
  "Hong Kong Ocean Park Marriott Hotel",
  "Courtyard by Marriott Hong Kong Sha Tin",
  "Mira Moon Hong Kong, a Member of Design Hotels™",
  "The Mira Hong Kong, a Member of Design Hotels™",
  "Le Méridien Hong Kong, Cyberport",
  "Residence Inn by Marriott Houston Northwest/Cypress",
  "Fairfield by Marriott Huai'an Downtown",
  "Fairfield by Marriott Huangshi Development Zone",
  "Sheraton Huizhou Bailuhu",
  "Renaissance Huizhou Hotel",
  "Le Méridien Xiaojing Bay",
  "Sheraton Huzhou Taihu Lake Hot Spring Resort & Spa",
  "Courtyard by Marriott Anji",
  "Aloft Huzhou",
  "Grand New Century Resort, Changxing, A Tribute Portfolio Resort",
  "Deqing Marriott Hotel",
  "Fairfield by Marriott Deqing",
  "Fairfield by Marriott Huzhou Nanxun",
  "Huzhou Marriott Hotel Nanxun",
  "Four Points by Sheraton Huzhou",
  "Four Points by Sheraton Huzhou, Nanxun",
  "Four Points by Sheraton Zhaosu",
  "Four Points by Sheraton Ji’an",
  "Fairfield By Marriott Jian Anfu",
  "Four Points by Sheraton Jiangmen Downtown",
  "Fairfield by Marriott Taishan",
  "Courtyard by Marriott Jiangyin",
  "Sheraton Jiangyin Hotel",
  "Four Points by Sheraton Jiaxing",
  "Four Points by Sheraton Haiyan",
  "Jiaxing Marriott Hotel",
  "Jieyang Marriott Hotel",
  "Sheraton Jinan Hotel",
  "Four Points by Sheraton Jinan, High-Tech Zone",
  "Fairfield by Marriott Jingdezhen",
  "Four Points by Sheraton Xishuangbanna",
  "Sheraton Grand Xishuangbanna Hotel",
  "Four Points by Sheraton Xuancheng, Jingxian",
  "Four Points by Sheraton Jingzhou Downtown",
  "Fairfield by Marriott Jingzhou",
  "Sheraton Pujiang",
  "Fairfield by Marriott Pujiang",
  "Jinhua Marriott Hotel",
  "Fairfield by Marriott Hengdian",
  "Sheraton Jinzhong",
  "Sheraton Jinzhou Hotel",
  "Sheraton Jiujiang",
  "Delta Hotels Jiuzhaigou",
  "Rissai Valley, a Ritz-Carlton Reserve",
  "Courtyard by Marriott Jiuzhaigou",
  "Sheraton Kaifeng",
  "Four Points by Sheraton Kashgar",
  "Renaissance Hotel Korla",
  "Courtyard by Marriott Korla",
  "Four Points by Sheraton Kunming, International Convention & Exhibition Center",
  "Delta Hotels Kunming",
  "Fairfield by Marriott Kunming Xinying",
  "Four Points by Sheraton Kunming Chenggong",
  "Four Points by Sheraton Kunming Dongfeng Square",
  "Four Points by Sheraton Kunming Guandu",
  "Four Points by Sheraton Kunming, Downtown",
  "Fairfield by Marriott Kunming Xishan",
  "Four Points by Sheraton Kunming Changshui Airport",
  "Sheraton Kunming",
  "Aloft Kunshan Dianshan Lake",
  "Sheraton Kunshan Dianshan Lake",
  "Four Points by Sheraton Kunshan",
  "Courtyard by Marriott Kunshan",
  "Fairfield by Marriott Kunshan",
  "Courtyard by Marriott Langfang",
  "Sheraton Langfang Chaobai River Hotel",
  "Four Points by Sheraton Langfang, Guan",
  "Sheraton Lanzhou Anning",
  "Four Points by Sheraton Leshan",
  "The St. Regis Lhasa Resort",
  "The ArcadiaPlace, Lugu Lake, a Member of Design Hotels",
  "Four Points by Sheraton Lianyungang Downtown",
  "Four Points by Sheraton Lianyungang",
  "Fairfield by Marriott Liaocheng Dongchangfu",
  "Fairfield by Marriott Lijiang Ancient Town",
  "The Westin Blue Bay Resort & Spa",
  "Marriott Resort Xiangshui Bay",
  "Four Points by Sheraton Linhai",
  "​Four Points by Sheraton Linyi City Center",
  "Fairfield by Marriott Linyi Beicheng New District",
  "Four Points by Sheraton Linyi Hedong",
  "Element Lishui",
  "Four Points by Sheraton Qingtian",
  "Lishui Marriott Hotel",
  "Four Points by Sheraton Liupanshui",
  "Courtyard by Marriott Liuzhou Sanjiang",
  "Liyang Marriott Hotel",
  "Four Points by Sheraton Luoyang Central Business District",
  "Four Points by Sheraton Luohe",
  "Sheraton Luoyang",
  "Courtyard by Marriott Luoyang",
  "Luoyang Marriott Hotel",
  "W Macau - Studio City",
  "Londoner Grand, a Luxury Collection Hotel, Macao",
  "The Ritz-Carlton, Macau",
  "The St. Regis Macao",
  "JW Marriott Hotel Macau",
  "Sheraton Maoming Romantic Beach Resort",
  "Four Points by Sheraton Maoming",
  "Sheraton Maoming Hot Spring Resort",
  "Four Points by Sheraton Mianyang",
  "Sheraton Mianyang",
  "Element Mile",
  "Sheraton Mile Hotel",
  "Courtyard by Marriott Nanchang",
  "Sheraton Nanchang Hotel",
  "Four Points by Sheraton Nanchang, Xihu",
  "Courtyard by Marriott Nanjing Jiangning",
  "Nanjing, Jiangning, Autograph Collection",
  "The Sifang Hotel Nanjing, Autograph Collection",
  "Marriott Nanjing South Hotel",
  "The Westin Nanjing Resort & Spa",
  "Fairfield by Marriott Nanjing Yuhuatai",
  "Four Points by Sheraton Nanjing, Gulou District",
  "Renaissance Nanjing Olympic Centre Hotel",
  "Sheraton Nanjing Kingsley Hotel & Towers",
  "The Westin Nanjing Xuanwu Lake",
  "Moxy Nanjing Jiangning",
  "The Ritz-Carlton, Nanjing",
  "Renaissance Nanning Hotel",
  "Courtyard by Marriott Nanning Wuxiang",
  "Four Points by Sheraton Nanning, Wuxiang",
  "Nanning Marriott Hotel",
  "Na Lotus Hotel, a Luxury Collection Hotel, Nanning",
  "Nantong Marriott Hotel",
  "Courtyard by Marriott Nantong",
  "Le Meridien Nantong",
  "Four Points by Sheraton Nantong, Haimen",
  "The Westin Ningbo",
  "Ningbo Marriott Hotel",
  "Sheraton Ninghai",
  "Moxy Ningbo Old Bund",
  "Sheraton Ningbo Hotel",
  "Sheraton Ningbo Yinzhou",
  "Sheraton Ningbo Xiangshan Resort",
  "Fairfield by Marriott Ningbo Yinzhou",
  "Courtyard by Marriott Xiapu",
  "Fairfield by Marriott Ningde Xiapu",
  "Courtyard by Marriott Pinghu",
  "Sheraton Qiandao Lake Resort",
  "Sheraton Qingdao Licang Hotel",
  "Sheraton Qingdao Jiaozhou Hotel",
  "The Westin Qingdao",
  "Four Points by Sheraton Qingdao, West Coast",
  "The Westin Qingdao West Coast",
  "Renaissance Qingdao Hotel",
  "Four Points by Sheraton Qingdao, Chengyang East",
  "The St. Regis Qingdao",
  "Flow and Co. Qingdao, Autograph Collection",
  "Le Méridien Qingdao",
  "Four Points by Sheraton Qingdao, Chengyang",
  "Le Méridien Qingdao West Coast",
  "Fairfield by Marriott Qingdao West Coast",
  "Qingdao Marriott Hotel Jiaozhou",
  "Sheraton Qingdao West Coast",
  "Element Qingdao",
  "Four Points by Sheraton Qingdao, Jiaozhou",
  "Sheraton Qingyuan Lion Lake Resort",
  "Qinhuangdao Marriott Resort",
  "Courtyard by Marriott Qinhuangdao West",
  "Sheraton Qinhuangdao Beidaihe Hotel",
  "Fairfield by Marriott Qinhuangdao Haigang",
  "Four Points by Sheraton Hainan, Qiongzhong",
  "Fairfield by Marriott Quanzhou Fengze",
  "Four Points by Sheraton Quanzhou Huian",
  "JW Marriott Hotel Qufu",
  "Four Points by Sheraton Rizhao Central Activities Zone",
  "Courtyard by Marriott Rizhao",
  "Sheraton Rizhao Hotel",
  "Four Points by Sheraton Rizhao",
  "The Ritz-Carlton Sanya, Yalong Bay",
  "The St. Regis Sanya Yalong Bay Resort",
  "Sheraton Sanya Haitang Bay Resort",
  "The Sanya EDITION",
  "JW Marriott Sanya Haitang Bay Resort & Spa",
  "JW Marriott Hotel Sanya Dadonghai Bay",
  "Four Points by Sheraton Hainan, Sanya",
  "The Shanhaitian Resort Sanya, Autograph Collection",
  "Renaissance Sanya Haitang Bay Resort",
  "The Westin Sanya Haitang Bay Resort",
  "Sheraton Sanya Resort",
  "The Taikang Sanya, a Tribute Portfolio Resort",
  "Sanya Marriott Yalong Bay Resort & Spa",
  "Sheraton Shanghai Pudong Riverside",
  "Four Points by Sheraton Shanghai Fengjing",
  "Courtyard by Marriott Shanghai Central",
  "Four Points by Sheraton Shanghai Jiading",
  "JW Marriott Marquis Hotel Shanghai Pudong",
  "Le Méridien Shanghai, Minhang",
  "W Shanghai - The Bund",
  "Sheraton Shanghai Chongming Hotel",
  "Shanghai Marriott Marquis City Centre",
  "Aqua Caeli Hotel, Shanghai Fengjing, a Tribute Portfolio Hotel",
  "The Portman Ritz-Carlton, Shanghai",
  "Sheraton Shanghai Jiading Hotel",
  "Marriott Executive Apartments Shanghai, Zhangjiang",
  "The Westin Bund Center, Shanghai",
  "Shanghai Marriott Hotel Parkview",
  "Aloft Shanghai Zhangjiang Haike",
  "Sheraton Shanghai Waigaoqiao Hotel",
  "Fairfield by Marriott Shanghai Hongqiao NECC",
  "Fairfield by Marriott Shanghai Hongqiao",
  "Sheraton Shanghai North Bund",
  "Moxy Shanghai Hongqiao NECC",
  "The St. Regis Shanghai Jingan",
  "Courtyard by Marriott Shanghai Songjiang",
  "Courtyard by Marriott Shanghai Changfeng Park",
  "Four Points by Sheraton Shanghai, Daning",
  "The Shanghai EDITION",
  "Shanghai Marriott Hotel Pudong East",
  "Renaissance Shanghai Zhongshan Park Hotel",
  "Courtyard by Marriott Shanghai Jiading",
  "Renaissance Shanghai Hongqiao",
  "Sheraton Shanghai Fengxian",
  "Fairfield by Marriott Shanghai Pudong",
  "Four Points by Sheraton Shanghai, Kangqiao",
  "Courtyard by Marriott Shanghai International Tourism and Resorts Zone",
  "Aloft Shanghai Hongqiao",
  "Renaissance Shanghai Caohejing Hotel",
  "Renaissance Shanghai Putuo Hotel",
  "Fairfield by Marriott Shanghai Pudong South",
  "Courtyard by Marriott Shanghai Xujiahui",
  "Moxy Shanghai Xuhui",
  "Four Points by Sheraton Shanghai Hongqiao",
  "Four Points by Sheraton Shanghai, Pudong",
  "Four Points by Sheraton Shanghai Qingpu New City",
  "Renaissance Shanghai Pudong Hotel",
  "The Hongta Hotel, a Luxury Collection Hotel, Shanghai",
  "Courtyard by Marriott Shanghai Hongqiao",
  "Fairfield by Marriott Shanghai Lingang Special Area",
  "Fairfield by Marriott Shanghai Jingan",
  "The St. Regis on the Bund, Shanghai",
  "Moxy Shanghai Putuo",
  "JW Marriott Hotel Shanghai at Tomorrow Square",
  "Shanghai Marriott Hotel Yangpu Riverside",
  "Delta Hotels Shanghai Baoshan",
  "JW Marriott Hotel Shanghai Fengxian",
  "Fairfield by Marriott Shanghai Qingpu",
  "Sheraton Grand Shanghai Pudong Hotel & Residences",
  "Courtyard by Marriott Shanghai Hongkou",
  "Shanghai Marriott Hotel Kangqiao",
  "The Ritz-Carlton Shanghai, Pudong",
  "Le Méridien Shanghai Sheshan",
  "Habo Hotel Shanghai, a Member of Design Hotels™",
  "Shanghai Marriott Hotel Pudong South",
  "Renaissance Shanghai Yu Garden Hotel",
  "Bvlgari Hotel Shanghai",
  "Fairfield by Marriott Shanghai Xuhui Center",
  "Four Points by Sheraton Shanghai International Tourism and Resorts Zone",
  "Courtyard by Marriott Shanghai Minhang",
  "Shanghai Marriott Hotel Songjiang",
  "Four Points by Sheraton Wuyuan",
  "Fairfield by Marriott Shangrao Xinzhou",
  "Shantou Marriott Hotel",
  "Sheraton Shantou Hotel",
  "Four Points by Sheraton Shanwei Lufeng",
  "Courtyard by Marriott Shanwei Haifeng",
  "Fairfield by Marriott Shenzhen Shenshan Special Cooperation Zone",
  "Courtyard by Marriott Xinchang",
  "Le Meridien Shaoxing Yuecheng",
  "Sheraton Shaoxing Shangyu",
  "Shaoxing Marriott Hotel Shangyu",
  "Sheraton Shenyang South City Hotel",
  "The Westin Shenyang",
  "Renaissance Shenyang West Hotel",
  "Fairfield by Marriott Shenyang Railway Station",
  "Le Méridien Shenyang, Heping",
  "Shenyang Marriott Hotel",
  "Fairfield by Marriott Shenzhen Dameisha",
  "Courtyard by Marriott Shenzhen Bao'an",
  "Renaissance Shenzhen Luohu",
  "JW Marriott Hotel Shenzhen Bao'an",
  "Fairfield by Marriott Shenzhen Longgang",
  "Shenzhen Marriott Hotel Nanshan",
  "NOA Hotel Shenzhen, a Member of Design Hotels",
  "Four Points by Sheraton Shenzhen",
  "Four Points by Sheraton Shenzhen Guangming",
  "Four Points by Sheraton Shenzhen Longhua",
  "Four Points by Sheraton Shenzhen Bay",
  "Fairfield by Marriott Shenzhen Qianhai",
  "JW Marriott Hotel Shenzhen",
  "The Mercury Garden Shenzhen Nanshan, A Tribute Portfolio Hotel",
  "Fairfield by Marriott Shenzhen Bao'an",
  "The St. Regis Shenzhen Bao'an",
  "Four Points by Sheraton Shenzhen Airport",
  "The G Shenzhen, A Tribute Portfolio Hotel",
  "Shenzhen Marriott Hotel Golden Bay",
  "Sheraton Shenzhen Nanshan",
  "The Westin Shenzhen Nanshan",
  "The OCT Harbour, Shenzhen - Marriott Executive Apartments",
  "Four Points by Sheraton Shenzhen Nanshan",
  "Courtyard by Marriott Shenzhen Northwest",
  "Courtyard by Marriott Shenzhen Bay",
  "The Ritz-Carlton, Shenzhen",
  "Sheraton Shenzhen Futian Hotel",
  "The St. Regis Shenzhen",
  "Moxy Shenzhen Bao'an",
  "Four Points by Sheraton Shenzhen Bao'an",
  "Le Méridien Shenzhen, Bao'an",
  "Renaissance Shenzhen Bay Hotel",
  "Moxy Shenzhen North Station",
  "Courtyard by Marriott Sherman",
  "Four Points by Sheraton Shijiazhuang Downtown",
  "Aloft Shijiazhuang",
  "Fairfield by Marriott Shijiazhuang High-Tech Zone",
  "Fairfield by Marriott Shijiazhuang Station",
  "TownePlace Suites by Marriott State College",
  "Sheraton Suzhou Yangcheng Lake",
  "Suining Marriott Hotel",
  "W Suzhou",
  "Le Méridien Suzhou, Suzhou Bay",
  "AC Hotel Suzhou Industrial Park",
  "Fairfield Inn By Marriott Suzhou Xiangcheng",
  "Fairfield by Marriott Suzhou Jinji Lake",
  "Artik Suzhou, Apartments by Marriott Bonvoy",
  "Four Points by Sheraton Suzhou",
  "Renaissance Suzhou Wujiang Hotel",
  "Fairfield by Marriott Suzhou High-Tech Zone",
  "Element Suzhou Science and Technology Town",
  "Renaissance Suzhou Hotel",
  "Four Points by Sheraton Taicang",
  "Courtyard by Marriott Suzhou",
  "Renaissance Suzhou Taihu Lake Hotel",
  "Moxy Suzhou City Centre",
  "Four Points by Sheraton Suzhou, Wuzhong",
  "Taicang Marriott Hotel",
  "Courtyard by Marriott Taicang",
  "Suzhou Marriott Hotel Yangcheng Lake",
  "Four Points by Sheraton Suzhou South",
  "AC Hotel Suzhou China",
  "Courtyard by Marriott Suzhou Mudu",
  "Marriott Executive Apartments Suzhou",
  "Suzhou Marriott Hotel Taihu Lake",
  "Four Points by Sheraton Suzhou Gusu",
  "The Ritz-Carlton, Suzhou",
  "Suzhou Marriott Hotel",
  "JW Marriott Hotel Taiyuan",
  "Four Points by Sheraton Taiyuan Downtown",
  "Fairfield by Marriott Taiyuan South",
  "Sheraton Taiyuan",
  "Courtyard by Marriott Taiyuan",
  "Fairfield by Marriott Taizhou Bay",
  "Sheraton Taizhou",
  "Courtyard by Marriott Jiangsu Taizhou",
  "Renaissance Tianjin TEDA Convention Centre Hotel",
  "The Lakeview, Tianjin -- Marriott Executive Apartments",
  "The Westin Tianjin",
  "The St. Regis Tianjin",
  "Four Points by Sheraton Tianjin National Convention and Exhibition Center",
  "Renaissance Tianjin Lakeview Hotel",
  "The Ritz-Carlton, Tianjin",
  "Courtyard by Marriott Tianjin Hongqiao",
  "Tianjin Marriott Hotel National Convention and Exhibition Center",
  "Four Points by Sheraton Tianjin Jiefang Bridge",
  "TEDA, Tianjin-Marriott Executive Apartments",
  "Four Points by Sheraton Tianshui",
  "Four Points by Sheraton Urumqi Economic Development Zone",
  "Fairfield by Marriott Urumqi Beijing Road",
  "Four Points by Sheraton Urumqi",
  "Four Points by Sheraton Shenzhou Peninsula",
  "The Westin Shimei Bay Resort",
  "Le Méridien Shimei Bay Beach Resort & Spa",
  "Sheraton Shenzhou Peninsula Resort",
  "The Westin Wenzhou",
  "Wenzhou Marriott Hotel",
  "Wenzhou Airport Marriott Hotel",
  "Grand New Century Hotel, Wenzhou, A Tribute Portfolio Hotel",
  "Four Points by Sheraton Wuchuan, Loong Bay",
  "The Westin Wuhan Wuchang",
  "Wuhan Marriott Hotel Hankou",
  "Four Points by Sheraton Wuhan Hankou",
  "Wuhan Marriott Hotel Wuchang",
  "Four Points by Sheraton Wuhan Optics Valley",
  "Renaissance Wuhan Hotel",
  "Wuhan Marriott Hotel Optics Valley",
  "Sheraton Grand Wuhan Hankou Hotel",
  "The Ritz-Carlton, Wuhan",
  "Four Points by Sheraton Wuhan Optics Valley Convention and Exhibition Center",
  "AC Hotels By Marriott Wuhan Hankou",
  "Four Points by Sheraton Wuhan, Dongxihu",
  "Fairfield by Marriott Wuhan Wuchang",
  "Four Points by Sheraton Wuhan, Jiangxia",
  "Courtyard by Marriott Wuhan Hankou",
  "Fairfield by Marriott Wuhan Hankou",
  "The Westin Wuhan Hanyang",
  "Fairfield by Marriott Wuhan Jiangxia",
  "Grand House, Jiangyin, a Tribute Portfolio Hotel",
  "Four Points by Sheraton Wuxi High-tech Zone",
  "Wuxi Marriott Hotel",
  "Wuxi Marriott Hotel Lihu Lake",
  "Courtyard by Marriott Wuxi Lihu Lake",
  "Four Points by Sheraton Wuxi Liangxi",
  "Fairfield by Marriott Xi'an Dayan Pagoda",
  "Xi'an Marriott Hotel High-Tech Zone",
  "Four Points by Sheraton Xi'an High-Tech Zone",
  "Moxy Xi'an Downtown",
  "Four Points by Sheraton Xi'an Dayan Pagoda",
  "Courtyard by Marriott Xi'an West",
  "The Fairway Place, Xi'an - Marriott Executive Apartments",
  "Fairfield by Marriott Xi'an Chanba",
  "JW Marriott Hotel Xi'an Southwest",
  "Sheraton Xi'an North City Hotel",
  "Sheraton Xi'an South",
  "Fairfield By Marriott Xi'an Weiyang",
  "The Westin Xi'an",
  "JW Marriott Hotel Xi'an",
  "Moxy Xi'an Beilin",
  "Le Méridien Xi'an, Chanba",
  "Four Points by Sheraton Xi'an Bell Tower",
  "Fairfield by Marriott Xi'an North Station",
  "Sheraton Xi'an Hotel",
  "Courtyard by Marriott Xi'an North",
  "Sheraton Xi'an Chanba",
  "W Xi'an",
  "The Ritz-Carlton, Xi'an",
  "Delta Hotels Xi'an",
  "Renaissance Xi'an Hotel",
  "Renaissance Xiamen Hotel",
  "Courtyard by Marriott Xiamen",
  "Courtyard by Marriott Xiamen Haicang",
  "Aloft Xiamen Xiangan",
  "Courtyard by Marriott Xiamen Xiang’an",
  "Element Xiamen Tong'an",
  "Xiamen Marriott Hotel & Conference Centre",
  "Xiamen Marriott Hotel Jimei",
  "Sheraton Xiamen Hotel",
  "W Xiamen",
  "Xiamen Marriott Hotel Haicang",
  "Le Méridien Xiamen",
  "Sheraton Grand Xiamen Jimei",
  "Fairfield by Marriott Xining North",
  "Fairfield Inn by Marriott Xinzhou Xinfu",
  "Wutai Mountain Marriott Hotel",
  "Sheraton Xuzhou",
  "Xuzhou Marriott Hotel Lakeview",
  "Four Points by Sheraton Changbaishan",
  "Four Points by Sheraton Yancheng, Jianhu",
  "Yancheng Marriott Hotel",
  "Fairfield by Marriott Yancheng Dafeng",
  "Four Points by Sheraton Yangjiang City Center",
  "Element Yangjiang Hailing Island",
  "Fairfield by Marriott Yangzhou Slender West Lake",
  "Courtyard by Marriott Yangzhou",
  "Sheraton Yantai Golden Beach Resort",
  "Yantai Marriott Hotel",
  "Fairfield By Marriott Yantai",
  "Four Points by Sheraton Yantai Zhifu",
  "Aloft Yantai",
  "The Westin Yantai",
  "Four Points by Sheraton Yantai",
  "Courtyard by Marriott Yibin",
  "Le Méridien Yichang Sanxia",
  "The Westin Yichang",
  "Courtyard by Marriott Yinchuan",
  "JW Marriott Hotel Yinchuan",
  "Sheraton Yinchuan",
  "Four Points by Sheraton Yinchuan Xingqing",
  "Fairfield by Marriott Yinchuan Xingqing",
  "Four Points by Sheraton Yining",
  "Fairfield by Marriott Yining",
  "Fairfield by Marriott Yiwu",
  "Yiwu Marriott Hotel",
  "The International Trade City, Yiwu - Marriott Executive Apartments",
  "Le Méridien Yixing",
  "Four Points by Sheraton Yiyang",
  "Courtyard by Marriott Wenzhou Yueqing",
  "Four Points by Sheraton Yulin High-Tech Zone",
  "Fairfield by Marriott Yulin",
  "Sheraton Yunfu Xinxing Hotel",
  "Fairfield by Marriott Yuyao",
  "Sheraton Tengzhou",
  "Zhangjiagang Marriott Hotel",
  "Fairfield by Marriott Zhangjiajie Tianmen Mountain",
  "Four Points by Sheraton Zhangjiajie Tianmen Mountain",
  "Four Points by Sheraton Zhangjiajie National Forest Park",
  "Element Chongli",
  "Courtyard by Marriott Chongli",
  "Four Points by Sheraton Zhanjiang Xiashan",
  "Sheraton Zhanjiang Hotel",
  "Sheraton Zhaoqing Dinghu",
  "Fairfield by Marriott Zhengzhou Beilonghu",
  "Sheraton Grand Zhengzhou Hotel",
  "Aloft Zhengzhou Shangjie",
  "Four Points by Sheraton Zhengzhou East Railway Station",
  "Fairfield by Marriott Zhengzhou Shuanghe Lake",
  "JW Marriott Hotel Zhengzhou",
  "Courtyard by Marriott Zhengzhou Airport",
  "Courtyard by Marriott Zhengzhou East",
  "Le Méridien Zhengzhou",
  "Sheraton Zhenjiang Hotel",
  "Zhenjiang Marriott Hotel",
  "The Westin Zhongshan Guzhen",
  "Le Méridien Zhongshan",
  "Sheraton Zhongshan Hotel",
  "The Westin Zhujiajian Resort, Zhoushan",
  "Fairfield by Marriott Zhoushan New City",
  "Four Points by Sheraton Zhoushan Dinghai",
  "Fairfield by Marriott Zhoushan Daishan",
  "Sheraton Zhoushan Hotel",
  "Fairfield by Marriott Zhoushan Putuo",
  "Aloft Zhuhai Xiangzhou",
  "The St. Regis Zhuhai",
  "Renaissance Zhuhai Hotel",
  "Sheraton Zhuhai Hotel",
  "Four Points by Sheraton Zhuhai Nanwan",
  "Fairfield by Marriott Zhuhai",
  "Courtyard by Marriott Zhuhai",
  "Zhuhai Marriott Hotel",
  "Zhuhai Marriott Hotel Jinwan",
  "Zhuhai Dong'ao Island Marriott Resort and Spa",
  "Fairfield by Marriott Zhuji",
  "Zhuzhou Marriott Hotel",
  "Four Points by Sheraton Zibo Zichuan",
  "Fairfield by Marriott Zibo",
  "Sheraton Zibo Hotel",
];

export const chinaMarriottProperties: MarriottProperty[] =
  chinaOfficialNames.map((officialName) => ({
    id: propertyId("CN", officialName),
    country: "CN",
    region: "overseas",
    officialName,
    brand: inferBrand(officialName),
    brandGroup: high.brandGroup,
    confidence: high.confidence,
    status: high.status,
    aliases: [],
    reason: `${officialName}은 Marriott Bonvoy 계열 호텔로 확인된 중국 호텔입니다.`,
  }));
