import { high, inferBrand } from "./helpers";
import type { MarriottProperty } from "./types";

// Source: Marriott hotel sitemap property codes, July 2026.
const germanyMarriottOfficialRows = [
  { id: "FRARP", officialName: "Roomers ParkView, a Luxury Collection Hotel, Frankfurt" },
  { id: "MUCLK", officialName: "Koenigshof, a Luxury Collection Hotel, Munich" },
  { id: "BERJW", officialName: "JW Marriott Hotel Berlin" },
  { id: "FRAJW", officialName: "JW Marriott Hotel Frankfurt" },
  { id: "BERAG", officialName: "Hotel Luc, Autograph Collection" },
  { id: "BERAK", officialName: "Roomers Berlin Steinplatz, Autograph Collection" },
  { id: "DRSAK", officialName: "Gewandhaus Dresden, Autograph Collection" },
  { id: "ERFAK", officialName: "Hotel Elephant Weimar, Autograph Collection" },
  { id: "FKBAK", officialName: "Roomers Baden-Baden, Autograph Collection" },
  { id: "FRAAR", officialName: "Villa Rothschild, Autograph Collection" },
  { id: "FRAFV", officialName: "Falkenstein Grand, Autograph Collection" },
  { id: "FRANV", officialName: "LUME Boutique Hotel, Autograph Collection" },
  { id: "FRAKR", officialName: "Roomers Frankfurt Central, Autograph Collection" },
  { id: "HAMAK", officialName: "Hotel Atlantic Hamburg, Autograph Collection" },
  { id: "HHNAK", officialName: "Schloss Lieser, Autograph Collection" },
  { id: "HAMKL", officialName: "Louis C. Jacob, Hamburg, Autograph Collection" },
  { id: "HHNBS", officialName: "Bollants SPA im Park, Autograph Collection" },
  { id: "MUCAK", officialName: "The Dean Munich, Autograph Collection" },
  { id: "MUCAT", officialName: "Caro & Selig, Tegernsee, Autograph Collection" },
  { id: "STRFK", officialName: "DAS AFFALTERBACH, Stuttgart, Autograph Collection" },
  { id: "CGNLD", officialName: "Delta Hotels Leverkusen" },
  { id: "FRADE", officialName: "Delta Hotels by Marriott Frankfurt Offenbach" },
  { id: "ACHSZ", officialName: "Seegut Zeppelin, a Member of Design Hotels" },
  { id: "BERDS", officialName: "Provocateur, Berlin, a Member of Design Hotels™" },
  { id: "BERMH", officialName: "The Mandala Berlin, a Member of Design Hotels" },
  { id: "BERKP", officialName: "KPM Hotel & Residences Berlin, a Member of Design Hotels™" },
  { id: "CGNQH", officialName: "THE QVEST Hideaway, a Member of Design Hotels" },
  { id: "FRATP", officialName: "The Pure, a Member of Design Hotels™" },
  { id: "FMOMM", officialName: "Mauritzhof Hotel Muenster, a Member of Design Hotels™" },
  { id: "HAJGN", officialName: "FREIgeist Göttingen Nordstadt, a Member of Design Hotels™" },
  { id: "HAMSD", officialName: "SIDE, a Member of Design Hotels™" },
  { id: "HAMTG", officialName: "The George Hotel, a Member of Design Hotels™" },
  { id: "HAJFE", officialName: "FREIgeist Einbeck, a Member of Design Hotels™" },
  { id: "SXBHL", officialName: "Hotel Liberty, a Member of Design Hotels™" },
  { id: "FRAMD", officialName: "Le Méridien Frankfurt" },
  { id: "HAMMD", officialName: "Le Méridien Hamburg" },
  { id: "MUCMD", officialName: "Le Méridien Munich" },
  { id: "NUEMD", officialName: "Le Méridien Grand Hotel Nuremberg" },
  { id: "STRMD", officialName: "Le Méridien Stuttgart" },
  { id: "BERMC", officialName: "Berlin Marriott Hotel" },
  { id: "CGNBO", officialName: "Bonn Marriott Hotel" },
  { id: "CGNMC", officialName: "Cologne Marriott Hotel" },
  { id: "FRADT", officialName: "Frankfurt Marriott Hotel" },
  { id: "FRAAP", officialName: "Frankfurt Airport Marriott Hotel" },
  { id: "HDBMC", officialName: "Heidelberg Marriott Hotel" },
  { id: "HAMDT", officialName: "Hamburg Marriott Hotel" },
  { id: "LEJDT", officialName: "Leipzig Marriott Hotel" },
  { id: "MUCFR", officialName: "Munich Airport Marriott Hotel" },
  { id: "MUCNO", officialName: "Munich Marriott Hotel" },
  { id: "MUCWE", officialName: "Munich Marriott Hotel City West" },
  { id: "ZPZDE", officialName: "Stuttgart Marriott Hotel Sindelfingen" },
  { id: "HAMRN", officialName: "Renaissance Hamburg Hotel" },
  { id: "BERSI", officialName: "Sheraton Berlin Grand Hotel Esplanade" },
  { id: "DUSSO", officialName: "Sheraton Duesseldorf Airport Hotel" },
  { id: "DUSSE", officialName: "Sheraton Essen Hotel" },
  { id: "FRAAS", officialName: "Sheraton Frankfurt Airport Hotel and Conference Center" },
  { id: "FRAIO", officialName: "Sheraton Offenbach Hotel" },
  { id: "HAJSI", officialName: "Sheraton Hannover Pelikan Hotel" },
  { id: "NUESI", officialName: "Sheraton Carlton Hotel Nuernberg" },
  { id: "CGNTF", officialName: "the Deutz, a Tribute Portfolio Hotel" },
  { id: "FRATX", officialName: "Gekko House, Frankfurt, a Tribute Portfolio Hotel" },
  { id: "MUCSB", officialName: "Arabella Alpenhotel am Spitzingsee, a Tribute Portfolio Hotel" },
  { id: "MUCLB", officialName: "Flesslers Lenggries, a Tribute Portfolio Hotel" },
  { id: "BERWI", officialName: "The Westin Grand Berlin" },
  { id: "FRAWI", officialName: "The Westin Grand Frankfurt" },
  { id: "HAMWI", officialName: "The Westin Hamburg Elbphilharmonie" },
  { id: "LEJWI", officialName: "The Westin Leipzig" },
  { id: "MUCWI", officialName: "The Westin Grand Munich" },
  { id: "BERAC", officialName: "AC Hotel Berlin Humboldthain Park" },
  { id: "FRAMZ", officialName: "AC Hotel Mainz" },
  { id: "NUEAC", officialName: "AC Hotel Wuerzburg" },
  { id: "MUCAL", officialName: "Aloft by Marriott Munich" },
  { id: "STRAL", officialName: "Aloft by Marriott Stuttgart" },
  { id: "BRECY", officialName: "Courtyard by Marriott Bremen" },
  { id: "BSLFR", officialName: "Courtyard by Marriott Freiburg" },
  { id: "BERMT", officialName: "Courtyard by Marriott Berlin City Center" },
  { id: "CGNCY", officialName: "Courtyard by Marriott Cologne" },
  { id: "DRSCY", officialName: "Courtyard by Marriott Dresden" },
  { id: "DUSCY", officialName: "Courtyard by Marriott Duesseldorf Seestern" },
  { id: "DUSHF", officialName: "Courtyard by Marriott Duesseldorf Hafen" },
  { id: "DTMCY", officialName: "Courtyard by Marriott Dortmund" },
  { id: "FRAWB", officialName: "Courtyard by Marriott Wiesbaden-Nordenstadt" },
  { id: "HAMCY", officialName: "Courtyard by Marriott Hamburg Airport" },
  { id: "HAJCY", officialName: "Courtyard by Marriott Hannover Maschsee" },
  { id: "HAMHC", officialName: "Courtyard by Marriott Hamburg City" },
  { id: "LBCSC", officialName: "Courtyard by Marriott Schwerin" },
  { id: "LEJMY", officialName: "Courtyard by Marriott Magdeburg" },
  { id: "MUCCG", officialName: "Courtyard by Marriott Munich Garching" },
  { id: "MUCCY", officialName: "Courtyard by Marriott Munich City Center" },
  { id: "MUCMS", officialName: "Courtyard by Marriott Oberpfaffenhofen Munich South" },
  { id: "MUCOR", officialName: "Courtyard by Marriott Munich City East" },
  { id: "WFGCY", officialName: "Courtyard by Marriott Wolfsburg" },
  { id: "DUSEP", officialName: "FOUR Essen City Centre" },
  { id: "FRAOP", officialName: "Four Points by Sheraton Offenbach Plaza" },
  { id: "MUCAP", officialName: "Four Points by Sheraton Munich Arabellapark" },
  { id: "MUCMU", officialName: "Four Points by Sheraton Munich Messe" },
  { id: "DUSRP", officialName: "Four Points Flex Ratingen Düsseldorf Airport" },
  { id: "DTMBF", officialName: "Four Points Flex by Sheraton Bochum" },
  { id: "DUSEF", officialName: "Four Points Flex by Sheraton Essen" },
  { id: "HHNKF", officialName: "Four Points Flex by Sheraton Koblenz" },
  { id: "HAJGF", officialName: "Four Points Flex by Sheraton Goettingen" },
  { id: "HAJXF", officialName: "Four Points Flex by Sheraton Hannover" },
  { id: "HAMKF", officialName: "Four Points Flex by Sheraton Kiel" },
  { id: "MHGOU", officialName: "Four Points Flex by Sheraton Östringen" },
  { id: "BEROM", officialName: "Moxy Berlin Humboldthain Park" },
  { id: "BEROX", officialName: "Moxy Berlin Ostbahnhof" },
  { id: "BREOX", officialName: "Moxy Bremen" },
  { id: "BEROA", officialName: "Moxy Berlin Airport" },
  { id: "CGNOA", officialName: "Moxy Cologne Bonn Airport" },
  { id: "CGNOM", officialName: "Moxy Cologne Muelheim" },
  { id: "DRSOX", officialName: "Moxy Dresden Neustadt" },
  { id: "DUSOD", officialName: "Moxy Duesseldorf South" },
  { id: "DUSOX", officialName: "Moxy Essen City" },
  { id: "DUSCC", officialName: "Moxy Duesseldorf City" },
  { id: "DTMOD", officialName: "Moxy Dortmund City" },
  { id: "DTMBO", officialName: "Moxy Bochum" },
  { id: "FRADO", officialName: "Moxy Darmstadt" },
  { id: "FRAOE", officialName: "Moxy Frankfurt Eschborn" },
  { id: "FRAOH", officialName: "Moxy Frankfurt East" },
  { id: "FRAOK", officialName: "Moxy Frankfurt Airport Kelsterbach" },
  { id: "FRAOR", officialName: "Moxy Frankfurt City Center" },
  { id: "FRAOX", officialName: "Moxy Frankfurt Airport" },
  { id: "FRAOS", officialName: "Moxy Simmern" },
  { id: "FKBLL", officialName: "Moxy Karlsruhe" },
  { id: "HAMHX", officialName: "Moxy Hamburg City" },
  { id: "HAMOA", officialName: "Moxy Hamburg Altona" },
  { id: "HDBOX", officialName: "Moxy Ludwigshafen" },
  { id: "HAMFO", officialName: "Moxy Hamburg - Finkenwerder" },
  { id: "MUCOE", officialName: "Moxy Munich Ostbahnhof" },
  { id: "MUCOM", officialName: "Moxy Munich Messe" },
  { id: "MUCOX", officialName: "Moxy Munich Airport" },
  { id: "NUEOX", officialName: "Moxy Wuerzburg" },
  { id: "STROX", officialName: "Moxy Stuttgart Airport/Messe" },
  { id: "STRSX", officialName: "Moxy Stuttgart Feuerbach" },
  { id: "SXBOR", officialName: "MOXY Rust" },
  { id: "STROO", officialName: "Moxy Outletcity Metzingen" },
  { id: "STRKH", officialName: "Moxy Kupferzell Hohenlohe" },
  { id: "DUSRI", officialName: "Residence Inn by Marriott Essen City" },
  { id: "DTMRI", officialName: "Residence Inn by Marriott Dortmund City" },
  { id: "FRARI", officialName: "Residence Inn by Marriott Frankfurt City Center" },
  { id: "HAMRA", officialName: "Residence Inn by Marriott Hamburg Altona" },
  { id: "MUCMR", officialName: "Residence Inn by Marriott Munich Ostbahnhof" },
  { id: "MUCRI", officialName: "Residence Inn by Marriott Munich City East" },
  { id: "MUCZR", officialName: "Residence Inn by Marriott Munich Central" },
] as const;

export const germanyMarriottProperties: MarriottProperty[] = germanyMarriottOfficialRows.map(
  ({ id, officialName }) => ({
    id,
    country: "DE",
    region: "overseas",
    officialName,
    brand: inferBrand(officialName),
    ...high,
    aliases: [],
  })
);
