import { applyCuratedMarriottPropertyAliases } from "../marriottPropertyOverrides";
import { high, inferBrand } from "./helpers";
import type { MarriottPropertySeed } from "./types";

// Source: Marriott hotel sitemap property codes, July 2026.
const spainMarriottOfficialRows = [
  { id: "BCNEB", officialName: "The Barcelona EDITION" },
  { id: "MADEB", officialName: "The Madrid EDITION" },
  { id: "BIOLC", officialName: "Hotel Marqués de Riscal, a Luxury Collection Hotel, Elciego" },
  { id: "EASLC", officialName: "Hotel Maria Cristina, a Luxury Collection Hotel, San Sebastian" },
  { id: "MADLC", officialName: "Santo Mauro, a Luxury Collection Hotel, Madrid" },
  { id: "MADCL", officialName: "The Palace, a Luxury Collection Hotel, Madrid" },
  { id: "PMILC", officialName: "Castillo Hotel Son Vida, a Luxury Collection Hotel, Mallorca" },
  { id: "SVQLC", officialName: "Hotel Alfonso XIII, a Luxury Collection Hotel, Seville" },
  { id: "MADJW", officialName: "JW Marriott Hotel Madrid" },
  { id: "PMIXR", officialName: "The St. Regis Mardavall Mallorca Resort" },
  { id: "BCNWH", officialName: "W Barcelona" },
  { id: "IBZWH", officialName: "W Ibiza" },
  { id: "AGPLD", officialName: "Grand Hotel Las Dunas, Autograph Collection" },
  { id: "BCNAK", officialName: "Cotton House Hotel, Autograph Collection" },
  { id: "BIOAK", officialName: "Hotel Ercilla de Bilbao, Autograph Collection" },
  { id: "BCNKS", officialName: "Sabàtic, Sitges, Autograph Collection" },
  { id: "GRXPA", officialName: "Hotel Palacio De Santa Paula, Autograph Collection" },
  { id: "ILDBA", officialName: "Hotel AC Baqueira Ski Resort, Autograph Collection" },
  { id: "IBZFK", officialName: "Sabatic Formentera Autograph Collection" },
  { id: "MADZM", officialName: "El Autor Hotel Madrid, Autograph Collection" },
  { id: "MADRE", officialName: "Hotel Palacio Del Retiro, Autograph Collection" },
  { id: "MADFT", officialName: "Eugenia de Montijo, Autograph Collection" },
  { id: "MADKV", officialName: "Círculo Gran Vía, Autograph Collection" },
  { id: "PMIAK", officialName: "Hacienda Son Antem Golf Resort, Autograph Collection" },
  { id: "SVQAS", officialName: "Querencia de Sevilla, Autograph Collection" },
  { id: "SCQAK", officialName: "Hotel Palacio del Carmen, Autograph Collection" },
  { id: "VLCAK", officialName: "Palacio Santa Clara, Autograph Collection" },
  { id: "VITBK", officialName: "Palacio Tondon, Autograph Collection" },
  { id: "VLCAY", officialName: "Grand Hotel Centenari, Valencia, Autograph Collection" },
  { id: "ALCDS", officialName: "Hospes Amérigo, Alicante, a Member of Design Hotels™" },
  { id: "BCNVH", officialName: "ORA Hotel Priorat, a Member of Design Hotels™" },
  { id: "BCNSV", officialName: "Sir Victor Hotel, a Member of Design Hotels™" },
  { id: "GRXDS", officialName: "Hospes Palacio de los Patos, a Member of Design Hotels™" },
  { id: "GROFV", officialName: "Finca Victoria, a Member of Design Hotels™" },
  { id: "LPABS", officialName: "Bohemia Suites & Spa, a Member of Design Hotels™" },
  { id: "LPASP", officialName: "Seaside Palm Beach, a Member of Design Hotels™" },
  { id: "MADPA", officialName: "Hospes Puerta de Alcalá, a Member of Design Hotels™" },
  { id: "PMIDS", officialName: "Hospes Maricel & Spa, Palma de Mallorca, a Member of Design Hotels™" },
  { id: "PMICN", officialName: "Concepcio by Nobis, Palma, a Member of Design Hotels™" },
  { id: "PMINP", officialName: "Nobis Hotel Palma, a Member of Design Hotels™" },
  { id: "PMIRA", officialName: "Es Racó d’Artà, a Member of Design Hotels™" },
  { id: "SLMDS", officialName: "Hospes Palacio de San Esteban , Salamanca, a Member of Design Hotels™" },
  { id: "SVQDS", officialName: "Hospes Las Casas del Rey de Baeza, a Member of Design Hotels™" },
  { id: "SVQPB", officialName: "Hospes Palacio del Bailío, a Member of Design Hotels™" },
  { id: "VLCDS", officialName: "Hospes Palau de la Mar, Valencia, a Member of Design Hotels™" },
  { id: "BCNMD", officialName: "Le Méridien Barcelona" },
  { id: "REUMD", officialName: "Le Méridien Ra Beach Hotel & Spa" },
  { id: "ALCMM", officialName: "Denia Marriott La Sella Golf Resort & Spa" },
  { id: "MADAD", officialName: "Madrid Marriott Auditorium Hotel & Conference Center" },
  { id: "MADPP", officialName: "Madrid Marriott Hotel Princesa Plaza" },
  { id: "AGPMB", officialName: "Marriott's Marbella Beach Resort" },
  { id: "AGPPY", officialName: "Marriott's Playa Andaluza" },
  { id: "PMIMC", officialName: "Marriott's Club Son Antem" },
  { id: "BCNRF", officialName: "Renaissance Barcelona Fira Hotel" },
  { id: "BCNDM", officialName: "Renaissance Barcelona Hotel" },
  { id: "FUESI", officialName: "Sheraton Fuerteventura Beach, Golf & Spa Resort" },
  { id: "PMISI", officialName: "Sheraton Mallorca Arabella Golf Hotel" },
  { id: "BCNTX", officialName: "Labtwentytwo Barcelona, a Tribute Portfolio Hotel" },
  { id: "BCNGM", officialName: "Sabàtic Gavà Mar, Barcelona, a Tribute Portfolio Hotel" },
  { id: "IBZTX", officialName: "Hotel Riomar Ibiza, a Tribute Portfolio Hotel" },
  { id: "SVQTX", officialName: "Los Seises Sevilla, a Tribute Portfolio Hotel" },
  { id: "AGPWI", officialName: "The Westin La Quinta Golf Resort & Spa, Benahavis, Marbella" },
  { id: "MADCZ", officialName: "The Westin Madrid Cuzco" },
  { id: "VLCWI", officialName: "The Westin Valencia" },
  { id: "AEIAL", officialName: "AC Hotel Algeciras" },
  { id: "AGPMG", officialName: "AC Hotel Malaga Palacio" },
  { id: "ALCAL", officialName: "AC Hotel Alicante" },
  { id: "ALCEA", officialName: "AC Hotel Elda" },
  { id: "BCNDL", officialName: "AC Hotel Diagonal L´Illa" },
  { id: "BCNIR", officialName: "AC Hotel Irla" },
  { id: "BCNSC", officialName: "AC Hotel Sant Cugat" },
  { id: "BCNSM", officialName: "AC Hotel Som" },
  { id: "BCNSU", officialName: "AC Hotel Victoria Suites" },
  { id: "BJZBA", officialName: "AC Hotel Badajoz" },
  { id: "BCNSA", officialName: "AC Hotel Sants" },
  { id: "HEVHU", officialName: "AC Hotel Huelva" },
  { id: "LCGCO", officialName: "AC Hotel A Coruna" },
  { id: "LENAC", officialName: "AC Hotel Leon San Antonio" },
  { id: "LENPO", officialName: "AC Hotel Ponferrada" },
  { id: "LPAAC", officialName: "AC Hotel Iberia Las Palmas" },
  { id: "LPAGR", officialName: "AC Hotel Gran Canaria" },
  { id: "MADAI", officialName: "AC Hotel Aitana" },
  { id: "MADAL", officialName: "AC Hotel Alcala de Henares" },
  { id: "MADAT", officialName: "AC Hotel Atocha" },
  { id: "MADAV", officialName: "AC Hotel Avenida de America" },
  { id: "MADCA", officialName: "AC Hotel Carlton Madrid" },
  { id: "MADCO", officialName: "AC Hotel Madrid Airport" },
  { id: "MADFE", officialName: "AC Hotel Madrid Feria" },
  { id: "MADFI", officialName: "AC Hotel La Finca" },
  { id: "MADGU", officialName: "AC Hotel Guadalajara, Spain" },
  { id: "MADRC", officialName: "AC Hotel Recoletos" },
  { id: "MADSE", officialName: "AC Hotel San Sebastian de los Reyes" },
  { id: "MADTO", officialName: "AC Hotel Ciudad de Toledo" },
  { id: "MADVA", officialName: "AC Hotel Los Vascos" },
  { id: "MJVMU", officialName: "AC Hotel Murcia" },
  { id: "ODBCO", officialName: "AC Hotel Cordoba" },
  { id: "OVDFO", officialName: "AC Hotel Oviedo Forum" },
  { id: "OVDGI", officialName: "AC Hotel Gijón" },
  { id: "PMIMA", officialName: "AC Hotel Ciutat de Palma" },
  { id: "PNATU", officialName: "AC Hotel Ciudad de Tudela" },
  { id: "REUTA", officialName: "AC Hotel Tarragona" },
  { id: "RGSBU", officialName: "AC Hotel Burgos" },
  { id: "RJLLO", officialName: "AC Hotel La Rioja" },
  { id: "RMUCP", officialName: "AC Hotel Cartagena" },
  { id: "SLMZA", officialName: "AC Hotel Zamora" },
  { id: "SVQCI", officialName: "AC Hotel Ciudad de Sevilla" },
  { id: "SVQJU", officialName: "AC Hotel Sevilla Forum" },
  { id: "TFNAC", officialName: "AC Hotel Tenerife" },
  { id: "VGOPA", officialName: "AC Hotel Palacio Universal" },
  { id: "VLCVA", officialName: "AC Hotel Valencia" },
  { id: "VLLAN", officialName: "AC Hotel Palacio de Santa Ana" },
  { id: "VLLPA", officialName: "AC Hotel Palencia" },
  { id: "XRYLI", officialName: "AC Hotel La Linea" },
  { id: "MADGV", officialName: "Aloft by Marriott Madrid Gran Via" },
  { id: "ALCFV", officialName: "Four Points by Sheraton Costa Blanca Villas" },
  { id: "ALCFP", officialName: "Four Points by Sheraton Costa Blanca Resort" },
  { id: "BCNFP", officialName: "Four Points by Sheraton Barcelona Diagonal" },
  { id: "BCNVP", officialName: "Four Points by Sheraton Barcelona Airport" },
  { id: "AGPXF", officialName: "Four Points Flex by Sheraton Malaga Centre" },
  { id: "MADAX", officialName: "Four Points Flex by Sheraton Madrid Atocha" },
  { id: "BCNOX", officialName: "Moxy Barcelona" },
  // Ritz-Carlton HWS XML property codes, July 2026.
  { id: "BCNRZ", officialName: "Hotel Arts Barcelona" },
  { id: "TFSRZ", officialName: "The Ritz-Carlton Tenerife, Abama" },
] as const;

export const spainMarriottProperties: MarriottPropertySeed[] = spainMarriottOfficialRows.map(
  ({ id, officialName }) =>
    applyCuratedMarriottPropertyAliases({
      id,
      country: "ES",
      region: "overseas",
      officialName,
      brand: inferBrand(officialName),
      ...high,
      aliases: [],
    })
);
