import { high, inferBrand } from "./helpers";
import type { MarriottProperty } from "./types";

// Source: Marriott hotel sitemap property codes, July 2026.
const franceMarriottOfficialRows = [
  { id: "NCEHC", officialName: "Hôtel du Couvent, a Luxury Collection Hotel, Nice, France" },
  { id: "PARLC", officialName: "Prince de Galles, a Luxury Collection Hotel, Paris" },
  { id: "PARBE", officialName: "Hôtel de Berri Champs-Élysées, a Luxury Collection Hotel, Paris" },
  { id: "NCEJW", officialName: "JW Marriott Cannes" },
  { id: "LILAK", officialName: "L'Hermitage Gantois, Autograph Collection" },
  { id: "RHEAK", officialName: "La Caserne Chanzy Hotel & Spa, Autograph Collection" },
  { id: "SXBAK", officialName: "Maison Rouge Strasbourg Hotel & Spa, Autograph Collection" },
  { id: "UROAK", officialName: "Hotel de Bourgtheroulde, Autograph Collection" },
  { id: "AVNDE", officialName: "Hôtel de Tourrel, Saint Rémy de Provence, a Member of Design Hotels™" },
  { id: "DIJDS", officialName: "Vertigo Hotel, Dijon, a Member of Design Hotels™" },
  { id: "MRSDA", officialName: "Domaine des Andéols, a Member of Design Hotels" },
  { id: "NCEDF", officialName: "Five Seas Cannes, a Member of Design Hotels™" },
  { id: "PARDS", officialName: "La Maison Champs Elysées, Paris, a Member of Design Hotels™" },
  { id: "PARLR", officialName: "Le Roch Hotel and Spa, Paris, a Member of Design Hotels™" },
  { id: "PARLP", officialName: "Le Pigalle, a Member of Design Hotels™" },
  { id: "PARWA", officialName: "Hôtel Wallace, a Member of Design Hotels™" },
  { id: "PARRO", officialName: "Hôtel Rochechouart, a Member of Design Hotels™" },
  { id: "PARCR", officialName: "Château de la Resle, a Member of Design Hotels™" },
  { id: "NCEMD", officialName: "Le Méridien Nice" },
  { id: "PARMD", officialName: "Le Méridien Paris Arc De Triomphe" },
  { id: "LYSMC", officialName: "Lyon Marriott Hotel Cité Internationale" },
  { id: "MCMCD", officialName: "Riviera Marriott Hotel La Porte de Monaco" },
  { id: "PARMC", officialName: "Paris Marriott Charles de Gaulle Airport Hotel" },
  { id: "PARST", officialName: "Paris Marriott Rive Gauche Hotel & Conference Center" },
  { id: "PAROA", officialName: "Paris Marriott Opera Ambassador Hotel" },
  { id: "PARDT", officialName: "Paris Marriott Champs Elysees Hotel" },
  { id: "PARDP", officialName: "Marriott's Village d'ile-de-France" },
  { id: "BODBR", officialName: "Renaissance Bordeaux Hotel" },
  { id: "MRSBR", officialName: "Renaissance Aix-en-Provence Hotel" },
  { id: "PARLD", officialName: "Renaissance Paris La Defense Hotel" },
  { id: "PARSP", officialName: "Renaissance Paris Nobel Tour Eiffel Hotel" },
  { id: "PARVD", officialName: "Renaissance Paris Vendome Hotel" },
  { id: "PARSC", officialName: "Renaissance Paris Hippodrome de St. Cloud Hotel" },
  { id: "PARWG", officialName: "Renaissance Paris Arc de Triomphe Hotel" },
  { id: "PARPR", officialName: "Renaissance Paris Republique Hotel" },
  { id: "NCESI", officialName: "Sheraton Nice" },
  { id: "PARSI", officialName: "Sheraton Paris Charles de Gaulle Airport Hotel" },
  { id: "NCEMB", officialName: "La Bastide de Mougins, a Tribute Portfolio Hotel" },
  { id: "NCETC", officialName: "Nice Centre Hotel" },
  { id: "PARTX", officialName: "Le Dokhan's, Paris Arc de Triomphe, a Tribute Portfolio Hotel" },
  { id: "PARXT", officialName: "Le Metropolitan, Paris Tour Eiffel, a Tribute Portfolio Hotel" },
  { id: "PARBT", officialName: "Le Parchamp, Paris Boulogne, a Tribute Portfolio Hotel" },
  { id: "PARGN", officialName: "Clubtrotteur Paris, a Tribute Portfolio Hotel" },
  { id: "GVASJ", officialName: "AC Hotel Saint-Julien-en-Genevois" },
  { id: "JLPAR", officialName: "AC Hotel Ambassadeur Antibes- Juan les Pins" },
  { id: "MRSAR", officialName: "AC Hotel Marseille Prado Velodrome" },
  { id: "NCEAC", officialName: "AC Hotel Nice" },
  { id: "PARAL", officialName: "AC Hotel Paris Le Bourget Airport" },
  { id: "PARAR", officialName: "AC Hotel Paris Porte Maillot" },
  { id: "SXBAR", officialName: "AC Hotel Strasbourg" },
  { id: "LYSDA", officialName: "Aloft by Marriott Dijon" },
  { id: "SXBAL", officialName: "Aloft by Marriott Strasbourg City Centre" },
  { id: "LYSYE", officialName: "Courtyard by Marriott Lyon Eurexpo Stadium" },
  { id: "MPLCY", officialName: "Courtyard by Marriott Montpellier" },
  { id: "PARAC", officialName: "Courtyard by Marriott Paris Arcueil" },
  { id: "PARCC", officialName: "Courtyard by Marriott Paris Creteil" },
  { id: "PARCF", officialName: "Courtyard by Marriott Paris La Defense West - Colombes" },
  { id: "PARSD", officialName: "Courtyard by Marriott Paris Saint Denis" },
  { id: "PARCA", officialName: "Courtyard by Marriott Paris Charles de Gaulle Central Airport" },
  { id: "PARGL", officialName: "Courtyard by Marriott Paris Gare de Lyon" },
  { id: "PARCV", officialName: "Courtyard by Marriott Paris Porte de Versailles" },
  { id: "TLSCY", officialName: "Courtyard by Marriott Toulouse Airport" },
  { id: "XCRRP", officialName: "Four Points by Sheraton Reims Cathédrale" },
  { id: "BVAOX", officialName: "Moxy Amiens" },
  { id: "BODOX", officialName: "Moxy Bordeaux" },
  { id: "GVACX", officialName: "Moxy Annecy" },
  { id: "LILOX", officialName: "Moxy Lille City" },
  { id: "LYSOX", officialName: "Moxy Lyon Airport" },
  { id: "NCEOA", officialName: "Moxy Antibes Sophia Antipolis" },
  { id: "NCEOX", officialName: "Moxy Nice" },
  { id: "PAROB", officialName: "Moxy Paris Bastille" },
  { id: "PAROX", officialName: "Moxy Paris Charles de Gaulle Airport" },
  { id: "PARCX", officialName: "Moxy Paris Clamart" },
  { id: "PAROL", officialName: "Moxy Paris Val d’Europe" },
  { id: "PARVX", officialName: "Moxy Paris La Villette" },
  { id: "LILRI", officialName: "Residence Inn by Marriott Lille" },
  { id: "PARRI", officialName: "Residence Inn by Marriott Paris Charles de Gaulle Central Airport" },
  { id: "PARRN", officialName: "Residence Inn by Marriott Paris Didot Montparnasse" },
  { id: "SXBRI", officialName: "Residence Inn by Marriott Strasbourg" },
  { id: "TLSTB", officialName: "Residence Inn by Marriott Toulouse-Blagnac Airport" },
] as const;

export const franceMarriottProperties: MarriottProperty[] = franceMarriottOfficialRows.map(
  ({ id, officialName }) => ({
    id,
    country: "FR",
    region: "overseas",
    officialName,
    brand: inferBrand(officialName),
    ...high,
    aliases: [],
  })
);
