import { high, inferBrand } from "./helpers";
import type { MarriottPropertySeed } from "./types";

// Source: Marriott hotel sitemap property codes, July 2026.
const unitedKingdomMarriottOfficialRows = [
  { id: "LONBG", officialName: "Bvlgari Hotel London" },
  { id: "LONEB", officialName: "The London EDITION" },
  { id: "EDILG", officialName: "The Edinburgh Grand, a Luxury Collection Hotel, Edinburgh" },
  { id: "LONIV", officialName: "The Langley, a Luxury Collection Hotel, Buckinghamshire" },
  { id: "LONLC", officialName: "The Park Tower Knightsbridge, a Luxury Collection Hotel, London" },
  { id: "LONWB", officialName: "The Wellesley Knightsbridge, a Luxury Collection Hotel, London" },
  { id: "LONGH", officialName: "JW Marriott Grosvenor House London" },
  { id: "EDIWH", officialName: "W Edinburgh" },
  { id: "LONHW", officialName: "W London" },
  { id: "CBGAK", officialName: "University Arms Hotel, Autograph Collection" },
  { id: "EDIOC", officialName: "Old Town Chambers, Autograph Collection" },
  { id: "EDIAK", officialName: "The Glasshouse, Autograph Collection" },
  { id: "LONDX", officialName: "The Dixon, Tower Bridge, Autograph Collection" },
  { id: "LONKB", officialName: "Bankside Hotel, Autograph Collection" },
  { id: "LONSE", officialName: "St. Ermin's Hotel, Autograph Collection" },
  { id: "LONXE", officialName: "Hotel Xenia, Autograph Collection" },
  { id: "LONAM", officialName: "Montcalm East, Autograph Collection" },
  { id: "LONSH", officialName: "The Stratford, Autograph Collection" },
  { id: "LONMM", officialName: "Montcalm Mayfair, Autograph Collection" },
  { id: "LONPK", officialName: "St. Pancras London, Autograph Collection" },
  { id: "LONMK", officialName: "Montcalm Royal London House, Autograph Collection " },
  { id: "LONAK", officialName: "Threadneedles, Autograph Collection" },
  { id: "MANSE", officialName: "Stock Exchange Hotel, Manchester, Autograph Collection" },
  { id: "BHXDE", officialName: "Delta Hotels Birmingham" },
  { id: "BRSDE", officialName: "Delta Hotels Bristol City Centre" },
  { id: "BRSSD", officialName: "Delta Hotels Swindon" },
  { id: "BRSSP", officialName: "Delta Hotels St. Pierre Country Club" },
  { id: "CWLSD", officialName: "Delta Hotels Swansea" },
  { id: "EDIDE", officialName: "Delta Hotels Edinburgh" },
  { id: "EMAPD", officialName: "Delta Hotels Breadsall Priory Country Club" },
  { id: "LTNDE", officialName: "Delta Hotels Milton Keynes" },
  { id: "LHRWD", officialName: "Delta Hotels Heathrow Windsor" },
  { id: "LONDB", officialName: "Delta Hotels Bexleyheath" },
  { id: "LONTP", officialName: "Delta Hotels Tudor Park Country Club" },
  { id: "LONDP", officialName: "Delta Hotels Peterborough" },
  { id: "LPLDE", officialName: "Delta Hotels Liverpool City Centre" },
  { id: "LONND", officialName: "Delta Hotels Northampton" },
  { id: "LBAYD", officialName: "Delta Hotels York" },
  { id: "LONWD", officialName: "Delta Hotels Waltham Abbey" },
  { id: "LONHD", officialName: "Delta Hotels Huntingdon" },
  { id: "MANDA", officialName: "Delta Hotels Manchester Airport" },
  { id: "MANPD", officialName: "Delta Hotels Preston" },
  { id: "MANWP", officialName: "Delta Hotels Worsley Park Country Club" },
  { id: "NCLDD", officialName: "Delta Hotels Durham Royal County" },
  { id: "NCLMD", officialName: "Delta Hotels Newcastle Gateshead" },
  { id: "STNCD", officialName: "Delta Hotels Cheshunt" },
  { id: "STNDE", officialName: "Delta Hotels Colchester" },
  { id: "LONTH", officialName: "Town Hall Hotel, London, a Member of Design Hotels™" },
  { id: "LONIS", officialName: "Inhabit Southwick Street, a Member of Design Hotels™" },
  { id: "LONIQ", officialName: "Inhabit Queen's Gardens, a Member of Design Hotels™" },
  { id: "LONSD", officialName: "Sir Devonshire Square, a Member of Design Hotels" },
  { id: "LONTG", officialName: "Miiro Templeton Garden, a Member of Design Hotels™" },
  { id: "BOHBM", officialName: "Bournemouth Highcliff Marriott Hotel" },
  { id: "BRSRY", officialName: "Bristol Marriott Royal Hotel" },
  { id: "CWLDT", officialName: "Cardiff Marriott Hotel" },
  { id: "EMALM", officialName: "Leicester Marriott Hotel" },
  { id: "EDIMH", officialName: "Edinburgh Marriott Hotel Holyrood" },
  { id: "GLADT", officialName: "Glasgow Marriott Hotel" },
  { id: "LONCH", officialName: "London Marriott Hotel County Hall" },
  { id: "LBADT", officialName: "Leeds Marriott Hotel" },
  { id: "LHRHR", officialName: "London Heathrow Marriott Hotel" },
  { id: "LONCW", officialName: "London Marriott Hotel Canary Wharf" },
  { id: "LONMA", officialName: "London Marriott Hotel Marble Arch" },
  { id: "LONWH", officialName: "London Marriott Hotel Maida Vale" },
  { id: "LGWGS", officialName: "Lingfield Park Marriott Hotel & Country Club" },
  { id: "LONDT", officialName: "London Marriott Hotel Grosvenor Square" },
  { id: "LONPL", officialName: "London Marriott Hotel Park Lane" },
  { id: "LONLM", officialName: "London Marriott Hotel Kensington" },
  { id: "LONRP", officialName: "London Marriott Hotel Regents Park" },
  { id: "MANVA", officialName: "Manchester Marriott Victoria & Albert Hotel" },
  { id: "MANMP", officialName: "Manchester Marriott Hotel Piccadilly" },
  { id: "PMEHA", officialName: "Portsmouth Marriott Hotel" },
  { id: "STNGS", officialName: "Hanbury Manor Marriott Hotel & Country Club" },
  { id: "LONQL", officialName: "Grand Residences by Marriott - Mayfair-London" },
  { id: "LHRBR", officialName: "Renaissance London Heathrow Hotel" },
  { id: "EDISI", officialName: "Sheraton Grand Hotel & Spa, Edinburgh" },
  { id: "LHRSS", officialName: "Sheraton Skyline Hotel London Heathrow" },
  { id: "LONGR", officialName: "Sheraton Grand London Park Lane" },
  { id: "LHRSI", officialName: "Sheraton Heathrow Hotel" },
  { id: "BRSTX", officialName: "Abbey Hotel Bath, a Tribute Portfolio Hotel" },
  { id: "BHXBM", officialName: "Billesley Manor Hotel & Spa, a Tribute Portfolio Hotel" },
  { id: "LONHY", officialName: "Hyde & Seek, London Hyde Park, a Tribute Portfolio Hotel" },
  { id: "LONPG", officialName: "The Cura Hotel Kensington, London, a Tribute Portfolio Hotel" },
  { id: "MANTX", officialName: "Hotel Football, Old Trafford, a Tribute Portfolio Hotel" },
  { id: "MANTR", officialName: "The Reach at Piccadilly, Manchester, a Tribute Portfolio Hotel" },
  { id: "LONWI", officialName: "The Westin London City" },
  { id: "BFSAC", officialName: "AC Hotel Belfast" },
  { id: "BHXAC", officialName: "AC Hotel Birmingham" },
  { id: "BHXAP", officialName: "AC Hotel by Marriott Birmingham NEC and Airport" },
  { id: "GLAAR", officialName: "AC Hotel Glasgow" },
  { id: "INVAR", officialName: "AC Hotel Inverness" },
  { id: "MANAC", officialName: "AC Hotel Manchester Salford Quays" },
  { id: "MANAQ", officialName: "AC Hotel Manchester City Centre" },
  { id: "ABZAL", officialName: "Aloft by Marriott Aberdeen TECA" },
  { id: "BHXAL", officialName: "Aloft by Marriott Birmingham Eastside" },
  { id: "BFSLT", officialName: "Aloft by Marriott Belfast Titanic Quarter" },
  { id: "LONAL", officialName: "Aloft by Marriott London Excel" },
  { id: "LPLAL", officialName: "Aloft by Marriott Liverpool" },
  { id: "ABZCY", officialName: "Courtyard by Marriott Aberdeen Airport" },
  { id: "DSACY", officialName: "Courtyard by Marriott Sheffield" },
  { id: "EDICY", officialName: "Courtyard by Marriott Edinburgh" },
  { id: "EDIHW", officialName: "Courtyard by Marriott Edinburgh West" },
  { id: "EXTCY", officialName: "Courtyard by Marriott Exeter Sandy Park" },
  { id: "GLACA", officialName: "Courtyard by Marriott Glasgow Airport" },
  { id: "GLACG", officialName: "Courtyard by Marriott Glasgow SEC" },
  { id: "INVCY", officialName: "Courtyard by Marriott Inverness Airport" },
  { id: "LCYAP", officialName: "Courtyard by Marriott London City Airport" },
  { id: "LGWCY", officialName: "Courtyard by Marriott London Gatwick Airport" },
  { id: "LHRCY", officialName: "Courtyard by Marriott London Heathrow Airport" },
  { id: "LTNCY", officialName: "Courtyard by Marriott Luton Airport" },
  { id: "MANCK", officialName: "Courtyard by Marriott Keele Staffordshire" },
  { id: "OXFCX", officialName: "Courtyard by Marriott Oxford South" },
  { id: "OXFCY", officialName: "Courtyard by Marriott Oxford City Centre" },
  { id: "EDIFP", officialName: "Four Points by Sheraton Edinburgh" },
  { id: "LGWFP", officialName: "Four Points by Sheraton London Gatwick Airport" },
  { id: "BHXJQ", officialName: "Four Points Flex by Sheraton Birmingham Jewellery Quarter" },
  { id: "CWLSU", officialName: "Four Points Flex by Sheraton Cardiff" },
  { id: "DNDDU", officialName: "Four Points Flex by Sheraton Dundee" },
  { id: "EDIEU", officialName: "Four Points Flex by Sheraton Edinburgh" },
  { id: "LONEU", officialName: "Four Points Flex by Sheraton London Euston" },
  { id: "LONFB", officialName: "Four Points Flex by Sheraton London Shoreditch East" },
  { id: "LONBX", officialName: "Four Points Flex by Sheraton Brighton Seafront" },
  { id: "LONXK", officialName: "Four Points Flex by Sheraton London Kensington Olympia" },
  { id: "LONVX", officialName: "Four Points Flex by Sheraton London Victoria" },
  { id: "NCLNU", officialName: "Four Points Flex by Sheraton Newcastle" },
  { id: "SOUWX", officialName: "Four Points Flex by Sheraton Winchester South" },
  { id: "ABZOX", officialName: "Moxy Aberdeen Airport" },
  { id: "BHXOX", officialName: "Moxy Birmingham NEC and Airport" },
  { id: "BRSOX", officialName: "Moxy Bristol" },
  { id: "BFSOX", officialName: "Moxy Belfast City" },
  { id: "EDIOF", officialName: "Moxy Edinburgh" },
  { id: "EDIOX", officialName: "Moxy Edinburgh Airport" },
  { id: "GLAOX", officialName: "Moxy Glasgow Merchant City" },
  { id: "GLAOS", officialName: "Moxy Glasgow SEC" },
  { id: "LONOF", officialName: "Moxy London Stratford" },
  { id: "LONOR", officialName: "Moxy London Excel" },
  { id: "LONOX", officialName: "Moxy London Heathrow Airport" },
  { id: "LONSX", officialName: "Moxy Slough" },
  { id: "LTNOX", officialName: "Moxy Milton Keynes" },
  { id: "LONXP", officialName: "Moxy London Piccadilly Circus" },
  { id: "MANOC", officialName: "Moxy Chester" },
  { id: "MANOX", officialName: "Moxy Manchester City" },
  { id: "NQYPO", officialName: "Moxy Plymouth" },
  { id: "QQYOX", officialName: "Moxy York" },
  { id: "SOUOX", officialName: "Moxy Southampton" },
  { id: "LONER", officialName: "Marriott Executive Apartments London, Canary Wharf" },
  { id: "ABZRI", officialName: "Residence Inn by Marriott Aberdeen" },
  { id: "BFSRT", officialName: "Residence Inn by Marriott Belfast Titanic Quarter" },
  { id: "EDIRI", officialName: "Residence Inn by Marriott Edinburgh" },
  { id: "LHRRI", officialName: "Residence Inn by Marriott Slough" },
  { id: "LONBD", officialName: "Residence Inn by Marriott London Tower Bridge" },
  { id: "LONRI", officialName: "Residence Inn by Marriott London Bridge" },
  { id: "LONRK", officialName: "Residence Inn by Marriott London Kensington" },
  { id: "MANRI", officialName: "Residence Inn by Marriott Manchester Piccadilly" },
  { id: "EMANF", officialName: "Four Points Flex Nottingham" },
  { id: "GLACM", officialName: "citizenM Glasgow" },
  { id: "LONBS", officialName: "citizenM London Bankside" },
  { id: "LONST", officialName: "citizenM London Shoreditch" },
  { id: "LONTL", officialName: "citizenM Tower Of London" },
  { id: "LONVS", officialName: "citizenM London Victoria Station" },
  { id: "LONXR", officialName: "The St. Regis London" },
  { id: "MANAL", officialName: "Aloft Manchester City Centre" },
] as const;

export const unitedKingdomMarriottProperties: MarriottPropertySeed[] = unitedKingdomMarriottOfficialRows.map(
  ({ id, officialName }) => ({
    id,
    country: "GB",
    region: "overseas",
    officialName,
    brand: inferBrand(officialName),
    ...high,
    aliases: [],
  })
);
