import { high, inferBrand } from "./helpers";
import type { MarriottPropertySeed } from "./types";

// Source: Marriott hotel sitemap property codes, July 2026.
const greeceMarriottOfficialRows = [
  { id: "ATHGL", officialName: "King George, a Luxury Collection Hotel, Athens" },
  { id: "ATHLC", officialName: "Hotel Grande Bretagne, a Luxury Collection Hotel, Athens" },
  { id: "CHQLC", officialName: "Domes Zeen Chania, a Luxury Collection Resort, Crete" },
  { id: "CFULC", officialName: "Domes Miramare, a Luxury Collection Resort, Corfu" },
  { id: "HERLC", officialName: "Blue Palace Elounda, a Luxury Collection Resort, Crete" },
  { id: "JMKLC", officialName: "Santa Marina, a Luxury Collection Resort, Mykonos" },
  { id: "JTRLC", officialName: "Vedema, a Luxury Collection Resort, Santorini" },
  { id: "JTRML", officialName: "Mystique, a Luxury Collection Hotel, Santorini" },
  { id: "KLXLC", officialName: "The Romanos, a Luxury Collection Resort, Costa Navarino" },
  { id: "KGSPI", officialName: "Patmos Aktis, a Luxury Collection Resort & Spa, Greece" },
  { id: "MLOWC", officialName: "Domes White Coast Milos" },
  { id: "PASLC", officialName: "Cosme, a Luxury Collection Resort, Paros" },
  { id: "RHOPA", officialName: "Amoh, a Luxury Collection Resort, Rhodes" },
  { id: "CHQMJ", officialName: "JW Marriott Crete Resort & Spa" },
  { id: "KLXWH", officialName: "W Costa Navarino" },
  { id: "ATHAK", officialName: "Academias Hotel, Autograph Collection" },
  { id: "CFUAK", officialName: "Domes of Corfu, Autograph Collection" },
  { id: "HERAK", officialName: "Domes of Elounda, Autograph Collection" },
  { id: "HERDO", officialName: "Domes Noruz Chania, Autograph Collection" },
  { id: "JMKAK", officialName: "Aegon Mykonos, Autograph Collection" },
  { id: "JMKTI", officialName: "Odera, Tinos, Autograph Collection" },
  { id: "JTRST", officialName: "Domes Novos Santorini, Autograph Collection" },
  { id: "PASOR", officialName: "Orosea, Paros, Autograph Collection" },
  { id: "RHOKB", officialName: "Aphi Aura, Rhodes, Autograph Collection" },
  { id: "SKGAK", officialName: "MonAsty, Thessaloniki, Autograph Collection" },
  { id: "ZTHAZ", officialName: "Domes Aulus Zante, Autograph Collection" },
  { id: "ATHDS", officialName: "Fresh Hotel, Athens, a Member of Design Hotels™" },
  { id: "ATHND", officialName: "New Hotel, Athens, a Member of Design Hotels™" },
  { id: "ATHPS", officialName: "Periscope, Athens, a Member of Design Hotels™" },
  { id: "ATHSD", officialName: "Semiramis Hotel, Athens, a Member of Design Hotels™" },
  { id: "ATHPH", officialName: "Perianth Hotel, a Member of Design Hotels™" },
  { id: "CHQTT", officialName: "The Tanneries Hotel & Spa, a Member of Design Hotels™" },
  { id: "CHQKT", officialName: "Tella Thera, a Member of Design Hotels™" },
  { id: "GPADS", officialName: "Dexamenes Seaside Hotel, a Member of Design Hotels™" },
  { id: "HERMB", officialName: "Minos Beach Art Hotel, a Member of Design Hotels™" },
  { id: "HERPC", officialName: "Phaea Cretan Malia, a Member of Design Hotels" },
  { id: "JMKDK", officialName: "Myconian Kyma, a Member of Design Hotels™" },
  { id: "JTRNS", officialName: "NOŪS Santorini, a Member of Design Hotels™" },
  { id: "JMKMA", officialName: "Myconian Avaton, Mykonos, a Member of Design Hotels™" },
  { id: "JMKMY", officialName: "O by Myconian, Mykonos, a Member of Design Hotels™" },
  { id: "JMKMT", officialName: "Mykonos Theoxenia, a Member of Design Hotels" },
  { id: "JTRIS", officialName: "Istoria, a Member of Design Hotels™" },
  { id: "JMKRM", officialName: "Rocabella Mykonos Hotel, a Member of Design Hotels™" },
  { id: "KLXMM", officialName: "MANNA, a Member of Design Hotels" },
  { id: "MLOSS", officialName: "Stamna Sifnos, a Member of Design Hotels" },
  { id: "MLOER", officialName: "Eréma, a Member of Design Hotels™" },
  { id: "PASPP", officialName: "Parilio, a Member of Design Hotels" },
  { id: "SKGTM", officialName: "The Met Hotel, a Member of Design Hotels™" },
  { id: "SKGAS", officialName: "EKIES All Senses Resort, a Member of Design Hotels™" },
  { id: "ZTHOA", officialName: "Olea All Suite Hotel, a Member of Design Hotels™" },
  { id: "HERSM", officialName: "Vasia Resort and SPA, Sissi, Crete" },
  { id: "ATHAM", officialName: "Athens Marriott Hotel" },
  { id: "RHOSI", officialName: "Sheraton Rhodes Resort" },
  { id: "HERZB", officialName: "Alai, Crete, a Tribute Portfolio Resort" },
  { id: "KLXWI", officialName: "The Westin Resort, Costa Navarino" },
  { id: "ATHOX", officialName: "Moxy Athens City" },
  { id: "GPAOX", officialName: "Moxy Patra Marina" },
] as const;

export const greeceMarriottProperties: MarriottPropertySeed[] = greeceMarriottOfficialRows.map(
  ({ id, officialName }) => ({
    id,
    country: "GR",
    region: "overseas",
    officialName,
    brand: inferBrand(officialName),
    ...high,
    aliases: [],
  })
);
