import { high, inferBrand, propertyId } from "./helpers";
import type { MarriottProperty } from "./types";

const indonesiaOfficialNames = [
  "Fairfield by Marriott Bali Kuta Sunset Road",
  "Renaissance Bali Nusa Dua Resort",
  "The Ritz-Carlton, Bali",
  "Mandapa, a Ritz-Carlton Reserve",
  "The Bohemian Bali, a Member of Design Hotels",
  "Courtyard by Marriott Bali Nusa Dua Resort",
  "Renaissance Bali Uluwatu Resort & Spa",
  "Four Points by Sheraton Balikpapan",
  "Moxy Bandung",
  "Grand Hotel Preanger, Bandung, a Tribute Portfolio Hotel",
  "Sheraton Bandung Hotel & Towers",
  "Courtyard by Marriott Bandung Dago",
  "Four Points by Sheraton Bandung",
  "Four Points by Sheraton Batam",
  "Batam Marriott Hotel Harbour Bay",
  "The Westin Nirup Island Resort & Spa",
  "Fairfield by Marriott Bekasi",
  "Four Points by Sheraton Bekasi",
  "Fairfield by Marriott Belitung",
  "Natra Bintan, a Tribute Portfolio Resort",
  "Jakarta Marriott Hotel Gelora",
  "Innit Lombok, a Member of Design Hotels",
  "The Residences at The Ritz-Carlton Jakarta, Pacific Place",
  "The Mayflower, Jakarta - Marriott Executive Apartments",
  "The Ritz-Carlton Jakarta, Mega Kuningan",
  "The Ritz-Carlton Jakarta, Pacific Place",
  "JW Marriott Hotel Jakarta",
  "Sheraton Grand Jakarta Gandaria City Hotel",
  "The Westin Jakarta",
  "The Hermitage, a Tribute Portfolio Hotel, Jakarta",
  "Four Points by Sheraton Jakarta, Thamrin",
  "Sari Pacific Jakarta, Autograph Collection",
  "Le Méridien Jakarta",
  "Aloft by Marriott Jakarta Kebon Jeruk",
  "Aloft by Marriott Jakarta Wahid Hasyim",
  "The St. Regis Jakarta",
  "Le Méridien Bali Jimbaran",
  "KARV, A Luxury Collection Resort & Spa, Jimbaran",
  "Magia de Uma, a Member of Design Hotels",
  "Aloft by Marriott Bali Kuta at Beachwalk",
  "Four Points by Sheraton Bintan, Lagoi Bay",
  "Aloft by Marriott South Jakarta",
  "Sheraton Jakarta Soekarno Hatta Airport",
  "Fairfield by Marriott Bali Legian",
  "Fairfield by Marriott Bali Kuta Ngurah Rai",
  "Sheraton Bali Kuta Resort",
  "Four Points by Sheraton Bali, Kuta",
  "Four Points by Sheraton Bali, Ungasan",
  "TA’AKTANA, a Luxury Collection Resort & Spa, Labuan Bajo",
  "Somewhere Lombok, a Member of Design Hotels™",
  "The Sira, a Luxury Collection Resort and Spa, Lombok",
  "Sheraton Senggigi Beach Resort",
  "Four Points by Sheraton Makassar",
  "Courtyard by Marriott Manado",
  "Manado Marriott Resort & Spa",
  "Four Points by Sheraton Manado",
  "JW Marriott Hotel Medan",
  "Four Points by Sheraton Medan",
  "Marriott’s Bali Nusa Dua Gardens",
  "Avala Nusa Dua, Bali, a Tribute Portfolio Resort",
  "Marriott’s Bali Nusa Dua Terrace",
  "Amarterra Villas Resort Bali Nusa Dua, Autograph Collection",
  "The Westin Resort Nusa Dua, Bali",
  "The St. Regis Bali Resort",
  "The Laguna, a Luxury Collection Resort & Spa, Nusa Dua, Bali",
  "JW Marriott Bali Ubud Resort & Spa",
  "Lampung Marriott Resort & Spa",
  "Cicada Resort Bali Ubud, Autograph Collection",
  "W Bali - Seminyak",
  "Four Points by Sheraton Bali, Seminyak",
  "Aloft by Marriott Bali Seminyak",
  "Courtyard by Marriott Bali Seminyak Resort",
  "Sheraton Belitung Resort",
  "Moxy Solo",
  "Fairfield by Marriott Bali South Kuta",
  "Cap Karoso, a Member of Design Hotels™",
  "Four Points by Sheraton Pontianak",
  "Four Points by Sheraton Surabaya, Tunjungan Plaza",
  "Four Points by Sheraton Surabaya, Pakuwon Indah",
  "JW Marriott Hotel Surabaya",
  "Sheraton Surabaya Hotel & Towers",
  "The Westin Surabaya",
  "Aloft by Marriott Surabaya Pakuwon City",
  "Fairfield by Marriott Surabaya",
  "Fairfield by Marriott Jakarta Soekarno-Hatta Airport",
  "Sthala, a Tribute Portfolio Hotel, Ubud Bali",
  "The Westin Resort & Spa Ubud, Bali",
  "Hiliwatu, Bali Ubud, a Tribute Portfolio Resort",
  "Element by Marriott Bali Ubud",
  "Bvlgari Resort Bali",
  "Yogyakarta Marriott Hotel",
];

export const indonesiaMarriottProperties: MarriottProperty[] =
  indonesiaOfficialNames.map((officialName) => ({
    id: propertyId("ID", officialName),
    country: "ID",
    region: "overseas",
    officialName,
    brand: inferBrand(officialName),
    brandGroup: high.brandGroup,
    confidence: high.confidence,
    status: high.status,
    aliases: [],
    reason: `${officialName}은 Marriott Bonvoy 계열 호텔로 확인된 인도네시아 호텔입니다.`,
  }));
