import { high, inferBrand } from "./helpers";
import type { MarriottProperty } from "./types";

// Source: Marriott destination page property codes, July 2026.
const indonesiaOfficialRows = [
  { id: "DPSFB", officialName: "Fairfield by Marriott Bali Kuta Sunset Road" },
  { id: "DPSND", officialName: "Renaissance Bali Nusa Dua Resort" },
  { id: "DPSSW", officialName: "The Ritz-Carlton, Bali" },
  { id: "DPSUB", officialName: "Mandapa, a Ritz-Carlton Reserve" },
  { id: "DPSBB", officialName: "The Bohemian Bali, a Member of Design Hotels" },
  { id: "DPSCY", officialName: "Courtyard by Marriott Bali Nusa Dua Resort" },
  { id: "DPSUW", officialName: "Renaissance Bali Uluwatu Resort & Spa" },
  { id: "BPNFP", officialName: "Four Points by Sheraton Balikpapan" },
  { id: "BDOOX", officialName: "Moxy Bandung" },
  { id: "BDOGP", officialName: "Grand Hotel Preanger, Bandung, a Tribute Portfolio Hotel" },
  { id: "BDOSI", officialName: "Sheraton Bandung Hotel & Towers" },
  { id: "BDOCY", officialName: "Courtyard by Marriott Bandung Dago" },
  { id: "BDOFP", officialName: "Four Points by Sheraton Bandung" },
  { id: "BTHFP", officialName: "Four Points by Sheraton Batam" },
  { id: "BTHMC", officialName: "Batam Marriott Hotel Harbour Bay" },
  { id: "BTHNI", officialName: "The Westin Nirup Island Resort & Spa" },
  { id: "JKTBF", officialName: "Fairfield by Marriott Bekasi" },
  { id: "JKTBP", officialName: "Four Points by Sheraton Bekasi" },
  { id: "TJQFI", officialName: "Fairfield by Marriott Belitung" },
  { id: "TNJTX", officialName: "Natra Bintan, a Tribute Portfolio Resort" },
  { id: "JKTMG", officialName: "Jakarta Marriott Hotel Gelora" },
  { id: "LOPIL", officialName: "Innit Lombok, a Member of Design Hotels" },
  { id: "JKTPR", officialName: "The Residences at The Ritz-Carlton Jakarta, Pacific Place" },
  { id: "JKTER", officialName: "The Mayflower, Jakarta - Marriott Executive Apartments" },
  { id: "JKTRZ", officialName: "The Ritz-Carlton Jakarta, Mega Kuningan" },
  { id: "JKTRT", officialName: "The Ritz-Carlton Jakarta, Pacific Place" },
  { id: "JKTJW", officialName: "JW Marriott Hotel Jakarta" },
  { id: "JKTGS", officialName: "Sheraton Grand Jakarta Gandaria City Hotel" },
  { id: "JKTWI", officialName: "The Westin Jakarta" },
  { id: "JKTTX", officialName: "The Hermitage, a Tribute Portfolio Hotel, Jakarta" },
  { id: "JKTTF", officialName: "Four Points by Sheraton Jakarta, Thamrin" },
  { id: "JKTAK", officialName: "Sari Pacific Jakarta, Autograph Collection" },
  { id: "JKTMD", officialName: "Le Méridien Jakarta" },
  { id: "JKTKJ", officialName: "Aloft by Marriott Jakarta Kebon Jeruk" },
  { id: "JKTAL", officialName: "Aloft by Marriott Jakarta Wahid Hasyim" },
  { id: "JKTXR", officialName: "The St. Regis Jakarta" },
  { id: "DPSMD", officialName: "Le Méridien Bali Jimbaran" },
  { id: "DPSJL", officialName: "KARV, A Luxury Collection Resort & Spa, Jimbaran" },
  { id: "DPSMA", officialName: "Magia de Uma, a Member of Design Hotels" },
  { id: "DPSKA", officialName: "Aloft by Marriott Bali Kuta at Beachwalk" },
  { id: "TNJFP", officialName: "Four Points by Sheraton Bintan, Lagoi Bay" },
  { id: "JKTAS", officialName: "Aloft by Marriott South Jakarta" },
  { id: "JKTSA", officialName: "Sheraton Jakarta Soekarno Hatta Airport" },
  { id: "DPSFI", officialName: "Fairfield by Marriott Bali Legian" },
  { id: "DPSNF", officialName: "Fairfield by Marriott Bali Kuta Ngurah Rai" },
  { id: "DPSKS", officialName: "Sheraton Bali Kuta Resort" },
  { id: "DPSKF", officialName: "Four Points by Sheraton Bali, Kuta" },
  { id: "DPSFG", officialName: "Four Points by Sheraton Bali, Ungasan" },
  { id: "LBJLC", officialName: "TA’AKTANA, a Luxury Collection Resort & Spa, Labuan Bajo" },
  { id: "LOPSL", officialName: "Somewhere Lombok, a Member of Design Hotels™" },
  { id: "LOPLC", officialName: "The Sira, a Luxury Collection Resort and Spa, Lombok" },
  { id: "LOPSI", officialName: "Sheraton Senggigi Beach Resort" },
  { id: "UPGFP", officialName: "Four Points by Sheraton Makassar" },
  { id: "MDCCY", officialName: "Courtyard by Marriott Manado" },
  { id: "MDCMC", officialName: "Manado Marriott Resort & Spa" },
  { id: "MDCFP", officialName: "Four Points by Sheraton Manado" },
  { id: "MESMC", officialName: "JW Marriott Hotel Medan" },
  { id: "MESFP", officialName: "Four Points by Sheraton Medan" },
  { id: "DPSMV", officialName: "Marriott’s Bali Nusa Dua Gardens" },
  { id: "DPSTA", officialName: "Avala Nusa Dua, Bali, a Tribute Portfolio Resort" },
  { id: "DPSVC", officialName: "Marriott’s Bali Nusa Dua Terrace" },
  { id: "DPSAV", officialName: "Amarterra Villas Resort Bali Nusa Dua, Autograph Collection" },
  { id: "DPSWI", officialName: "The Westin Resort Nusa Dua, Bali" },
  { id: "DPSXR", officialName: "The St. Regis Bali Resort" },
  { id: "DPSLC", officialName: "The Laguna, a Luxury Collection Resort & Spa, Nusa Dua, Bali" },
  { id: "DPSUJ", officialName: "JW Marriott Bali Ubud Resort & Spa" },
  { id: "TKGMC", officialName: "Lampung Marriott Resort & Spa" },
  { id: "DPSUK", officialName: "Cicada Resort Bali Ubud, Autograph Collection" },
  { id: "DPSWH", officialName: "W Bali - Seminyak" },
  { id: "DPSFP", officialName: "Four Points by Sheraton Bali, Seminyak" },
  { id: "DPSAS", officialName: "Aloft by Marriott Bali Seminyak" },
  { id: "DPSSM", officialName: "Courtyard by Marriott Bali Seminyak Resort" },
  { id: "TJQSI", officialName: "Sheraton Belitung Resort" },
  { id: "SOCOX", officialName: "Moxy Solo" },
  { id: "DPSSK", officialName: "Fairfield by Marriott Bali South Kuta" },
  { id: "TMCCK", officialName: "Cap Karoso, a Member of Design Hotels™" },
  { id: "PNKFP", officialName: "Four Points by Sheraton Pontianak" },
  { id: "SUBFP", officialName: "Four Points by Sheraton Surabaya, Tunjungan Plaza" },
  { id: "SUBFK", officialName: "Four Points by Sheraton Surabaya, Pakuwon Indah" },
  { id: "SUBJW", officialName: "JW Marriott Hotel Surabaya" },
  { id: "SUBSI", officialName: "Sheraton Surabaya Hotel & Towers" },
  { id: "SUBWI", officialName: "The Westin Surabaya" },
  { id: "SUBAL", officialName: "Aloft by Marriott Surabaya Pakuwon City" },
  { id: "SUBFI", officialName: "Fairfield by Marriott Surabaya" },
  { id: "JKTFA", officialName: "Fairfield by Marriott Jakarta Soekarno-Hatta Airport" },
  { id: "DPSTP", officialName: "Sthala, a Tribute Portfolio Hotel, Ubud Bali" },
  { id: "DPSWR", officialName: "The Westin Resort & Spa Ubud, Bali" },
  { id: "DPSHB", officialName: "Hiliwatu, Bali Ubud, a Tribute Portfolio Resort" },
  { id: "DPSEL", officialName: "Element by Marriott Bali Ubud" },
  { id: "DPSBG", officialName: "Bvlgari Resort Bali" },
  { id: "JOGMC", officialName: "Yogyakarta Marriott Hotel" },
];

export const indonesiaMarriottProperties: MarriottProperty[] =
  indonesiaOfficialRows.map(({ id, officialName }) => ({
    id: `id-${id.toLowerCase()}`,
    country: "ID",
    region: "overseas",
    officialName,
    brand: inferBrand(officialName),
    brandGroup: high.brandGroup,
    confidence: high.confidence,
    status: high.status,
    aliases: [],
    reason: `${officialName}은 Marriott Bonvoy 계열 호텔로 확인된 인도네시아 호텔입니다.`,
  }));
