import { high, inferBrand } from "./helpers";
import type { MarriottProperty } from "./types";

// Source: Marriott destination page property codes, July 2026.
const indiaOfficialRows = [
  { id: "AGRLC", officialName: "ITC Mughal, a Luxury Collection Resort & Spa, Agra" },
  { id: "AGRCY", officialName: "Courtyard by Marriott Agra" },
  { id: "AGRFI", officialName: "Fairfield by Marriott Agra" },
  { id: "AMDLC", officialName: "ITC Narmada, a Luxury Collection Hotel, Ahmedabad" },
  { id: "AMDFP", officialName: "Four Points by Sheraton Ahmedabad" },
  { id: "AMDLM", officialName: "Le Meridien Ahmedabad" },
  { id: "AMDRS", officialName: "The Fern Residency Ahmedabad, Subhash Bridge, Series by Marriott" },
  { id: "AMDRA", officialName: "The Fern Residency Ahmedabad, Ellisbridge, Series by Marriott" },
  { id: "AMDFI", officialName: "Fairfield by Marriott Ahmedabad" },
  { id: "AMDBR", officialName: "Renaissance Ahmedabad Hotel" },
  { id: "ATQMD", officialName: "Le Méridien Amritsar" },
  { id: "ATQRA", officialName: "Courtyard by Marriott Amritsar" },
  { id: "ATQFP", officialName: "Four Points by Sheraton Amritsar, Mall Road" },
  { id: "ATQFI", officialName: "Fairfield by Marriott Amritsar" },
  { id: "ATQER", officialName: "Marriott Executive Apartments Mall Road Amritsar" },
  { id: "IXYRK", officialName: "The Fern Royal Farm Resort Anjar, Series by Marriott" },
  { id: "BHOHC", officialName: "Crescent The Fern Budhni, Series by Marriott" },
  { id: "GOIHC", officialName: "The Fern Habitat Goa, Candolim, Series by Marriott" },
  { id: "IXGFI", officialName: "Fairfield by Marriott Belagavi" },
  { id: "BLRGS", officialName: "Sheraton Grand Bangalore Hotel at Brigade Gateway" },
  { id: "BLRRB", officialName: "The Fern Residency Bengaluru, Yeshwanthpur, Series by Marriott" },
  { id: "BLRRS", officialName: "The Fern Residency Bengaluru, Seshadripuram, Series by Marriott" },
  { id: "BLRNH", officialName: "JW Marriott Bengaluru Prestige Golfshire Resort & Spa" },
  { id: "BLRHB", officialName: "Courtyard by Marriott Bengaluru Hebbal" },
  { id: "BLRFI", officialName: "Fairfield by Marriott Bengaluru Outer Ring Road" },
  { id: "BLRFP", officialName: "Four Points by Sheraton Bengaluru, Whitefield" },
  { id: "BLRGL", officialName: "ITC Gardenia, a Luxury Collection Hotel, Bengaluru" },
  { id: "BLRLC", officialName: "ITC Windsor, a Luxury Collection Hotel, Bengaluru" },
  { id: "BLRSW", officialName: "Sheraton Grand Bengaluru Whitefield Hotel & Convention Center" },
  { id: "BLRWF", officialName: "Bengaluru Marriott Hotel Whitefield" },
  { id: "BLRUB", officialName: "Marriott Executive Apartments Bengaluru UB City" },
  { id: "BLRJW", officialName: "JW Marriott Hotel Bengaluru" },
  { id: "BLRFK", officialName: "Fairfield by Marriott Bengaluru Whitefield" },
  { id: "BLRFB", officialName: "Fairfield by Marriott Bengaluru Rajajinagar" },
  { id: "BLRWB", officialName: "Trinity Whitefield Bengaluru" },
  { id: "BLRTX", officialName: "Mulberry Shades Bengaluru Nandi Hills, a Tribute Portfolio Resort" },
  { id: "BLROX", officialName: "Moxy Bengaluru Airport Prestige Tech Cloud" },
  { id: "BLRAL", officialName: "Aloft by Marriott Bengaluru Outer Ring Road" },
  { id: "BLRGT", officialName: "Courtyard by Marriott Bengaluru Outer Ring Road" },
  { id: "BLRBH", officialName: "Renaissance Bengaluru Race Course Hotel" },
  { id: "BLRRZ", officialName: "The Ritz-Carlton, Bangalore" },
  { id: "BOMRB", officialName: "The Fern Residency Bhiwandi-Pimplas, Series by Marriott" },
  { id: "BHORB", officialName: "The Fern Residency Bhopal, Series by Marriott" },
  { id: "BHOCY", officialName: "Courtyard by Marriott Bhopal" },
  { id: "JAIRR", officialName: "The Fern Ranthambhore Forest Resort Sawai Madhopur, Series by Marriott" },
  { id: "PABCY", officialName: "Courtyard by Marriott Bilaspur" },
  { id: "GOIFI", officialName: "Fairfield by Marriott Goa Calangute" },
  { id: "IXCJW", officialName: "JW Marriott Hotel Chandigarh" },
  { id: "MAAVW", officialName: "The Westin Chennai Velachery" },
  { id: "MAAFC", officialName: "Fairfield by Marriott Chennai OMR" },
  { id: "MAAFP", officialName: "Four Points by Sheraton Mahabalipuram Resort & Convention Center" },
  { id: "MAAFV", officialName: "Four Points by Sheraton Chennai, Velachery" },
  { id: "MAAMD", officialName: "Le Royal Méridien Chennai" },
  { id: "MAASC", officialName: "Sheraton Grand Chennai Resort & Spa" },
  { id: "MAALC", officialName: "ITC Grand Chola, a Luxury Collection Hotel, Chennai" },
  { id: "MAAFH", officialName: "Fairfield by Marriott Chennai Mahindra World City" },
  { id: "MAAFO", officialName: "Four Points by Sheraton Chennai OMR" },
  { id: "MAACY", officialName: "Courtyard by Marriott Chennai" },
  { id: "RQYFC", officialName: "UG The Fern Resort & Spa Chikmagalur, Series by Marriott" },
  { id: "CJBFI", officialName: "Fairfield by Marriott Coimbatore" },
  { id: "GOIRK", officialName: "Kesarval The Fern Goa, Verna, Series by Marriott" },
  { id: "STVRD", officialName: "The Fern Seaside Luxurious Tent Resort Daman, Series by Marriott" },
  { id: "PNQRD", officialName: "The Fern Samali Resort Dapoli, Series by Marriott" },
  { id: "DEDFI", officialName: "Fairfield by Marriott Dehradun" },
  { id: "DEDMD", officialName: "Le Méridien Dehradun Resort & Spa" },
  { id: "IXCRS", officialName: "The Fern Surya Resort Dharampur, Kasauli Hills, Series by Marriott" },
  { id: "BDQRS", officialName: "The Fern Sardar Sarovar Resort Ekta Nagar, Series by Marriott" },
  { id: "DELAR", officialName: "Aravali Marriott Resort & Spa, Delhi NCR" },
  { id: "SXRSF", officialName: "Four Points by Sheraton Sonmarg Resort" },
  { id: "AMDRG", officialName: "The Fern Residency Gandhinagar, Series by Marriott" },
  { id: "KLHFB", officialName: "Blue Ocean The Fern Resort & Spa Ganpatipule, Series by Marriott" },
  { id: "GAYRB", officialName: "The Fern Residency Bodhgaya, Series by Marriott" },
  { id: "HDOCY", officialName: "Courtyard by Marriott Ghaziabad India" },
  { id: "GOICG", officialName: "Courtyard by Marriott Goa Colva" },
  { id: "GOIMD", officialName: "Le Méridien Goa, Calangute" },
  { id: "GOIVM", officialName: "JW Marriott Goa" },
  { id: "GOIWH", officialName: "W Goa" },
  { id: "GOIFB", officialName: "Fairfield by Marriott Goa Benaulim" },
  { id: "GOIFK", officialName: "The Fern Kadamba Hotel & Spa Goa, Panjim, Series by Marriott" },
  { id: "GOIMC", officialName: "Goa Marriott Resort & Spa" },
  { id: "GOIBR", officialName: "Renaissance Goa Hotel" },
  { id: "GOIXR", officialName: "The St. Regis Goa Resort" },
  { id: "GOIWI", officialName: "The Westin Goa" },
  { id: "GOILC", officialName: "ITC Grand Goa, a Luxury Collection Resort & Spa, Goa" },
  { id: "GOIFG", officialName: "Fairfield by Marriott Goa Anjuna" },
  { id: "BDQRG", officialName: "The Fern Residency Godhra, Series by Marriott" },
  { id: "GOPCY", officialName: "Courtyard by Marriott Gorakhpur" },
  { id: "DELBL", officialName: "ITC Grand Bharat, a Luxury Collection Retreat, Gurgaon, New Delhi Capital Region" },
  { id: "DELDM", officialName: "Le Méridien Gurgaon, Delhi NCR" },
  { id: "DELWI", officialName: "The Westin Gurgaon, New Delhi" },
  { id: "DELGU", officialName: "Courtyard by Marriott Gurugram Downtown" },
  { id: "HBXRH", officialName: "The Fern Residency Hubballi, Series by Marriott" },
  { id: "HYDCY", officialName: "Courtyard by Marriott Hyderabad" },
  { id: "HYDLC", officialName: "ITC Kakatiya, a Luxury Collection Hotel, Hyderabad" },
  { id: "HYDSI", officialName: "Sheraton Hyderabad Hotel" },
  { id: "HYDHY", officialName: "Marriott Executive Apartments Hyderabad" },
  { id: "HYDMC", officialName: "Hyderabad Marriott Hotel & Convention Centre" },
  { id: "HYDMD", officialName: "Le Meridien Hyderabad" },
  { id: "HYDFI", officialName: "Fairfield by Marriott Hyderabad Gachibowli" },
  { id: "HYDLK", officialName: "ITC Kohenur, a Luxury Collection Hotel, Hyderabad" },
  { id: "HYDWI", officialName: "The Westin Hyderabad Mindspace" },
  { id: "HYDWH", officialName: "The Westin Hyderabad Hitec City" },
  { id: "ISKFR", officialName: "Rakabi The Fern Igatpuri, Series By Marriott" },
  { id: "IDRSI", officialName: "Sheraton Grand Palace Indore" },
  { id: "IDRMH", officialName: "Indore Marriott Hotel" },
  { id: "IDRFI", officialName: "Fairfield by Marriott Indore" },
  { id: "JAIRN", officialName: "The Fern Nest Resort Jaipur, Series by Marriott" },
  { id: "JAIWK", officialName: "The Westin Jaipur Kant Kalwar Resort and Spa" },
  { id: "JAIMD", officialName: "Le Méridien Jaipur Resort & Spa" },
  { id: "JAILC", officialName: "ITC Rajputana, a Luxury Collection Hotel, Jaipur" },
  { id: "JAIFP", officialName: "Four Points by Sheraton Jaipur, City Square" },
  { id: "JAIBP", officialName: "Fairfield by Marriott Jaipur" },
  { id: "JAIMC", officialName: "Jaipur Marriott Hotel" },
  { id: "JAIFI", officialName: "Fairfield by Marriott Jaipur Tonk Road" },
  { id: "JAIFE", officialName: "The Fern Jaipur, Series by Marriott" },
  { id: "JSAMC", officialName: "Jaisalmer Marriott Resort & Spa" },
  { id: "BDQFB", officialName: "Bhanu The Fern Forest Resort & Spa Jambughoda, Series by Marriott" },
  { id: "JGARJ", officialName: "The Fern Residency Jamnagar, Series by Marriott" },
  { id: "JDHFI", officialName: "Fairfield by Marriott Jodhpur" },
  { id: "JDHRJ", officialName: "The Fern Residency Jodhpur, Series by Marriott" },
  { id: "STVRK", officialName: "The Fern Vishranta Resort Kamrej-Surat, Series by Marriott" },
  { id: "IXCNM", officialName: "Noormahal, Delhi NCR Karnal, Autograph Collection" },
  { id: "IXJMC", officialName: "Katra Marriott Resort & Spa" },
  { id: "PNQRR", officialName: "The Fern Riverview Resort Chiplun, Series by Marriott" },
  { id: "COKMD", officialName: "Le Méridien Kochi" },
  { id: "COKMK", officialName: "The Artiste Kochi, a Tribute Portfolio Hotel" },
  { id: "COKFK", officialName: "The Fern Kochi, Series by Marriott" },
  { id: "COKIC", officialName: "Courtyard by Marriott Kochi Infopark" },
  { id: "COKMC", officialName: "Kochi Marriott Hotel" },
  { id: "COKTX", officialName: "Port Muziris, a Tribute Portfolio Hotel, Kochi" },
  { id: "COKAP", officialName: "Courtyard by Marriott Kochi Airport" },
  { id: "KLHFK", officialName: "The Fern Kolhapur, Series by Marriott" },
  { id: "CCUWI", officialName: "The Westin Kolkata Rajarhat" },
  { id: "CCULC", officialName: "ITC Sonar, a Luxury Collection Hotel, Kolkata" },
  { id: "CCULR", officialName: "ITC Royal Bengal, a Luxury Collection Hotel, Kolkata" },
  { id: "CCUJW", officialName: "JW Marriott Hotel Kolkata" },
  { id: "CCUFI", officialName: "Fairfield by Marriott Kolkata" },
  { id: "LKOBR", officialName: "Renaissance Lucknow Hotel" },
  { id: "LKOFI", officialName: "Fairfield by Marriott Lucknow" },
  { id: "IXEMC", officialName: "Coorg Marriott Resort & Spa" },
  { id: "IXMCY", officialName: "Courtyard by Marriott Madurai" },
  { id: "PNQCM", officialName: "Courtyard by Marriott Mahabaleshwar" },
  { id: "PNQDM", officialName: "Le Méridien Mahabaleshwar Resort & Spa" },
  { id: "BOMJW", officialName: "JW Marriott Mumbai Juhu" },
  { id: "BOMLC", officialName: "ITC Maratha, a Luxury Collection Hotel, Mumbai" },
  { id: "BOMRC", officialName: "The Fern Residency Mumbai, The Acres Chembur, Series by Marriott" },
  { id: "BOMRF", officialName: "The Fern Fayms Resort Naigaon, Series by Marriott" },
  { id: "BOMSA", officialName: "JW Marriott Mumbai Sahar" },
  { id: "BOMRL", officialName: "ITC Grand Central, a Luxury Collection Hotel, Mumbai" },
  { id: "BOMRM", officialName: "The Fern Residency Mumbai, Mira Road, Series by Marriott" },
  { id: "BOMER", officialName: "Lakeside Chalet, Mumbai - Marriott Executive Apartments" },
  { id: "BOMFF", officialName: "Fairfield by Marriott Mumbai Andheri West" },
  { id: "BOMFG", officialName: "The Fern Mumbai, Goregaon, Series by Marriott" },
  { id: "BOMFM", officialName: "Meluha The Fern Mumbai, Powai, Series by Marriott" },
  { id: "BOMFI", officialName: "Fairfield by Marriott Mumbai International Airport" },
  { id: "BOMWI", officialName: "The Westin Mumbai Garden City" },
  { id: "BOMXR", officialName: "The St. Regis Mumbai" },
  { id: "BOMCY", officialName: "Courtyard by Marriott Mumbai International Airport" },
  { id: "BOMFP", officialName: "Four Points by Sheraton Navi Mumbai, Vashi" },
  { id: "BOMRD", officialName: "The Fern Residency Mumbai, Pritam Dadar, Series by Marriott" },
  { id: "BOMAW", officialName: "Moxy Mumbai Andheri West" },
  { id: "BOMWW", officialName: "The Westin Mumbai Powai Lake" },
  { id: "DEDJW", officialName: "JW Marriott Mussoorie Walnut Grove Resort & Spa" },
  { id: "DEDRB", officialName: "The Fern Brentwood Resort Mussoorie, Series by Marriott" },
  { id: "NAGMD", officialName: "Le Méridien Nagpur" },
  { id: "ISKFH", officialName: "The Fern Heaven on The Hills Hatgad-Saputara, Series by Marriott" },
  { id: "ISKCN", officialName: "Courtyard by Marriott Nashik" },
  { id: "ISKFP", officialName: "Four Points by Sheraton Nashik" },
  { id: "BOMRT", officialName: "The Fern Residency Navi Mumbai, Turbhe, Series by Marriott" },
  { id: "BOMNV", officialName: "Courtyard by Marriott Navi Mumbai" },
  { id: "BOMMN", officialName: "Navi Mumbai Marriott Hotel" },
  { id: "BOMNM", officialName: "Le Méridien Navi Mumbai" },
  { id: "CJBMD", officialName: "Le Méridien Coimbatore" },
  { id: "DELAL", officialName: "Aloft by Marriott New Delhi Aerocity" },
  { id: "DELAP", officialName: "JW Marriott Hotel New Delhi Aerocity" },
  { id: "DELFN", officialName: "Four Points by Sheraton New Delhi, Airport Highway" },
  { id: "DELSN", officialName: "Sheraton New Delhi Hotel" },
  { id: "DELLC", officialName: "ITC Maurya, a Luxury Collection Hotel, New Delhi" },
  { id: "DELMD", officialName: "Le Méridien New Delhi" },
  { id: "BOMFV", officialName: "The Fern Shelter Resort Palghar, Series by Marriott" },
  { id: "PNQFH", officialName: "The Fern Habitat Pune, Mundhwa, Series by Marriott" },
  { id: "PNQRZ", officialName: "The Ritz-Carlton, Pune" },
  { id: "PNQFE", officialName: "E-Square The Fern Pune, Series by Marriott" },
  { id: "PNQHI", officialName: "Hotel Irada, Pune Wine Country, a Member of Design Hotels" },
  { id: "PNQMC", officialName: "JW Marriott Hotel Pune" },
  { id: "PNQWI", officialName: "The Westin Pune Koregaon Park" },
  { id: "PNQFA", officialName: "Amanora The Fern Pune, Series by Marriott" },
  { id: "PNQMD", officialName: "Sheraton Grand Pune Bund Garden Hotel" },
  { id: "PNQRW", officialName: "The Fern Residency Pune, Woodland, Series by Marriott" },
  { id: "PNQCK", officialName: "Courtyard by Marriott Pune Chakan" },
  { id: "PNQMS", officialName: "Marriott Suites Pune" },
  { id: "PNQPH", officialName: "Courtyard by Marriott Pune Hinjewadi" },
  { id: "PNQFI", officialName: "Fairfield by Marriott Pune Kharadi" },
  { id: "PNQFP", officialName: "Four Points by Sheraton Hotel & Serviced Apartments, Pune" },
  { id: "JAIPU", officialName: "The Westin Pushkar Resort & Spa" },
  { id: "RPRCY", officialName: "Courtyard by Marriott Raipur" },
  { id: "HSRRR", officialName: "The Fern Residency Rajkot, Series by Marriott" },
  { id: "DELMO", officialName: "Jim Corbett Marriott Resort & Spa" },
  { id: "PGHRJ", officialName: "Debu's The Fern Resort & Spa Jim Corbett, Series by Marriott" },
  { id: "IXRCY", officialName: "Courtyard by Marriott Ranchi" },
  { id: "IXEFT", officialName: "Tapovana The Fern Sakleshpur, Series by Marriott" },
  { id: "JAIRJ", officialName: "JW Marriott Ranthambore Resort & Spa" },
  { id: "SHLCY", officialName: "Courtyard by Marriott Shillong" },
  { id: "IXBCY", officialName: "Courtyard by Marriott Siliguri" },
  { id: "DELSW", officialName: "The Westin Sohna Resort & Spa" },
  { id: "SSERS", officialName: "The Fern Residency Solapur, Series by Marriott" },
  { id: "SXRFP", officialName: "Four Points by Sheraton Srinagar" },
  { id: "MAAFI", officialName: "Fairfield by Marriott Sriperumbudur" },
  { id: "STVCY", officialName: "Courtyard by Marriott Surat" },
  { id: "STVMD", officialName: "Le Meridien, Surat" },
  { id: "STVMC", officialName: "Surat Marriott Hotel" },
  { id: "PNQRV", officialName: "The Fern Residency Pune, Vadgaon-Talegaon, Series by Marriott" },
  { id: "DEDWI", officialName: "The Westin Resort & Spa, Himalayas" },
  { id: "TRZCY", officialName: "Courtyard by Marriott Tiruchirappalli" },
  { id: "TIRCY", officialName: "Courtyard By Marriott Tirupati" },
  { id: "UDRRB", officialName: "The Fern Bambora Fort Udaipur, Series by Marriott" },
  { id: "UDRRU", officialName: "The Fern Residency Udaipur, Series by Marriott" },
  { id: "UDRMC", officialName: "Udaipur Marriott Hotel" },
  { id: "BDQFA", officialName: "The Fern Residency Vadodara, Alkapuri, Series by Marriott" },
  { id: "BDQRV", officialName: "The Fern Residency Vadodara, Series by Marriott" },
  { id: "BDQCC", officialName: "Courtyard by Marriott Vadodara" },
  { id: "BDQVF", officialName: "Four Points by Sheraton Vadodara" },
  { id: "BDQFI", officialName: "Fairfield by Marriott Vadodara" },
  { id: "BDQFV", officialName: "The Fern Vadodara, Series by Marriott" },
  { id: "VTZFP", officialName: "Four Points by Sheraton Visakhapatnam" },
  { id: "VTZFI", officialName: "Fairfield by Marriott Visakhapatnam" },
];

export const indiaMarriottProperties: MarriottProperty[] =
  indiaOfficialRows.map(({ id, officialName }) => ({
    id: `in-${id.toLowerCase()}`,
    country: "IN",
    region: "overseas",
    officialName,
    brand: inferBrand(officialName),
    brandGroup: high.brandGroup,
    confidence: high.confidence,
    status: high.status,
    aliases: [],
    reason: `${officialName}은 Marriott Bonvoy 계열 호텔로 확인된 인도 호텔입니다.`,
  }));
