import { high, inferBrand, propertyId } from "./helpers";
import type { MarriottProperty } from "./types";

const indiaOfficialNames = [
  "ITC Mughal, a Luxury Collection Resort & Spa, Agra",
  "Courtyard by Marriott Agra",
  "Fairfield by Marriott Agra",
  "ITC Narmada, a Luxury Collection Hotel, Ahmedabad",
  "Four Points by Sheraton Ahmedabad",
  "Le Meridien Ahmedabad",
  "The Fern Residency Ahmedabad, Subhash Bridge, Series by Marriott",
  "The Fern Residency Ahmedabad, Ellisbridge, Series by Marriott",
  "Fairfield by Marriott Ahmedabad",
  "Renaissance Ahmedabad Hotel",
  "Le Méridien Amritsar",
  "Courtyard by Marriott Amritsar",
  "Four Points by Sheraton Amritsar, Mall Road",
  "Fairfield by Marriott Amritsar",
  "Marriott Executive Apartments Mall Road Amritsar",
  "The Fern Royal Farm Resort Anjar, Series by Marriott",
  "Crescent The Fern Budhni, Series by Marriott",
  "The Fern Habitat Goa, Candolim, Series by Marriott",
  "Fairfield by Marriott Belagavi",
  "Sheraton Grand Bangalore Hotel at Brigade Gateway",
  "The Fern Residency Bengaluru, Yeshwanthpur, Series by Marriott",
  "The Fern Residency Bengaluru, Seshadripuram, Series by Marriott",
  "JW Marriott Bengaluru Prestige Golfshire Resort & Spa",
  "Courtyard by Marriott Bengaluru Hebbal",
  "Fairfield by Marriott Bengaluru Outer Ring Road",
  "Four Points by Sheraton Bengaluru, Whitefield",
  "ITC Gardenia, a Luxury Collection Hotel, Bengaluru",
  "ITC Windsor, a Luxury Collection Hotel, Bengaluru",
  "Sheraton Grand Bengaluru Whitefield Hotel & Convention Center",
  "Bengaluru Marriott Hotel Whitefield",
  "Marriott Executive Apartments Bengaluru UB City",
  "JW Marriott Hotel Bengaluru",
  "Fairfield by Marriott Bengaluru Whitefield",
  "Fairfield by Marriott Bengaluru Rajajinagar",
  "Trinity Whitefield Bengaluru",
  "Mulberry Shades Bengaluru Nandi Hills, a Tribute Portfolio Resort",
  "Moxy Bengaluru Airport Prestige Tech Cloud",
  "Aloft by Marriott Bengaluru Outer Ring Road",
  "Courtyard by Marriott Bengaluru Outer Ring Road",
  "Renaissance Bengaluru Race Course Hotel",
  "The Ritz-Carlton, Bangalore",
  "The Fern Residency Bhiwandi-Pimplas, Series by Marriott",
  "The Fern Residency Bhopal, Series by Marriott",
  "Courtyard by Marriott Bhopal",
  "The Fern Ranthambhore Forest Resort Sawai Madhopur, Series by Marriott",
  "Courtyard by Marriott Bilaspur",
  "Fairfield by Marriott Goa Calangute",
  "JW Marriott Hotel Chandigarh",
  "The Westin Chennai Velachery",
  "Fairfield by Marriott Chennai OMR",
  "Four Points by Sheraton Mahabalipuram Resort & Convention Center",
  "Four Points by Sheraton Chennai, Velachery",
  "Le Royal Méridien Chennai",
  "Sheraton Grand Chennai Resort & Spa",
  "ITC Grand Chola, a Luxury Collection Hotel, Chennai",
  "Fairfield by Marriott Chennai Mahindra World City",
  "Four Points by Sheraton Chennai OMR",
  "Courtyard by Marriott Chennai",
  "UG The Fern Resort & Spa Chikmagalur, Series by Marriott",
  "Fairfield by Marriott Coimbatore",
  "Kesarval The Fern Goa, Verna, Series by Marriott",
  "The Fern Seaside Luxurious Tent Resort Daman, Series by Marriott",
  "The Fern Samali Resort Dapoli, Series by Marriott",
  "Fairfield by Marriott Dehradun",
  "Le Méridien Dehradun Resort & Spa",
  "The Fern Surya Resort Dharampur, Kasauli Hills, Series by Marriott",
  "The Fern Sardar Sarovar Resort Ekta Nagar, Series by Marriott",
  "Aravali Marriott Resort & Spa, Delhi NCR",
  "Four Points by Sheraton Sonmarg Resort",
  "The Fern Residency Gandhinagar, Series by Marriott",
  "Blue Ocean The Fern Resort & Spa Ganpatipule, Series by Marriott",
  "The Fern Residency Bodhgaya, Series by Marriott",
  "Courtyard by Marriott Ghaziabad India",
  "Courtyard by Marriott Goa Colva",
  "Le Méridien Goa, Calangute",
  "JW Marriott Goa",
  "W Goa",
  "Fairfield by Marriott Goa Benaulim",
  "The Fern Kadamba Hotel & Spa Goa, Panjim, Series by Marriott",
  "Goa Marriott Resort & Spa",
  "Renaissance Goa Hotel",
  "The St. Regis Goa Resort",
  "The Westin Goa",
  "ITC Grand Goa, a Luxury Collection Resort & Spa, Goa",
  "Fairfield by Marriott Goa Anjuna",
  "The Fern Residency Godhra, Series by Marriott",
  "Courtyard by Marriott Gorakhpur",
  "ITC Grand Bharat, a Luxury Collection Retreat, Gurgaon, New Delhi Capital Region",
  "Le Méridien Gurgaon, Delhi NCR",
  "The Westin Gurgaon, New Delhi",
  "Courtyard by Marriott Gurugram Downtown",
  "The Fern Residency Hubballi, Series by Marriott",
  "Courtyard by Marriott Hyderabad",
  "ITC Kakatiya, a Luxury Collection Hotel, Hyderabad",
  "Sheraton Hyderabad Hotel",
  "Marriott Executive Apartments Hyderabad",
  "Hyderabad Marriott Hotel & Convention Centre",
  "Le Meridien Hyderabad",
  "Fairfield by Marriott Hyderabad Gachibowli",
  "ITC Kohenur, a Luxury Collection Hotel, Hyderabad",
  "The Westin Hyderabad Mindspace",
  "The Westin Hyderabad Hitec City",
  "Rakabi The Fern Igatpuri, Series By Marriott",
  "Sheraton Grand Palace Indore",
  "Indore Marriott Hotel",
  "Fairfield by Marriott Indore",
  "The Fern Nest Resort Jaipur, Series by Marriott",
  "The Westin Jaipur Kant Kalwar Resort and Spa",
  "Le Méridien Jaipur Resort & Spa",
  "ITC Rajputana, a Luxury Collection Hotel, Jaipur",
  "Four Points by Sheraton Jaipur, City Square",
  "Fairfield by Marriott Jaipur",
  "Jaipur Marriott Hotel",
  "Fairfield by Marriott Jaipur Tonk Road",
  "The Fern Jaipur, Series by Marriott",
  "Jaisalmer Marriott Resort & Spa",
  "Bhanu The Fern Forest Resort & Spa Jambughoda, Series by Marriott",
  "The Fern Residency Jamnagar, Series by Marriott",
  "Fairfield by Marriott Jodhpur",
  "The Fern Residency Jodhpur, Series by Marriott",
  "The Fern Vishranta Resort Kamrej-Surat, Series by Marriott",
  "Noormahal, Delhi NCR Karnal, Autograph Collection",
  "Katra Marriott Resort & Spa",
  "The Fern Riverview Resort Chiplun, Series by Marriott",
  "Le Méridien Kochi",
  "The Artiste Kochi, a Tribute Portfolio Hotel",
  "The Fern Kochi, Series by Marriott",
  "Courtyard by Marriott Kochi Infopark",
  "Kochi Marriott Hotel",
  "Port Muziris, a Tribute Portfolio Hotel, Kochi",
  "Courtyard by Marriott Kochi Airport",
  "The Fern Kolhapur, Series by Marriott",
  "The Westin Kolkata Rajarhat",
  "ITC Sonar, a Luxury Collection Hotel, Kolkata",
  "ITC Royal Bengal, a Luxury Collection Hotel, Kolkata",
  "JW Marriott Hotel Kolkata",
  "Fairfield by Marriott Kolkata",
  "Renaissance Lucknow Hotel",
  "Fairfield by Marriott Lucknow",
  "Coorg Marriott Resort & Spa",
  "Courtyard by Marriott Madurai",
  "Courtyard by Marriott Mahabaleshwar",
  "Le Méridien Mahabaleshwar Resort & Spa",
  "JW Marriott Mumbai Juhu",
  "ITC Maratha, a Luxury Collection Hotel, Mumbai",
  "The Fern Residency Mumbai, The Acres Chembur, Series by Marriott",
  "The Fern Fayms Resort Naigaon, Series by Marriott",
  "JW Marriott Mumbai Sahar",
  "ITC Grand Central, a Luxury Collection Hotel, Mumbai",
  "The Fern Residency Mumbai, Mira Road, Series by Marriott",
  "Lakeside Chalet, Mumbai - Marriott Executive Apartments",
  "Fairfield by Marriott Mumbai Andheri West",
  "The Fern Mumbai, Goregaon, Series by Marriott",
  "Meluha The Fern Mumbai, Powai, Series by Marriott",
  "Fairfield by Marriott Mumbai International Airport",
  "The Westin Mumbai Garden City",
  "The St. Regis Mumbai",
  "Courtyard by Marriott Mumbai International Airport",
  "Four Points by Sheraton Navi Mumbai, Vashi",
  "The Fern Residency Mumbai, Pritam Dadar, Series by Marriott",
  "Moxy Mumbai Andheri West",
  "The Westin Mumbai Powai Lake",
  "JW Marriott Mussoorie Walnut Grove Resort & Spa",
  "The Fern Brentwood Resort Mussoorie, Series by Marriott",
  "Le Méridien Nagpur",
  "The Fern Heaven on The Hills Hatgad-Saputara, Series by Marriott",
  "Courtyard by Marriott Nashik",
  "Four Points by Sheraton Nashik",
  "The Fern Residency Navi Mumbai, Turbhe, Series by Marriott",
  "Courtyard by Marriott Navi Mumbai",
  "Navi Mumbai Marriott Hotel",
  "Le Méridien Navi Mumbai",
  "Le Méridien Coimbatore",
  "Aloft by Marriott New Delhi Aerocity",
  "JW Marriott Hotel New Delhi Aerocity",
  "Four Points by Sheraton New Delhi, Airport Highway",
  "Sheraton New Delhi Hotel",
  "ITC Maurya, a Luxury Collection Hotel, New Delhi",
  "Le Méridien New Delhi",
  "The Fern Shelter Resort Palghar, Series by Marriott",
  "The Fern Habitat Pune, Mundhwa, Series by Marriott",
  "The Ritz-Carlton, Pune",
  "E-Square The Fern Pune, Series by Marriott",
  "Hotel Irada, Pune Wine Country, a Member of Design Hotels",
  "JW Marriott Hotel Pune",
  "The Westin Pune Koregaon Park",
  "Amanora The Fern Pune, Series by Marriott",
  "Sheraton Grand Pune Bund Garden Hotel",
  "The Fern Residency Pune, Woodland, Series by Marriott",
  "Courtyard by Marriott Pune Chakan",
  "Marriott Suites Pune",
  "Courtyard by Marriott Pune Hinjewadi",
  "Fairfield by Marriott Pune Kharadi",
  "Four Points by Sheraton Hotel & Serviced Apartments, Pune",
  "The Westin Pushkar Resort & Spa",
  "Courtyard by Marriott Raipur",
  "The Fern Residency Rajkot, Series by Marriott",
  "Jim Corbett Marriott Resort & Spa",
  "Debu's The Fern Resort & Spa Jim Corbett, Series by Marriott",
  "Courtyard by Marriott Ranchi",
  "Tapovana The Fern Sakleshpur, Series by Marriott",
  "JW Marriott Ranthambore Resort & Spa",
  "Courtyard by Marriott Shillong",
  "Courtyard by Marriott Siliguri",
  "The Westin Sohna Resort & Spa",
  "The Fern Residency Solapur, Series by Marriott",
  "Four Points by Sheraton Srinagar",
  "Fairfield by Marriott Sriperumbudur",
  "Courtyard by Marriott Surat",
  "Le Meridien, Surat",
  "Surat Marriott Hotel",
  "The Fern Residency Pune, Vadgaon-Talegaon, Series by Marriott",
  "The Westin Resort & Spa, Himalayas",
  "Courtyard by Marriott Tiruchirappalli",
  "Courtyard By Marriott Tirupati",
  "The Fern Bambora Fort Udaipur, Series by Marriott",
  "The Fern Residency Udaipur, Series by Marriott",
  "Udaipur Marriott Hotel",
  "The Fern Residency Vadodara, Alkapuri, Series by Marriott",
  "The Fern Residency Vadodara, Series by Marriott",
  "Courtyard by Marriott Vadodara",
  "Four Points by Sheraton Vadodara",
  "Fairfield by Marriott Vadodara",
  "The Fern Vadodara, Series by Marriott",
  "Four Points by Sheraton Visakhapatnam",
  "Fairfield by Marriott Visakhapatnam",
];

export const indiaMarriottProperties: MarriottProperty[] =
  indiaOfficialNames.map((officialName) => ({
    id: propertyId("IN", officialName),
    country: "IN",
    region: "overseas",
    officialName,
    brand: inferBrand(officialName),
    brandGroup: high.brandGroup,
    confidence: high.confidence,
    status: high.status,
    aliases: [],
    reason: `${officialName}은 Marriott Bonvoy 계열 호텔로 확인된 인도 호텔입니다.`,
  }));
