import { contains, high, inferBrand, propertyId } from "./helpers";
import type { MarriottProperty, MarriottPropertyAlias } from "./types";

// Source: Marriott Bonvoy Italy hotel sitemap (marriott.com/en-us/hotel-sitemap/italy-hotel-sitemap), July 2026.
const italyOfficialNames = [
  "The Lake Como EDITION",
  "The Rome EDITION",
  "The Excelsior, a Luxury Collection Hotel, Florence",
  "Excelsior Hotel Gallia, a Luxury Collection Hotel, Milan",
  "Casa Brera, a Luxury Collection Hotel, Milan",
  "Pazziella, a Luxury Collection Hotel, Capri",
  "Hotel Cala di Volpe, a Luxury Collection Hotel, Costa Smeralda",
  "The Gritti Palace, a Luxury Collection Hotel, Venice",
  "Hotel Danieli, a Luxury Collection Hotel, Venice",
  "JW Marriott Venice Resort & Spa",
  "The St. Regis Florence",
  "The St. Regis Rome",
  "The St. Regis Venice",
  "W Florence",
  "W Sardinia - Poltu Quatu",
  "W Rome",
  "Ortea Palace Hotel, Sicily, Autograph Collection",
  "Mangia's Brucoli, Sicily, Autograph Collection",
  "Grotta Giusti Thermal Spa Resort Tuscany, Autograph Collection",
  "Sina Villa Medici, Autograph Collection",
  "Grand Universe Lucca, Autograph Collection",
  "Principessa Forte dei Marmi, Autograph Collection",
  "The Pantheon Iconic Rome Hotel, Autograph Collection",
  "Argentario Golf & Wellness Resort, Autograph Collection",
  "Cardo Roma, Autograph Collection",
  "Sina Bernini Bristol, Autograph Collection",
  "Delta Hotels Giardini Naxos",
  "Plaza Caserta",
  "Delta Hotels Olbia Sardinia",
  "Elizabeth Country House, a Member of Design Hotels™",
  "Parkhotel Mondschein, a Member of Design Hotels™",
  "Arua Private Spa Villas, a Member of Design Hotels™",
  "Vigilius Mountain Resort, a Member of Design Hotels™",
  "Palazzo Daniele, a Member Design Hotels",
  "Hotel Greif, a Member of Design Hotels",
  "Hotel Schwarzschmied, a Member of Design Hotels™",
  "Schgaguler Hotel, a Member of Design Hotels",
  "1477 Reichhalter, a Member of Design Hotels",
  "Villa Arnica, a Member of Design Hotels",
  "Sextantio Le Grotte della Civita, a Member of Design Hotels™",
  "Chapter Chianti, a Member of Design Hotels",
  "Hotel Windsor, a Member of Design Hotels™",
  "STRAF, Milan, a Member of Design Hotels™",
  "C-Hotel & Spa, Cassago Brianza, a Member of Design Hotels™",
  "Hotel Viu Milan, a Member of Design Hotels™",
  "Gombit Hotel Bergamo",
  "La Bandita Townhouse, Pienza, a Member of Design Hotels™",
  "Rastrello, a Member of Design Hotels™",
  "Eremito, a Member of Design Hotels™",
  "Sextantio Albergo Diffuso, a Member of Design Hotels™",
  "G-Rough, Rome, a Member of Design Hotels™",
  "Elizabeth Unique Hotel, a Member of Design Hotels™",
  "Palazzo Velabro, a Member of Design Hotels™",
  "Elizabeth Unique Venice, a Member of Design Hotels™",
  "Le Méridien Visconti Rome",
  "Milan Marriott Hotel",
  "Rome Marriott Park Hotel",
  "Rome Marriott Grand Hotel Flora",
  "Renaissance Tuscany Il Ciocco Resort & Spa",
  "Renaissance Naples Hotel Mediterraneo",
  "Sheraton Milan Malpensa Airport Hotel & Conference Centre",
  "Sheraton Milan San Siro",
  "Sheraton Lake Como Hotel",
  "Cervo Hotel, Costa Smeralda Resort",
  "Sheraton Rome Parco de' Medici",
  "Cala Ponte, a Tribute Portfolio Hotel",
  "Villa Ermellina Siena, a Tribute Portfolio Hotel",
  "Duo Milan Porta Nuova, a Tribute Portfolio Hotel",
  "NEMI, Milan, a Tribute Portfolio Hotel",
  "HABITA79, Pompeii, a Tribute Portfolio Hotel",
  "The Regency, Rome, a Tribute Portfolio Hotel",
  "Hotel Urbana, a Tribute Portfolio Hotel",
  "The Westin Palace, Milan",
  "The Westin Excelsior, Rome",
  "AC Hotel Bologna",
  "AC Hotel Firenze",
  "AC Hotel Genova",
  "AC Hotel Milano",
  "AC Hotel Milan Sesto",
  "AC Hotel Pisa",
  "AC Hotel Padova",
  "AC Hotel Clodio Roma",
  "AC Hotel Torino",
  "AC Hotel Brescia",
  "AC Hotel Vicenza",
  "AC Hotel Venezia",
  "Courtyard by Marriott Milano Linate",
  "Courtyard by Marriott Rome Central Park",
  "Courtyard by Marriott Venice Airport",
  "Four Points by Sheraton Bolzano",
  "Four Points by Sheraton Catania Hotel & Conference Center",
  "Four Points by Sheraton Siena",
  "Four Points by Sheraton Padova",
  "Four Points by Sheraton Venice Mestre",
  "Four Points Flex by Sheraton Parma",
  "Four Points Flex by Sheraton Bologna Airport",
  "Four Points Flex by Sheraton Naples Marigliano",
  "Moxy Milan Linate Airport",
  "Moxy Milan Malpensa Airport",
  "Moxy Pompeii",
  "Moxy Venice Airport",
  "Moxy Verona",
  "Le Geant, Courmayeur, Apartments by Marriott Bonvoy",
  "Residence Inn by Marriott Milano Linate",
  "Residence Inn Naples Airport",
];

const italyAliasOverrides: Record<string, MarriottPropertyAlias[]> = {
  "Ortea Palace Hotel, Sicily, Autograph Collection": [
    contains("ORTEA LUXURY PALACE"),
    contains("ORTEA PALACE"),
  ],
};

export const italyMarriottProperties: MarriottProperty[] =
  italyOfficialNames.map((officialName) => ({
    id: propertyId("IT", officialName),
    country: "IT",
    region: "overseas",
    officialName,
    brand: inferBrand(officialName),
    brandGroup: high.brandGroup,
    confidence: high.confidence,
    status: high.status,
    aliases: italyAliasOverrides[officialName] ?? [],
    reason: `${officialName}은 Marriott Bonvoy 계열 호텔로 확인된 이탈리아 호텔입니다.`,
  }));
