import { applyCuratedMarriottPropertyAliases } from "../marriottPropertyOverrides";
import { high, inferBrand } from "./helpers";
import type { MarriottPropertySeed } from "./types";

// Source: Marriott destination page property codes, July 2026.
const japanOfficialRows = [
  { id: "KMJFI", officialName: "Fairfield by Marriott Kumamoto Aso" },
  { id: "UKBFI", officialName: "Fairfield by Marriott Hyogo Awaji Higashiura" },
  { id: "CTSFE", officialName: "Fairfield by Marriott Hokkaido Eniwa" },
  { id: "KMQCY", officialName: "Courtyard by Marriott Fukui" },
  { id: "FUKHS", officialName: "Four Points Flex by Sheraton Fukuoka Hakata" },
  { id: "FUKRZ", officialName: "The Ritz-Carlton, Fukuoka" },
  { id: "NGOFN", officialName: "Fairfield by Marriott Gifu Mino" },
  { id: "NGOFG", officialName: "Fairfield by Marriott Gifu Seiryu Satoyama Park" },
  { id: "NGOFJ", officialName: "Fairfield by Marriott Gifu Gujo" },
  { id: "MMJFI", officialName: "Fairfield by Marriott Gifu Takayama Shirakawa Go" },
  { id: "HKDXF", officialName: "Four Points Flex by Sheraton Hakodate Station" },
  { id: "TYOMH", officialName: "HOTEL THE MITSUI HAKONE, a Luxury Collection Hotel & Spa" },
  { id: "FSZHM", officialName: "Hamamatsu Marriott Hotel" },
  { id: "HIJSI", officialName: "Sheraton Grand Hiroshima Hotel" },
  { id: "IKIKM", officialName: "Iki Retreat by Onko Chishin, a Member of Design Hotels™" },
  { id: "KOJSI", officialName: "Sheraton Kagoshima" },
  { id: "KMQKU", officialName: "Four Points Flex by Sheraton Kanazawa" },
  { id: "MMJKH", officialName: "Karuizawa Marriott Hotel" },
  { id: "UKBXF", officialName: "Four Points Flex by Sheraton Kobe Sannomiya" },
  { id: "UKBMC", officialName: "Kobe Marriott Hotel" },
  { id: "OSAKB", officialName: "Kobe Bay Sheraton Hotel & Towers" },
  { id: "OKASI", officialName: "Sheraton Okinawa Sunmarina Resort" },
  { id: "OKJYD", officialName: "Yoruya, a Member of Design Hotels™" },
  { id: "CTSKO", officialName: "Kimamaya by Odin, a Member of Design Hotels" },
  { id: "OSAGK", officialName: "Genji Kyoto, a Member of Design Hotels™" },
  { id: "UKYOX", officialName: "Moxy Kyoto" },
  { id: "UKYLC", officialName: "Suiran, a Luxury Collection Hotel, Kyoto" },
  { id: "UKYRZ", officialName: "The Ritz-Carlton, Kyoto" },
  { id: "OSALC", officialName: "HOTEL THE MITSUI KYOTO, a Luxury Collection Hotel & Spa" },
  { id: "UKYFM", officialName: "Fairfield by Marriott Kyoto Amanohashidate" },
  { id: "UKYWI", officialName: "The Westin Miyako Kyoto" },
  { id: "OSAKS", officialName: "Courtyard by Marriott Kyoto Shijo Karasuma" },
  { id: "OSAKT", officialName: "The Chapter Kyoto, a Tribute Portfolio Hotel" },
  { id: "OSAYU", officialName: "Four Points Flex by Sheraton Kyoto Oike" },
  { id: "UKYFI", officialName: "Fairfield by Marriott Kyoto Minamiyamashiro" },
  { id: "UKYFK", officialName: "Fairfield by Marriott Kyoto Kyotamba" },
  { id: "UKYAK", officialName: "The Prince Kyoto Takaragaike, Autograph Collection" },
  { id: "OKJFI", officialName: "Fairfield by Marriott Okayama Hiruzen Highland" },
  { id: "MMJJJ", officialName: "Matsumoto Jujo, a Member of Design Hotels™" },
  { id: "NGOFI", officialName: "Fairfield by Marriott Mie Okuise Odai" },
  { id: "NGOFM", officialName: "Fairfield by Marriott Mie Kumano Kodo Mihama" },
  { id: "OSAFI", officialName: "Fairfield by Marriott Hyogo Awaji Fukura" },
  { id: "OKALC", officialName: "IRAPH SUI, a Luxury Collection Hotel, Miyako Okinawa" },
  { id: "HNAMU", officialName: "Four Points Flex by Sheraton Morioka" },
  { id: "MMJCH", officialName: "Courtyard by Marriott Hakuba" },
  { id: "NGSMC", officialName: "Nagasaki Marriott Hotel" },
  { id: "UBJSN", officialName: "SOIL Nagatoyumoto, a Member of Design Hotels" },
  { id: "OKACR", officialName: "Courtyard by Marriott Okinawa Resort" },
  { id: "OKARZ", officialName: "The Ritz-Carlton, Okinawa" },
  { id: "NGODT", officialName: "Nagoya Marriott Associa Hotel" },
  { id: "NGOAK", officialName: "TIAD, Autograph Collection" },
  { id: "NGOXF", officialName: "Four Points Flex by Sheraton Nagoya Station" },
  { id: "NGOCY", officialName: "Courtyard by Marriott Nagoya" },
  { id: "OSANL", officialName: "Shisui, a Luxury Collection Hotel, Nara" },
  { id: "OSAJW", officialName: "JW Marriott Hotel Nara" },
  { id: "TYONZ", officialName: "The Ritz-Carlton, Nikko" },
  { id: "CTSRZ", officialName: "Higashiyama Niseko Village, a Ritz-Carlton Reserve" },
  { id: "CTSOX", officialName: "Moxy Niseko Village" },
  { id: "OKARN", officialName: "Renaissance Okinawa Resort" },
  { id: "OSAUU", officialName: "Four Points Flex by Sheraton Osaka Umeda" },
  { id: "OSAOX", officialName: "Moxy Osaka Honmachi" },
  { id: "OSAFN", officialName: "Fairfield by Marriott Osaka Namba" },
  { id: "OSAOO", officialName: "Moxy Osaka Umeda" },
  { id: "OSAXR", officialName: "The St. Regis Osaka" },
  { id: "OSAOW", officialName: "W Osaka" },
  { id: "OSAAK", officialName: "THE OSAKA STATION HOTEL, Autograph Collection" },
  { id: "OSARZ", officialName: "The Ritz-Carlton, Osaka" },
  { id: "OSAYS", officialName: "Sheraton Miyako Hotel Osaka" },
  { id: "OSASS", officialName: "Sugata Hotel Osaka Shinsaibashi, Series by Marriott" },
  { id: "OSAHU", officialName: "Four Points Flex by Sheraton Osaka Shinsaibashi" },
  { id: "OSASU", officialName: "Four Points Flex by Sheraton Shin Osaka" },
  { id: "OSAKU", officialName: "Four Points Flex by Sheraton Osaka Kitahama" },
  { id: "OSAWI", officialName: "The Westin Osaka" },
  { id: "OSACO", officialName: "Courtyard by Marriott Osaka Honmachi" },
  { id: "OSAMC", officialName: "Osaka Marriott Miyako Hotel" },
  { id: "OSACY", officialName: "Courtyard by Marriott Shin-Osaka Station" },
  { id: "OSAAL", officialName: "Aloft by Marriott Osaka Dojima" },
  { id: "OSAXN", officialName: "City Express By Marriott Osaka Namba South" },
  { id: "OSAXI", officialName: "City Express By Marriott Osaka Shin-Imamiya" },
  { id: "OSAKO", officialName: "Hotel Koo Otsu Hyakucho, a Member of Design Hotels™" },
  { id: "CTSWI", officialName: "The Westin Rusutsu Resort" },
  { id: "CTSFI", officialName: "Fairfield by Marriott Sapporo" },
  { id: "CTSCY", officialName: "Courtyard by Marriott Sapporo" },
  { id: "SDJWI", officialName: "The Westin Sendai" },
  { id: "HIJFI", officialName: "Fairfield by Marriott Hiroshima Sera" },
  { id: "OSALB", officialName: "Lake Biwa Marriott Hotel" },
  { id: "FSZIZ", officialName: "Izu Marriott Hotel Shuzenji" },
  { id: "CTSFM", officialName: "Fairfield by Marriott Hokkaido Minamifurano" },
  { id: "KOJFI", officialName: "Fairfield by Marriott Kagoshima Sakurajima" },
  { id: "OSAFT", officialName: "Fairfield by Marriott Nara Tenri Yamanobenomichi" },
  { id: "IBRFT", officialName: "Fairfield by Marriott Tochigi Utsunomiya" },
  { id: "IBRFN", officialName: "Fairfield by Marriott Tochigi Nikko" },
  { id: "IBRFI", officialName: "Fairfield by Marriott Tochigi Motegi" },
  { id: "NGOFP", officialName: "Four Points by Sheraton Nagoya, Chubu International Airport" },
  { id: "TYOMC", officialName: "Tokyo Marriott Hotel" },
  { id: "TYOSW", officialName: "Four Points Flex by Sheraton Tokyo Shibuya West" },
  { id: "TYOWI", officialName: "The Westin Tokyo" },
  { id: "TYOLC", officialName: "The Prince Gallery Tokyo Kioicho, a Luxury Collection Hotel" },
  { id: "TYOAL", officialName: "Aloft by Marriott Tokyo Ginza" },
  { id: "TYOGZ", officialName: "Courtyard by Marriott Tokyo Station" },
  { id: "TYOCY", officialName: "Courtyard by Marriott Tokyo Ginza Hotel" },
  { id: "TYOBT", officialName: "Bvlgari Hotel Tokyo" },
  { id: "TYOUU", officialName: "Four Points Flex by Sheraton Tokyo Ueno" },
  { id: "TYORZ", officialName: "The Ritz-Carlton, Tokyo" },
  { id: "TYOMY", officialName: "Sheraton Miyako Hotel Tokyo" },
  { id: "TYOAK", officialName: "The Prince Sakura Tower Tokyo, Autograph Collection" },
  { id: "TYOEB", officialName: "The Tokyo EDITION, Ginza" },
  { id: "TYOAM", officialName: "Mesm Tokyo, Autograph Collection" },
  { id: "TYOET", officialName: "The Tokyo EDITION, Toranomon" },
  { id: "TYOAR", officialName: "AC Hotel Tokyo Ginza" },
  { id: "TYOHU", officialName: "Four Points Flex by Sheraton Tokyo Higashi Kanda" },
  { id: "TYOJW", officialName: "JW Marriott Hotel Tokyo" },
  { id: "TYOOX", officialName: "Moxy Tokyo Kinshicho" },
  { id: "OSAFB", officialName: "Fairfield by Marriott Hyogo Kannabe Highland" },
  { id: "OKJFT", officialName: "Fairfield by Marriott Okayama Tsuyama" },
  { id: "FUKFI", officialName: "Fairfield by Marriott Fukuoka Ukiha" },
  { id: "TYOSI", officialName: "Sheraton Grande Tokyo Bay Hotel" },
  { id: "NGSSU", officialName: "Fairfield by Marriott Saga Ureshino Onsen" },
  { id: "IBRUU", officialName: "Four Points Flex by Sheraton Utsunomiya" },
  { id: "OSAFW", officialName: "Fairfield by Marriott Wakayama Kumano Kodo Susami" },
  { id: "OSAFK", officialName: "Fairfield by Marriott Wakayama Kushimoto" },
  { id: "OSANA", officialName: "Nanki-Shirahama Marriott Hotel" },
  { id: "OSAFY", officialName: "Fairfield by Marriott Hyogo Tajima Yabu" },
  { id: "MMJFJ", officialName: "Fuji Marriott Hotel Lake Yamanaka" },
  { id: "TYOYU", officialName: "Four Points Flex by Sheraton Yokohama West" },
  { id: "TYOWY", officialName: "The Westin Yokohama" },
  { id: "TYOYS", officialName: "Yokohama Bay Sheraton Hotel & Towers" },
  { id: "CTSFN", officialName: "Fairfield by Marriott Hokkaido Naganuma" },
  { id: "OSAKC", officialName: "Courtyard Kyoto Station" },
  { id: "TYOYY", officialName: "Courtyard Shin Yokohama Station" },
];

export const japanMarriottProperties: MarriottPropertySeed[] =
  japanOfficialRows.map(({ id, officialName }) =>
    applyCuratedMarriottPropertyAliases({
      id: `jp-${id.toLowerCase()}`,
      country: "JP",
      region: "overseas",
      officialName,
      brand: inferBrand(officialName),
      brandGroup: high.brandGroup,
      confidence: high.confidence,
      status: high.status,
      aliases: [],
      reason: `${officialName}은 Marriott Bonvoy 계열 호텔로 확인된 일본 호텔입니다.`,
    })
  );
