import { high, inferBrand, propertyId } from "./helpers";
import type { MarriottProperty } from "./types";

const japanOfficialNames = [
  "Fairfield by Marriott Kumamoto Aso",
  "Fairfield by Marriott Hyogo Awaji Higashiura",
  "Fairfield by Marriott Hokkaido Eniwa",
  "Courtyard by Marriott Fukui",
  "Four Points Flex by Sheraton Fukuoka Hakata",
  "The Ritz-Carlton, Fukuoka",
  "Fairfield by Marriott Gifu Mino",
  "Fairfield by Marriott Gifu Seiryu Satoyama Park",
  "Fairfield by Marriott Gifu Gujo",
  "Fairfield by Marriott Gifu Takayama Shirakawa Go",
  "Four Points Flex by Sheraton Hakodate Station",
  "HOTEL THE MITSUI HAKONE, a Luxury Collection Hotel & Spa",
  "Hamamatsu Marriott Hotel",
  "Sheraton Grand Hiroshima Hotel",
  "Iki Retreat by Onko Chishin, a Member of Design Hotels™",
  "Sheraton Kagoshima",
  "Four Points Flex by Sheraton Kanazawa",
  "Karuizawa Marriott Hotel",
  "Four Points Flex by Sheraton Kobe Sannomiya",
  "Kobe Marriott Hotel",
  "Kobe Bay Sheraton Hotel & Towers",
  "Sheraton Okinawa Sunmarina Resort",
  "Yoruya, a Member of Design Hotels™",
  "Kimamaya by Odin, a Member of Design Hotels",
  "Genji Kyoto, a Member of Design Hotels™",
  "Moxy Kyoto",
  "Suiran, a Luxury Collection Hotel, Kyoto",
  "The Ritz-Carlton, Kyoto",
  "HOTEL THE MITSUI KYOTO, a Luxury Collection Hotel & Spa",
  "Fairfield by Marriott Kyoto Amanohashidate",
  "The Westin Miyako Kyoto",
  "Courtyard by Marriott Kyoto Shijo Karasuma",
  "The Chapter Kyoto, a Tribute Portfolio Hotel",
  "Four Points Flex by Sheraton Kyoto Oike",
  "Fairfield by Marriott Kyoto Minamiyamashiro",
  "Fairfield by Marriott Kyoto Kyotamba",
  "The Prince Kyoto Takaragaike, Autograph Collection",
  "Fairfield by Marriott Okayama Hiruzen Highland",
  "Matsumoto Jujo, a Member of Design Hotels™",
  "Fairfield by Marriott Mie Okuise Odai",
  "Fairfield by Marriott Mie Kumano Kodo Mihama",
  "Fairfield by Marriott Hyogo Awaji Fukura",
  "IRAPH SUI, a Luxury Collection Hotel, Miyako Okinawa",
  "Four Points Flex by Sheraton Morioka",
  "Courtyard by Marriott Hakuba",
  "Nagasaki Marriott Hotel",
  "SOIL Nagatoyumoto, a Member of Design Hotels",
  "Courtyard by Marriott Okinawa Resort",
  "The Ritz-Carlton, Okinawa",
  "Nagoya Marriott Associa Hotel",
  "TIAD, Autograph Collection",
  "Four Points Flex by Sheraton Nagoya Station",
  "Courtyard by Marriott Nagoya",
  "Shisui, a Luxury Collection Hotel, Nara",
  "JW Marriott Hotel Nara",
  "The Ritz-Carlton, Nikko",
  "Higashiyama Niseko Village, a Ritz-Carlton Reserve",
  "Moxy Niseko Village",
  "Renaissance Okinawa Resort",
  "Four Points Flex by Sheraton Osaka Umeda",
  "Moxy Osaka Honmachi",
  "Fairfield by Marriott Osaka Namba",
  "Moxy Osaka Umeda",
  "The St. Regis Osaka",
  "W Osaka",
  "THE OSAKA STATION HOTEL, Autograph Collection",
  "The Ritz-Carlton, Osaka",
  "Sheraton Miyako Hotel Osaka",
  "Sugata Hotel Osaka Shinsaibashi, Series by Marriott",
  "Four Points Flex by Sheraton Osaka Shinsaibashi",
  "Four Points Flex by Sheraton Shin Osaka",
  "Four Points Flex by Sheraton Osaka Kitahama",
  "The Westin Osaka",
  "Courtyard by Marriott Osaka Honmachi",
  "Osaka Marriott Miyako Hotel",
  "Courtyard by Marriott Shin-Osaka Station",
  "Aloft by Marriott Osaka Dojima",
  "City Express By Marriott Osaka Namba South",
  "City Express By Marriott Osaka Shin-Imamiya",
  "Hotel Koo Otsu Hyakucho, a Member of Design Hotels™",
  "The Westin Rusutsu Resort",
  "Fairfield by Marriott Sapporo",
  "Courtyard by Marriott Sapporo",
  "The Westin Sendai",
  "Fairfield by Marriott Hiroshima Sera",
  "Lake Biwa Marriott Hotel",
  "Izu Marriott Hotel Shuzenji",
  "Fairfield by Marriott Hokkaido Minamifurano",
  "Fairfield by Marriott Kagoshima Sakurajima",
  "Fairfield by Marriott Nara Tenri Yamanobenomichi",
  "Fairfield by Marriott Tochigi Utsunomiya",
  "Fairfield by Marriott Tochigi Nikko",
  "Fairfield by Marriott Tochigi Motegi",
  "Four Points by Sheraton Nagoya, Chubu International Airport",
  "Tokyo Marriott Hotel",
  "Four Points Flex by Sheraton Tokyo Shibuya West",
  "The Westin Tokyo",
  "The Prince Gallery Tokyo Kioicho, a Luxury Collection Hotel",
  "Aloft by Marriott Tokyo Ginza",
  "Courtyard by Marriott Tokyo Station",
  "Courtyard by Marriott Tokyo Ginza Hotel",
  "Bvlgari Hotel Tokyo",
  "Four Points Flex by Sheraton Tokyo Ueno",
  "The Ritz-Carlton, Tokyo",
  "Sheraton Miyako Hotel Tokyo",
  "The Prince Sakura Tower Tokyo, Autograph Collection",
  "The Tokyo EDITION, Ginza",
  "Mesm Tokyo, Autograph Collection",
  "The Tokyo EDITION, Toranomon",
  "AC Hotel Tokyo Ginza",
  "Four Points Flex by Sheraton Tokyo Higashi Kanda",
  "JW Marriott Hotel Tokyo",
  "Moxy Tokyo Kinshicho",
  "Fairfield by Marriott Hyogo Kannabe Highland",
  "Fairfield by Marriott Okayama Tsuyama",
  "Fairfield by Marriott Fukuoka Ukiha",
  "Sheraton Grande Tokyo Bay Hotel",
  "Fairfield by Marriott Saga Ureshino Onsen",
  "Four Points Flex by Sheraton Utsunomiya",
  "Fairfield by Marriott Wakayama Kumano Kodo Susami",
  "Fairfield by Marriott Wakayama Kushimoto",
  "Nanki-Shirahama Marriott Hotel",
  "Fairfield by Marriott Hyogo Tajima Yabu",
  "Fuji Marriott Hotel Lake Yamanaka",
  "Four Points Flex by Sheraton Yokohama West",
  "The Westin Yokohama",
  "Yokohama Bay Sheraton Hotel & Towers",
  "Fairfield by Marriott Hokkaido Naganuma",
];

export const japanMarriottProperties: MarriottProperty[] =
  japanOfficialNames.map((officialName) => ({
    id: propertyId("JP", officialName),
    country: "JP",
    region: "overseas",
    officialName,
    brand: inferBrand(officialName),
    brandGroup: high.brandGroup,
    confidence: high.confidence,
    status: high.status,
    aliases: [],
    reason: `${officialName}은 Marriott Bonvoy 계열 호텔로 확인된 일본 호텔입니다.`,
  }));
