import { high, inferBrand } from "./helpers";
import type { MarriottProperty } from "./types";

// Source: Marriott hotel sitemap property codes, July 2026.
const mexicoMarriottOfficialRows = [
  { id: "CUNEK", officialName: "The Riviera Maya EDITION at Kanai" },
  { id: "CUNPB", officialName: "Paraiso de la Bonita, a Luxury Collection Resort, Riviera Maya, Adult All-Inclusive" },
  { id: "CUNIM", officialName: "Almare, a Luxury Collection Resort, Isla Mujeres Cancun, Adult All-Inclusive" },
  { id: "MEXLC", officialName: "Las Alcobas, a Luxury Collection Hotel, Mexico City" },
  { id: "SJDLC", officialName: "Solaz, a Luxury Collection Resort, Los Cabos" },
  { id: "SJDLS", officialName: "The Residences at Solaz, a Luxury Collection Resort, Los Cabos" },
  { id: "CUNJW", officialName: "JW Marriott Cancun Resort & Spa" },
  { id: "GDLJW", officialName: "JW Marriott Hotel Guadalajara" },
  { id: "MTYJW", officialName: "JW Marriott Hotel Monterrey Valle" },
  { id: "MEXJW", officialName: "JW Marriott Hotel Mexico City Polanco" },
  { id: "MEXSF", officialName: "JW Marriott Hotel Mexico City Santa Fe" },
  { id: "SJDJW", officialName: "JW Marriott Los Cabos Beach Resort & Spa" },
  { id: "SJDJC", officialName: "Casa Maat at JW Marriott Los Cabos Beach Resort & Spa" },
  { id: "CUNXR", officialName: "The St. Regis Kanai Resort, Riviera Maya" },
  { id: "CUNCM", officialName: "The St. Regis Costa Mujeres Resort, Cancun" },
  { id: "MEXXR", officialName: "The St. Regis Mexico City" },
  { id: "PVRXR", officialName: "The St. Regis Punta Mita Resort" },
  { id: "MEXWM", officialName: "W Mexico City" },
  { id: "PVRWH", officialName: "W Punta de Mita" },
  { id: "BJXAK", officialName: "Cleviá, San Miguel de Allende, Autograph Collection" },
  { id: "CUNHV", officialName: "Royalton Hideaway Riviera Cancun, An Autograph Collection All-Inclusive Resort - Adults Only" },
  { id: "CUNRC", officialName: "Royalton CHIC Cancun, An Autograph Collection All-Inclusive Resort - Adults Only" },
  { id: "CUNRV", officialName: "Royalton Riviera Cancun, An Autograph Collection All-Inclusive Resort & Casino" },
  { id: "CUNSR", officialName: "Royalton Splash Riviera Cancun, An Autograph Collection All-Inclusive Resort" },
  { id: "CUUAK", officialName: "VETTA Distrito Uno, Autograph Collection" },
  { id: "CUNPA", officialName: "Planet Hollywood Cancun Adult Scene by Royalton, Autograph Collection All-Inclusive Resort - Adults" },
  { id: "CUNPC", officialName: "Planet Hollywood Cancun by Royalton, An Autograph Collection All-Inclusive Resort" },
  { id: "MEXBA", officialName: "Boca Alameda, Mexico City, Autograph Collection" },
  { id: "SLWAK", officialName: "CASA MAYOR Saltillo, Hotel Hacienda" },
  { id: "SJDHA", officialName: "Hacienda del Mar Los Cabos, An Autograph Collection All-Inclusive Resort" },
  { id: "CUUDC", officialName: "Delta Hotels by Marriott Chihuahua" },
  { id: "MTYJD", officialName: "SJ Grand Hotel Monterrey" },
  { id: "PVRDE", officialName: "Delta Hotels Riviera Nayarit, An All-Inclusive Resort" },
  { id: "PBCDE", officialName: "Gran Hotel de Puebla by HNF" },
  { id: "VERDE", officialName: "Delta Hotels by Marriott Riviera Veracruz" },
  { id: "BJXDS", officialName: "Elena de Cobre, a Member of Design Hotels™" },
  { id: "BJXHM", officialName: "Hotel Matilda, a Member of Design Hotels™" },
  { id: "CZMDE", officialName: "Papaya Playa Project, Tulum, a Member of Design Hotels™" },
  { id: "CZMDS", officialName: "Hotel La Semilla, Playa del Carmen, a Member of Design Hotels™" },
  { id: "GDLDS", officialName: "Casa Habita, Guadalajara, a Member of Design Hotels™" },
  { id: "LAPBC", officialName: "Baja Club Hotel, La Paz, Baja California Sur, a Member of Design Hotels™" },
  { id: "MEXDS", officialName: "CONDESA df, Mexico City, a Member of Design Hotels™" },
  { id: "MEXHD", officialName: "Habita, Mexico City, a Member of Design Hotels™" },
  { id: "MIDDS", officialName: "Rosas & Xocolate, Mérida, a Member of Design Hotels™" },
  { id: "MTYDS", officialName: "Habita Monterrey, a Member of Design Hotels™" },
  { id: "MEXUL", officialName: "Circulo Mexicano, Mexico, a Member of Design Hotels™" },
  { id: "MEXDD", officialName: "Downtown Mexico, a Member of Design Hotels" },
  { id: "MIDHS", officialName: "Hotel Sevilla, a Member of Design Hotels™" },
  { id: "OAXOO", officialName: "Otro Oaxaca, a Member of Design Hotels™" },
  { id: "PAZDR", officialName: "Maison Couturier, San Rafael, a Member of Design Hotels™" },
  { id: "PAZDS", officialName: "Azucar, Monte Gordo, a Member of Design Hotels™" },
  { id: "PBCDS", officialName: "La Purificadora, Puebla, a Member of Design Hotels™" },
  { id: "PXMDS", officialName: "Hotel Escondido, Puerto Escondido, a Member of Design Hotels™" },
  { id: "PXMHE", officialName: "Hotel Escondido Oaxaca , Oaxaca, a Member of Design Hotels™" },
  { id: "PXMTR", officialName: "Terrestre, a Member of Design Hotels™" },
  { id: "PXMHH", officialName: "Hotel Humano, a Member of Design Hotels" },
  { id: "SJDDH", officialName: "Drift San Jose del Cabo, a Member of Design Hotels™" },
  { id: "SJDNB", officialName: "NEST Baja, a Member of Design Hotels" },
  { id: "TQOXT", officialName: "XELA Tulum, a Member of Design Hotels™" },
  { id: "TIJME", officialName: "MIRA Earth Studios Valle de Guadalupe, a Member of Design Hotels" },
  { id: "MEXDM", officialName: "Le Méridien Mexico City Reforma" },
  { id: "AGUMC", officialName: "Aguascalientes Marriott Hotel" },
  { id: "CUNMX", officialName: "Marriott Cancun, An All-Inclusive Resort" },
  { id: "CULMC", officialName: "Culiacan Marriott Hotel" },
  { id: "MEXMC", officialName: "Mexico City Marriott Reforma Hotel" },
  { id: "PBCMC", officialName: "Marriott Puebla Hotel Meson del Angel" },
  { id: "PVRMX", officialName: "Marriott Puerto Vallarta Resort & Spa" },
  { id: "TGZMC", officialName: "Marriott Tuxtla Gutierrez Hotel" },
  { id: "TIJMC", officialName: "Tijuana Marriott Hotel" },
  { id: "TRCMC", officialName: "Torreon Marriott Hotel" },
  { id: "VSAMC", officialName: "Villahermosa Marriott Hotel" },
  { id: "CUNWL", officialName: "The Westin Lagunamar Ocean Resort Villas & Spa, Cancun" },
  { id: "CUNWV", officialName: "The Westin Cancun Resort Villas & Spa" },
  { id: "CUNWO", officialName: "The Westin Resort & Spa, Cancun" },
  { id: "SJDWV", officialName: "The Westin Los Cabos Resort Villas" },
  { id: "SJDWB", officialName: "The Westin Los Cabos Resort Villas - Baja Point" },
  { id: "CUNBR", officialName: "Renaissance Cancun Resort & Marina" },
  { id: "BJXLS", officialName: "Sheraton León" },
  { id: "CUUSI", officialName: "Sheraton Chihuahua Soberano" },
  { id: "GDLSE", officialName: "Sheraton Guadalajara Expo" },
  { id: "MEXIS", officialName: "Sheraton Maria Isabel Mexico City Reforma" },
  { id: "PVRSI", officialName: "Sheraton Buganvilias Puerto Vallarta" },
  { id: "CUNMH", officialName: "Mystique Holbox by Royalton, A Tribute Portfolio Resort" },
  { id: "CUNAN", officialName: "Casa Nizuc, a Tribute Portfolio Resort" },
  { id: "CZMWI", officialName: "The Westin Cozumel" },
  { id: "CUNWA", officialName: "The Westin Cancun Resort & Spa" },
  { id: "GDLWI", officialName: "The Westin Guadalajara" },
  { id: "MEXWS", officialName: "The Westin Santa Fe, Mexico City" },
  { id: "MTYWI", officialName: "The Westin Monterrey Valle" },
  { id: "PVRWI", officialName: "The Westin Resort & Spa, Puerto Vallarta" },
  { id: "PVRWA", officialName: "The Westin Playa Vallarta, an All-Inclusive Resort" },
  { id: "GDLAC", officialName: "AC Hotel Guadalajara, Mexico" },
  { id: "GDLAR", officialName: "AC Hotel Guadalajara Expo, Mexico" },
  { id: "MEXAC", officialName: "AC Hotel Santa Fe" },
  { id: "MTYAC", officialName: "AC Hotel Monterrey Valle" },
  { id: "MTYAS", officialName: "AC Hotel Saltillo" },
  { id: "QROQA", officialName: "AC Hotel Queretaro Antea" },
  { id: "SLPAC", officialName: "AC Hotel By Marriott San Luis Potosi" },
  { id: "VERAC", officialName: "AC Hotel Veracruz" },
  { id: "CUNAL", officialName: "Aloft by Marriott Cancun" },
  { id: "CUNLA", officialName: "Aloft by Marriott Playa del Carmen" },
  { id: "GDLAG", officialName: "Aloft by Marriott Guadalajara Sur" },
  { id: "GDLCC", officialName: "Hotel Guadalajara Country Club by HNF" },
  { id: "QROAQ", officialName: "Aloft by Marriott Queretaro" },
  { id: "AGUJC", officialName: "City Express Junior by Marriott Aguascalientes Centro" },
  { id: "AGUXS", officialName: "City Express by Marriott Aguascalientes Sur" },
  { id: "BJXXL", officialName: "City Express by Marriott Leon" },
  { id: "BJXPL", officialName: "City Express Plus by Marriott Leon Centro de Convenciones" },
  { id: "BJXXI", officialName: "City Express by Marriott Irapuato" },
  { id: "BJXXO", officialName: "City Express by Marriott Silao Aeropuerto" },
  { id: "BJXXG", officialName: "City Express by Marriott Celaya Galerias" },
  { id: "BJXJL", officialName: "City Express Junior by Marriott León Centro De Convenciones" },
  { id: "BJXXM", officialName: "City Express by Marriott Lagos De Moreno" },
  { id: "BJXXN", officialName: "City Express by Marriott Irapuato Norte" },
  { id: "BJXXC", officialName: "City Express by Marriott Celaya Parque" },
  { id: "BJXXS", officialName: "City Express by Marriott Salamanca" },
  { id: "CUNJC", officialName: "City Express Junior by Marriott Cancun" },
  { id: "CJSJJ", officialName: "City Express Junior by Marriott Ciudad Juárez Consulado" },
  { id: "CVMXV", officialName: "City Express by Marriott Ciudad Victoria" },
  { id: "CMEJC", officialName: "City Express Junior by Marriott Ciudad Del Carmen" },
  { id: "CUNXC", officialName: "City Express by Marriott Cancun" },
  { id: "CENXO", officialName: "City Express by Marriott Ciudad Obregón" },
  { id: "CPEXP", officialName: "City Express by Marriott Campeche" },
  { id: "CMEJO", officialName: "City Express Junior by Marriott Ciudad Del Carmen Aeropuerto" },
  { id: "CMEXC", officialName: "City Express by Marriott Ciudad del Carmen" },
  { id: "CUUXC", officialName: "City Express by Marriott Chihuahua" },
  { id: "CUNPO", officialName: "City Express Plus by Marriott Cancún Aeropuerto Riviera" },
  { id: "CUNXP", officialName: "City Express by Marriott Playa Del Carmen" },
  { id: "CTMXC", officialName: "City Express by Marriott Chetumal" },
  { id: "CULXC", officialName: "City Express by Marriott Culiacán" },
  { id: "CJSXJ", officialName: "City Express by Marriott Ciudad Juárez" },
  { id: "CUNXA", officialName: "City Express by Marriott Cancun Aeropuerto" },
  { id: "DGOXD", officialName: "City Express by Marriott Durango" },
  { id: "GDLPR", officialName: "City Express Plus by Marriott Guadalajara Providencia" },
  { id: "GDLJP", officialName: "City Express Junior by Marriott Guadalajara Periférico Sur" },
  { id: "GDLPP", officialName: "City Express Plus by Marriott Guadalajara Palomar" },
  { id: "GDLPE", officialName: "City Express Plus by Marriott Guadalajara Expo" },
  { id: "GDLXO", officialName: "City Express by Marriott Guadalajara Aeropuerto" },
  { id: "HMOXH", officialName: "City Express by Marriott Hermosillo" },
  { id: "HMOXG", officialName: "City Express by Marriott Guaymas" },
  { id: "HMOXE", officialName: "City Express by Marriott Hermosillo Expo" },
  { id: "IZTXS", officialName: "City Express by Marriott Salina Cruz" },
  { id: "LMMXL", officialName: "City Express by Marriott Los Mochis" },
  { id: "LAPXL", officialName: "City Express by Marriott La Paz" },
  { id: "MIDXM", officialName: "City Express by Marriott Merida" },
  { id: "MEXPE", officialName: "City Express Plus by Marriott Ciudad de México Santa Fe" },
  { id: "MEXPG", officialName: "City Express Plus by Marriott Ciudad de México Reforma El Ángel" },
  { id: "MTYXL", officialName: "City Express by Marriott Saltillo Norte" },
  { id: "MEXPU", officialName: "City Express Plus by Marriott Ciudad de México Patio Universidad" },
  { id: "MEXXV", officialName: "City Express by Marriott Ciudad de México La Villa" },
  { id: "MEXPP", officialName: "City Express Plus by Marriott Ciudad de México Periférico Sur Tlalpan" },
  { id: "MEXPM", officialName: "City Express Plus by Marriott Ciudad de México Mundo E" },
  { id: "MAMXM", officialName: "City Express by Marriott Matamoros" },
  { id: "MTYPS", officialName: "City Express Plus by Marriott Monterrey Nuevo Sur" },
  { id: "MEXXD", officialName: "City Express by Marriott Ciudad De Mexico Alameda" },
  { id: "MTYPG", officialName: "City Express Plus by Marriott Monterrey Galerias" },
  { id: "MXLJM", officialName: "City Express Junior by Marriott Mexicali" },
  { id: "MIDPM", officialName: "City Express Plus by Marriott Mérida" },
  { id: "MTYXN", officialName: "City Express by Marriott Monterrey Norte" },
  { id: "MTYXU", officialName: "City Express by Marriott Monterrey Universidad" },
  { id: "MIDJA", officialName: "City Express Junior by Marriott Merida Altabrisa" },
  { id: "MZTPM", officialName: "City Express Plus by Marriott Mazatlán" },
  { id: "MEXXL", officialName: "City Express by Marriott Ciudad de México Tlalpan" },
  { id: "MZTXM", officialName: "City Express by Marriott Mazatlán" },
  { id: "MEXXB", officialName: "City Express by Marriott Ciudad de México Tlalnepantla" },
  { id: "MEXPI", officialName: "City Express Plus by Marriott Ciudad de México Insurgentes Sur" },
  { id: "MTYXO", officialName: "City Express by Marriott Monterrey Aeropuerto" },
  { id: "MEXJS", officialName: "City Express Junior by Marriott Ciudad de México Sullivan" },
  { id: "MXLXM", officialName: "City Express by Marriott Mexicali" },
  { id: "MEXPT", officialName: "City Express Plus by Marriott Ciudad de Mexico Interlomas" },
  { id: "MEXXP", officialName: "City Express by Marriott Tepotzotlan" },
  { id: "MEXXE", officialName: "City Express by Marriott Ciudad de México EBC Reforma" },
  { id: "MEXXU", officialName: "City Express by Marriott Tula" },
  { id: "MEXCM", officialName: "City Centro by Marriott Ciudad De México" },
  { id: "MEXSA", officialName: "City Express Suites by Marriott Ciudad de México Anzures" },
  { id: "MXLPM", officialName: "City Express Plus by Marriott Mexicali" },
  { id: "MTYXW", officialName: "City Express by Marriott Saltillo Sur" },
  { id: "MEXXA", officialName: "City Express by Marriott Ciudad De México La Raza" },
  { id: "MEXXO", officialName: "City Express by Marriott Ciudad de México Aeropuerto" },
  { id: "MTYXT", officialName: "City Express by Marriott Monterrey Lindavista" },
  { id: "MTYXC", officialName: "City Express by Marriott Monterrey Santa Catarina" },
  { id: "MTTXT", officialName: "City Express by Marriott Minatitlan" },
  { id: "MEXXZ", officialName: "City Express by Marriott Ciudad de México Plaza Central" },
  { id: "MTYPC", officialName: "City Express Plus by Marriott Monterrey Centro" },
  { id: "NOGXN", officialName: "City Express by Marriott Nogales" },
  { id: "NLDXN", officialName: "City Express by Marriott Nuevo Laredo" },
  { id: "NOGXC", officialName: "City Express by Marriott Cananea" },
  { id: "OAXCO", officialName: "City Centro by Marriott Oaxaca" },
  { id: "OAXXO", officialName: "City Express by Marriott Oaxaca" },
  { id: "PAZXT", officialName: "City Express by Marriott Tuxpan" },
  { id: "PBCXC", officialName: "City Express by Marriott Puebla Centro" },
  { id: "PBCXT", officialName: "City Express by Marriott Tehuacan" },
  { id: "PBCJF", officialName: "City Express Junior by Marriott Puebla Finsa" },
  { id: "PDSXP", officialName: "City Express by Marriott Piedras Negras" },
  { id: "PPEXC", officialName: "City Express by Marriott Caborca" },
  { id: "PBCXA", officialName: "City Express by Marriott Puebla Angelopolis" },
  { id: "PBCXP", officialName: "City Express by Marriott Puebla Finsa" },
  { id: "PBCJA", officialName: "City Express Junior by Marriott Puebla Angelopolis" },
  { id: "PBCXX", officialName: "City Express by Marriott Apizaco" },
  { id: "PVRPP", officialName: "City Express Plus by Marriott Puerto Vallarta" },
  { id: "PBCSF", officialName: "City Express Suites Puebla Finsa" },
  { id: "QROXJ", officialName: "City Express by Marriott Querétaro Juríca" },
  { id: "QROSQ", officialName: "City Express Suites by Marriott Querétaro" },
  { id: "QROXQ", officialName: "City Express by Marriott Queretaro" },
  { id: "REXXO", officialName: "City Express by Marriott Reynosa Aeropuerto" },
  { id: "REXXR", officialName: "City Express by Marriott Reynosa" },
  { id: "SLPJC", officialName: "City Express Junior by Marriott San Luis Potosi Carranza" },
  { id: "SLPPS", officialName: "City Express Plus by Marriott San Luis Potosí" },
  { id: "SLPJI", officialName: "City Express Junior by Marriott San Luis Potosí Zona Industrial" },
  { id: "SLPCL", officialName: "City Centro by Marriott San Luis Potosi" },
  { id: "SLPXI", officialName: "City Express by Marriott San Luis Potosí Zona Industrial" },
  { id: "SLPXU", officialName: "City Express by Marriott San Luis Potosi Zona Universitaria" },
  { id: "SJDPC", officialName: "City Express Plus by Marriott Cabo San Lucas" },
  { id: "TIJPT", officialName: "City Express Plus by Marriott Tijuana" },
  { id: "TAMPT", officialName: "City Express Plus by Marriott Tampico" },
  { id: "TIJXE", officialName: "City Express by Marriott Ensenada" },
  { id: "TGZJP", officialName: "City Express Junior by Marriott Tuxtla Gutiérrez Poliforum" },
  { id: "TAMXT", officialName: "City Express by Marriott Tampico" },
  { id: "TIJPE", officialName: "City Express Plus by Marriott Ensenada" },
  { id: "TPQXT", officialName: "City Express by Marriott Tepic" },
  { id: "TLCXT", officialName: "City Express by Marriott Toluca" },
  { id: "TIJXO", officialName: "City Express by Marriott Tijuana Otay" },
  { id: "TAMXA", officialName: "City Express by Marriott Tampico Altamira" },
  { id: "TIJXS", officialName: "City Express by Marriott Rosarito" },
  { id: "TGZXT", officialName: "City Express by Marriott Tuxtla Gutierrez" },
  { id: "TAPXT", officialName: "City Express by Marriott Tapachula" },
  { id: "TGZXC", officialName: "City Express by Marriott Comitan" },
  { id: "TIJXR", officialName: "City Express by Marriott Tijuana Río" },
  { id: "TIJSR", officialName: "City Express Suites by Marriott Tijuana Rio" },
  { id: "TIJXI", officialName: "City Express by Marriott Tijuana Insurgentes" },
  { id: "TIJJO", officialName: "City Express Junior by Marriott Tijuana Otay" },
  { id: "TLCJO", officialName: "City Express Junior by Marriott Toluca Aeropuerto" },
  { id: "TLCJI", officialName: "City Express Junior by Marriott Toluca Zona Industrial" },
  { id: "TRCXT", officialName: "City Express by Marriott Torreón" },
  { id: "TIJXF", officialName: "City Express by Marriott Tijuana El Florido" },
  { id: "VSAJV", officialName: "City Express Junior by Marriott Villahermosa" },
  { id: "VERJT", officialName: "City Express Junior by Marriott Tuxtepec" },
  { id: "VERJO", officialName: "City Express Junior by Marriott Veracruz Aeropuerto" },
  { id: "VERXX", officialName: "City Express by Marriott Xalapa" },
  { id: "VSAXV", officialName: "City Express by Marriott Villahermosa" },
  { id: "VERXV", officialName: "City Express by Marriott Veracruz" },
  { id: "VSAXP", officialName: "City Express by Marriott Paraiso" },
  { id: "ZLOXM", officialName: "City Express by Marriott Manzanillo" },
  { id: "ZIHXL", officialName: "City Express by Marriott Lazaro Cardenas" },
  { id: "ZCLXZ", officialName: "City Express by Marriott Zacatecas" },
  { id: "BJXCY", officialName: "Courtyard by Marriott Leon at The Poliforum" },
  { id: "CJSCY", officialName: "Courtyard by Marriott Ciudad Juarez" },
  { id: "CUNCY", officialName: "Courtyard by Marriott Cancun Airport" },
  { id: "CUUCY", officialName: "Courtyard by Marriott Chihuahua" },
  { id: "CMEYC", officialName: "Courtyard by Marriott Ciudad del Carmen Campeche" },
  { id: "CUNPY", officialName: "Courtyard By Marriott Playa del Carmen Quintana Roo" },
  { id: "GDLCA", officialName: "Courtyard by Marriott Guadalajara Andares" },
  { id: "HMOCY", officialName: "Courtyard by Marriott Hermosillo" },
  { id: "LAPCY", officialName: "Courtyard by Marriott La Paz Baja California Sur" },
  { id: "MEXCY", officialName: "Courtyard by Marriott Mexico City Airport" },
  { id: "MEXNA", officialName: "Courtyard by Marriott Mexico City Toreo" },
  { id: "MEXRV", officialName: "Courtyard by Marriott Mexico City Revolucion" },
  { id: "MEXVJ", officialName: "Courtyard by Marriott Mexico City Vallejo" },
  { id: "MIDCY", officialName: "Courtyard by Marriott Merida Downtown" },
  { id: "MTYCY", officialName: "Courtyard by Marriott Monterrey Airport" },
  { id: "MTYSJ", officialName: "Courtyard by Marriott Monterrey San Jeronimo/Valle" },
  { id: "MXLCY", officialName: "Courtyard by Marriott Mexicali" },
  { id: "MZTCY", officialName: "Courtyard by Marriott Mazatlan Beach Resort" },
  { id: "PBCCY", officialName: "Courtyard by Marriott Puebla Las Animas" },
  { id: "PAZCY", officialName: "Courtyard by Marriott Tuxpan Veracruz" },
  { id: "QROCY", officialName: "Courtyard by Marriott Queretaro" },
  { id: "SLPCS", officialName: "Courtyard by Marriott San Luis Potosi, Los Lagos" },
  { id: "SLPCY", officialName: "Courtyard by Marriott San Luis Potosi" },
  { id: "SLWCS", officialName: "Courtyard by Marriott Saltillo" },
  { id: "TLCCY", officialName: "Courtyard by Marriott Toluca Airport" },
  { id: "TLCTM", officialName: "Courtyard by Marriott Toluca Tollocan" },
  { id: "TRCCT", officialName: "Courtyard by Marriott Torreón" },
  { id: "VSACY", officialName: "Courtyard by Marriott Villahermosa Tabasco" },
  { id: "AGUFI", officialName: "Fairfield by Marriott Inn & Suites Aguascalientes" },
  { id: "BJXFI", officialName: "Fairfield by Marriott Inn & Suites Silao Guanajuato Airport" },
  { id: "CUNFD", officialName: "Fairfield by Marriott Inn & Suites Cancun Downtown" },
  { id: "CUNFI", officialName: "Fairfield by Marriott Inn & Suites Cancun Airport" },
  { id: "MEXFI", officialName: "Fairfield by Marriott Inn & Suites Mexico City Vallejo" },
  { id: "MXLFI", officialName: "Fairfield by Marriott Inn & Suites Mexicali" },
  { id: "NOGFI", officialName: "Fairfield by Marriott Inn & Suites Nogales" },
  { id: "QROPT", officialName: "Fairfield by Marriott Inn & Suites Queretaro Juriquilla" },
  { id: "SJDFI", officialName: "Fairfield by Marriott Los Cabos" },
  { id: "SLPFI", officialName: "Fairfield by Marriott Inn & Suites San Luis Potosi" },
  { id: "SLPLF", officialName: "Fairfield by Marriott San Luis Potosí Los Lagos" },
  { id: "TIJFI", officialName: "Fairfield by Marriott Inn & Suites Tijuana" },
  { id: "VSAFI", officialName: "Fairfield by Marriott Inn & Suites Villahermosa Tabasco" },
  { id: "CJSFP", officialName: "Four Points by Sheraton Ciudad Juarez" },
  { id: "CUNFP", officialName: "Four Points by Sheraton Cancun Centro" },
  { id: "CUUFP", officialName: "Four Points by Sheraton Distrito Uno Chihuahua" },
  { id: "MEXFP", officialName: "Four Points by Sheraton Mexico City, Colonia Roma" },
  { id: "MTYFA", officialName: "Four Points by Sheraton Monterrey Airport" },
  { id: "MTYFL", officialName: "Four Points by Sheraton Monterrey Linda Vista" },
  { id: "MTYFP", officialName: "Four Points by Sheraton Galerias Monterrey" },
  { id: "PBCFP", officialName: "Four Points by Sheraton Puebla" },
  { id: "QROQF", officialName: "Four Points by Sheraton Queretaro Norte" },
  { id: "SLWFP", officialName: "Four Points by Sheraton Saltillo" },
  { id: "VERFP", officialName: "Four Points by Sheraton Veracruz" },
  { id: "TQOOX", officialName: "Moxy Tulum" },
  { id: "TQOBA", officialName: "Bloom Tulum, Apartments by Marriott Bonvoy" },
  { id: "CUNRP", officialName: "Residence Inn by Marriott Playa del Carmen" },
  { id: "CUNRI", officialName: "Residence Inn by Marriott Cancun Hotel Zone" },
  { id: "GDLCR", officialName: "Residence Inn by Marriott Guadalajara Country Club" },
  { id: "MIDRI", officialName: "Residence Inn by Marriott Merida" },
] as const;

export const mexicoMarriottProperties: MarriottProperty[] = mexicoMarriottOfficialRows.map(
  ({ id, officialName }) => ({
    id,
    country: "MX",
    region: "overseas",
    officialName,
    brand: inferBrand(officialName),
    ...high,
    aliases: [],
  })
);
