import { applyCuratedMarriottPropertyAliases } from "../marriottPropertyOverrides";
import { high, inferBrand } from "./helpers";
import type { MarriottPropertySeed } from "./types";

// Source: Marriott destination page property codes, July 2026.
const malaysiaOfficialRows = [
  { id: "JHBFP", officialName: "Four Points by Sheraton Desaru" },
  { id: "JHBWI", officialName: "The Westin Desaru Coast Resort" },
  { id: "KULPC", officialName: "AC Hotel Puchong" },
  { id: "PENMH", officialName: "Iconic Marjorie Hotel, Penang, a Tribute Portfolio Hotel" },
  { id: "KBRPP", officialName: "Perhentian Marriott Resort & Spa" },
  { id: "BTUFI", officialName: "Fairfield by Marriott Bintulu Paragon" },
  { id: "PENGT", officialName: "Macalister Mansion, George Town, a Member of Design Hotels™" },
  { id: "PENMC", officialName: "Penang Marriott Hotel" },
  { id: "PENTM", officialName: "The Millen Penang, Autograph Collection" },
  { id: "PENCY", officialName: "Courtyard by Marriott Penang" },
  { id: "PENER", officialName: "Marriott Executive Apartments, Penang" },
  { id: "PENTP", officialName: "The Prestige Hotel, a Member of Design Hotels™" },
  { id: "IPHAC", officialName: "AC Hotel Ipoh" },
  { id: "JHBBR", officialName: "Renaissance Johor Bahru Hotel" },
  { id: "JHBSJ", officialName: "Sheraton Johor Bahru" },
  { id: "PENBT", officialName: "THE BERTAM PENANG, A TRIBUTE PORTFOLIO HOTEL" },
  { id: "BKILH", officialName: "The LUMA Hotel, Kota Kinabalu, a Member of Design Hotels™" },
  { id: "BKIKK", officialName: "Kota Kinabalu Marriott Hotel" },
  { id: "BKIMD", officialName: "Le Méridien Kota Kinabalu" },
  { id: "KBRBF", officialName: "Fairfield by Marriott Kuala Besut" },
  { id: "KULAK", officialName: "The Majestic Hotel Kuala Lumpur, Autograph Collection" },
  { id: "KULSP", officialName: "Hotel Stripes Kuala Lumpur, Autograph Collection" },
  { id: "KULWH", officialName: "W Kuala Lumpur" },
  { id: "KULCC", officialName: "Courtyard By Marriott Kuala Lumpur City Center" },
  { id: "KULRN", officialName: "Renaissance Kuala Lumpur Hotel & Convention Centre" },
  { id: "KULXR", officialName: "The St. Regis Kuala Lumpur" },
  { id: "KULEH", officialName: "Else Kuala Lumpur, a Member of Design Hotels" },
  { id: "KULCM", officialName: "citizenM Kuala Lumpur" },
  { id: "KULAL", officialName: "Aloft by Marriott Kuala Lumpur Sentral" },
  { id: "KULCS", officialName: "Courtyard by Marriott Kuala Lumpur South" },
  { id: "KULKA", officialName: "AC Hotel Kuala Lumpur" },
  { id: "KULFK", officialName: "Four Points by Sheraton Kuala Lumpur, City Centre" },
  { id: "KULMD", officialName: "Le Méridien Kuala Lumpur" },
  { id: "KULFC", officialName: "Four Points by Sheraton Kuala Lumpur, Chinatown" },
  { id: "KULOK", officialName: "Moxy Kuala Lumpur Chinatown" },
  { id: "KULFI", officialName: "Fairfield by Marriott Chow Kit Kuala Lumpur" },
  { id: "KULRZ", officialName: "The Ritz-Carlton, Kuala Lumpur" },
  { id: "KULEA", officialName: "Marriott Executive Apartments Kuala Lumpur" },
  { id: "KULDT", officialName: "JW Marriott Hotel Kuala Lumpur" },
  { id: "KULEL", officialName: "Element by Marriott Kuala Lumpur" },
  { id: "KULWI", officialName: "The Westin Kuala Lumpur" },
  { id: "KULSI", officialName: "Sheraton Imperial Kuala Lumpur Hotel" },
  { id: "KUAAR", officialName: "AC Hotel Kuantan" },
  { id: "KCHSI", officialName: "Sheraton Kuching Hotel" },
  { id: "LGKWI", officialName: "The Westin Langkawi Resort & Spa" },
  { id: "LGKRZ", officialName: "The Ritz-Carlton, Langkawi" },
  { id: "LGKAL", officialName: "Aloft by Marriott Langkawi Pantai Tengah" },
  { id: "LGKXR", officialName: "The St. Regis Langkawi" },
  { id: "JHBAP", officialName: "Four Points by Sheraton Johor Bahru" },
  { id: "MKZCY", officialName: "Courtyard by Marriott Melaka" },
  { id: "MYYMC", officialName: "Miri Marriott Resort & Spa" },
  { id: "MYYMU", officialName: "Mulu Marriott Resort & Spa" },
  { id: "PENLP", officialName: "Lone Pine, Penang, a Tribute Portfolio Resort" },
  { id: "PENAR", officialName: "AC Hotel Penang" },
  { id: "KULPJ", officialName: "Petaling Jaya Marriott Hotel" },
  { id: "KULJM", officialName: "Le Méridien Petaling Jaya" },
  { id: "SZBSI", officialName: "Sheraton Petaling Jaya Hotel" },
  { id: "KULFP", officialName: "Four Points by Sheraton Puchong" },
  { id: "KULDM", officialName: "Le Méridien Putrajaya" },
  { id: "KULPT", officialName: "Palm Garden Hotel, Putrajaya, a Tribute Portfolio Hotel" },
  { id: "KULOX", officialName: "Moxy Putrajaya" },
  { id: "BKISI", officialName: "Sheraton Kota Kinabalu" },
  { id: "KULPG", officialName: "Putrajaya Marriott Hotel" },
  { id: "KULSC", officialName: "Courtyard by Marriott Setia Alam" },
  { id: "KULSY", officialName: "Courtyard By Marriott Subang" },
  { id: "JHBJW", officialName: "JW Marriott Hotel Johor Bahru" },
];

export const malaysiaMarriottProperties: MarriottPropertySeed[] =
  malaysiaOfficialRows.map(({ id, officialName }) =>
    applyCuratedMarriottPropertyAliases({
      id: `my-${id.toLowerCase()}`,
      country: "MY",
      region: "overseas",
      officialName,
      brand: inferBrand(officialName),
      brandGroup: high.brandGroup,
      confidence: high.confidence,
      status: high.status,
      aliases: [],
      reason: `${officialName}은 Marriott Bonvoy 계열 호텔로 확인된 말레이시아 호텔입니다.`,
    })
  );
