import { high, inferBrand, propertyId } from "./helpers";
import type { MarriottProperty } from "./types";

const malaysiaOfficialNames = [
  "Four Points by Sheraton Desaru",
  "The Westin Desaru Coast Resort",
  "AC Hotel Puchong",
  "Iconic Marjorie Hotel, Penang, a Tribute Portfolio Hotel",
  "Perhentian Marriott Resort & Spa",
  "Fairfield by Marriott Bintulu Paragon",
  "Macalister Mansion, George Town, a Member of Design Hotels™",
  "Penang Marriott Hotel",
  "The Millen Penang, Autograph Collection",
  "Courtyard by Marriott Penang",
  "Marriott Executive Apartments, Penang",
  "The Prestige Hotel, a Member of Design Hotels™",
  "AC Hotel Ipoh",
  "Renaissance Johor Bahru Hotel",
  "Sheraton Johor Bahru",
  "THE BERTAM PENANG, A TRIBUTE PORTFOLIO HOTEL",
  "The LUMA Hotel, Kota Kinabalu, a Member of Design Hotels™",
  "Kota Kinabalu Marriott Hotel",
  "Le Méridien Kota Kinabalu",
  "Fairfield by Marriott Kuala Besut",
  "The Majestic Hotel Kuala Lumpur, Autograph Collection",
  "Hotel Stripes Kuala Lumpur, Autograph Collection",
  "W Kuala Lumpur",
  "Courtyard By Marriott Kuala Lumpur City Center",
  "Renaissance Kuala Lumpur Hotel & Convention Centre",
  "The St. Regis Kuala Lumpur",
  "Else Kuala Lumpur, a Member of Design Hotels",
  "citizenM Kuala Lumpur",
  "Aloft by Marriott Kuala Lumpur Sentral",
  "Courtyard by Marriott Kuala Lumpur South",
  "AC Hotel Kuala Lumpur",
  "Four Points by Sheraton Kuala Lumpur, City Centre",
  "Le Méridien Kuala Lumpur",
  "Four Points by Sheraton Kuala Lumpur, Chinatown",
  "Moxy Kuala Lumpur Chinatown",
  "Fairfield by Marriott Chow Kit Kuala Lumpur",
  "The Ritz-Carlton, Kuala Lumpur",
  "Marriott Executive Apartments Kuala Lumpur",
  "JW Marriott Hotel Kuala Lumpur",
  "Element by Marriott Kuala Lumpur",
  "The Westin Kuala Lumpur",
  "Sheraton Imperial Kuala Lumpur Hotel",
  "AC Hotel Kuantan",
  "Sheraton Kuching Hotel",
  "The Westin Langkawi Resort & Spa",
  "The Ritz-Carlton, Langkawi",
  "Aloft by Marriott Langkawi Pantai Tengah",
  "The St. Regis Langkawi",
  "Four Points by Sheraton Johor Bahru",
  "Courtyard by Marriott Melaka",
  "Miri Marriott Resort & Spa",
  "Mulu Marriott Resort & Spa",
  "Lone Pine, Penang, a Tribute Portfolio Resort",
  "AC Hotel Penang",
  "Petaling Jaya Marriott Hotel",
  "Le Méridien Petaling Jaya",
  "Sheraton Petaling Jaya Hotel",
  "Four Points by Sheraton Puchong",
  "Le Méridien Putrajaya",
  "Palm Garden Hotel, Putrajaya, a Tribute Portfolio Hotel",
  "Moxy Putrajaya",
  "Sheraton Kota Kinabalu",
  "Putrajaya Marriott Hotel",
  "Courtyard by Marriott Setia Alam",
  "Courtyard By Marriott Subang",
];

export const malaysiaMarriottProperties: MarriottProperty[] =
  malaysiaOfficialNames.map((officialName) => ({
    id: propertyId("MY", officialName),
    country: "MY",
    region: "overseas",
    officialName,
    brand: inferBrand(officialName),
    brandGroup: high.brandGroup,
    confidence: high.confidence,
    status: high.status,
    aliases: [],
    reason: `${officialName}은 Marriott Bonvoy 계열 호텔로 확인된 말레이시아 호텔입니다.`,
  }));
