import { high, inferBrand } from "./helpers";
import type { MarriottPropertySeed } from "./types";

// Source: Marriott hotel sitemap property codes, July 2026.
const saudiArabiaMarriottOfficialRows = [
  { id: "EJHEB", officialName: "The Red Sea EDITION" },
  { id: "JEDEB", officialName: "The Jeddah EDITION" },
  { id: "JEDLA", officialName: "Assila, a Luxury Collection Hotel, Jeddah" },
  { id: "RUHLC", officialName: "Bab Samhan, a Luxury Collection Hotel, Diriyah" },
  { id: "RUHJB", officialName: "JW Marriott Hotel Riyadh" },
  { id: "EJHXR", officialName: "The St. Regis Red Sea Resort" },
  { id: "RUHXR", officialName: "The St. Regis Riyadh" },
  { id: "RUHWH", officialName: "W Riyadh - KAFD" },
  { id: "DHAMD", officialName: "Le Méridien Al Khobar" },
  { id: "JEDMK", officialName: "Le Méridien Towers Makkah" },
  { id: "JEDMM", officialName: "Le Méridien Makkah" },
  { id: "MEDMD", officialName: "Le Méridien Medina" },
  { id: "RUHMD", officialName: "Le Méridien Riyadh" },
  { id: "TUUMD", officialName: "Le Méridien Tabuk" },
  { id: "JEDMR", officialName: "Jeddah Marriott Hotel Madinah Road" },
  { id: "MEDMC", officialName: "Madinah Marriott Hotel" },
  { id: "QCAMC", officialName: "Jabal Omar Marriott Hotel, Makkah" },
  { id: "RUHAP", officialName: "Riyadh Airport Marriott Hotel" },
  { id: "RUHDQ", officialName: "Marriott Riyadh Diplomatic Quarter" },
  { id: "RUHSA", officialName: "Riyadh Marriott Hotel" },
  { id: "DMMSI", officialName: "Sheraton Dammam Hotel & Convention Centre" },
  { id: "JEDSI", officialName: "Sheraton Jeddah Hotel" },
  { id: "JEDSM", officialName: "Sheraton Makkah Jabal Al Kaaba Hotel" },
  { id: "RUHSI", officialName: "Sheraton Riyadh Hotel & Towers" },
  { id: "DHADL", officialName: "Aloft by Marriott Dhahran" },
  { id: "RUHAL", officialName: "Aloft by Marriott Riyadh" },
  { id: "DMMJC", officialName: "Courtyard by Marriott Jubail" },
  { id: "GIZCY", officialName: "Courtyard by Marriott Jazan" },
  { id: "JEDKM", officialName: "Courtyard by Marriott Makkah" },
  { id: "RUHAB", officialName: "Courtyard by Marriott Riyadh Diplomatic Quarter" },
  { id: "RUHCY", officialName: "Courtyard by Marriott Riyadh Olaya" },
  { id: "RUHNR", officialName: "Courtyard by Marriott Riyadh Northern Ring Road" },
  { id: "AQIFP", officialName: "Four Points by Sheraton Hafar Al Batin" },
  { id: "JEDFP", officialName: "Four Points by Sheraton Makkah Al Naseem" },
  { id: "JEDFO", officialName: "Four Points by Sheraton Jeddah Corniche" },
  { id: "JEDSP", officialName: "Four Points by Sheraton Jeddah King Fahd Road" },
  { id: "RUHFP", officialName: "Four Points by Sheraton Riyadh Khaldia" },
  { id: "RUHFK", officialName: "Four Points by Sheraton King Abdulaziz Road" },
  { id: "JEDIK", officialName: "Lifestyle Living, Al Salam Jeddah, Apartments by Marriott Bonvoy" },
  { id: "ELQEL", officialName: "Element by Marriott Al Qassim" },
  { id: "DMMKA", officialName: "Marriott Executive Apartments Al Khobar" },
  { id: "MEDER", officialName: "Marriott Executive Apartments Madinah" },
  { id: "RUHED", officialName: "Riyadh Diplomatic Quarter - Marriott Executive Apartments" },
  { id: "RUHRY", officialName: "Marriott Executive Apartments Riyadh, Convention Center" },
  { id: "DMMRI", officialName: "Residence Inn by Marriott Dammam" },
  { id: "GIZRI", officialName: "Residence Inn by Marriott Jazan" },
  { id: "JEDAR", officialName: "Marriott Executive Apartments Jeddah Al Salam" },
  { id: "JEDDE", officialName: "Delta Hotels Jeddah Al Salam" },
  { id: "JEDMP", officialName: "Four Points Makkah Ibrahim Al Khalil" },
  { id: "RUHOW", officialName: "ROSH Olaya" },
  // Ritz-Carlton HWS XML property codes, July 2026.
  { id: "EJHRZ", officialName: "Nujuma, a Ritz-Carlton Reserve" },
  { id: "JEDRJ", officialName: "The Ritz-Carlton Jeddah" },
  { id: "RUHRZ", officialName: "The Ritz-Carlton, Riyadh" },
] as const;

export const saudiArabiaMarriottProperties: MarriottPropertySeed[] = saudiArabiaMarriottOfficialRows.map(
  ({ id, officialName }) => ({
    id,
    country: "SA",
    region: "overseas",
    officialName,
    brand: inferBrand(officialName),
    ...high,
    aliases: [],
  })
);
