import { high, inferBrand, propertyId } from "./helpers";
import type { MarriottProperty } from "./types";

const thailandOfficialNames = [
  "sala bang pa-in, a Member of Design Hotels™",
  "Sheraton Grande Sukhumvit, a Luxury Collection Hotel, Bangkok",
  "Marriott Executive Apartments, Bangkok Townhall Sukhumvit",
  "W Bangkok",
  "Montien Riverside Hotel Bangkok",
  "Bangkok Marriott Hotel Sukhumvit",
  "The St. Regis Bangkok",
  "Madi Paidi Bangkok, Autograph Collection",
  "Four Points by Sheraton Bangkok Ploenchit Sukhumvit",
  "Marriott Executive Apartments Bangkok, Sukhumvit Thonglor",
  "Aloft by Marriott Bangkok Sukhumvit 11",
  "Marriott Executive Apartments Bangkok, Sukhumvit 101",
  "Hotel Muse Bangkok, Autograph Collection",
  "Marriott Executive Apartments Bangkok, Sukhumvit 50",
  "The Ritz-Carlton, Bangkok",
  "Marriott Executive Apartments Sukhumvit Park, Bangkok",
  "Courtyard by Marriott Bangkok Sukhumvit 20",
  "Four Points by Sheraton Bangkok, Sukhumvit 22",
  "The Westin Grande Sukhumvit, Bangkok",
  "Public House Bangkok, a Member of Design Hotels",
  "Sathorn Vista, Bangkok - Marriott Executive Apartments",
  "The Athenee Hotel, a Luxury Collection Hotel, Bangkok",
  "Bangkok Marriott Hotel The Surawongse",
  "Bangkok Marriott Marquis Queen’s Park",
  "Courtyard by Marriott Bangkok",
  "Moxy Bangkok Ratchaprasong",
  "Renaissance Bangkok Ratchaprasong Hotel",
  "Le Méridien Bangkok",
  "Metropole, Bangkok, a Tribute Portfolio Hotel",
  "Courtyard by Marriott Bangkok Suvarnabhumi Airport",
  "Royal Orchid Sheraton Riverside Hotel Bangkok",
  "JW Marriott Hotel Bangkok",
  "Jubilee Prestige Hotel Ratchadapisek",
  "Chiang Mai Marriott Hotel",
  "Le Méridien Chiang Rai Resort, Thailand",
  "Hua Hin Marriott Resort & Spa",
  "Sheraton Hua Hin Resort & Spa",
  "Casa de La Flora, Khao Lak, Phang Nga, a Member of Design Hotels™",
  "Le Méridien Khao Lak Resort & Spa",
  "Sheraton Samui Resort",
  "W Koh Samui",
  "Renaissance Koh Samui Resort & Spa",
  "Vana Belle, a Luxury Collection Resort, Koh Samui",
  "The Ritz-Carlton, Koh Samui",
  "Phulay Bay, a Ritz-Carlton Reserve",
  "Veranda Resort Phuket, Autograph Collection",
  "Courtyard by Marriott Phuket, Patong Beach Resort",
  "Renaissance Pattaya Resort & Spa",
  "Courtyard by Marriott North Pattaya",
  "Pattaya Marriott Resort and Spa",
  "Marriott Vacation Club, Khao Lak Beach Resort",
  "Iniala Beach House, a Member of Design Hotels™",
  "JW Marriott Khao Lak Resort & Spa",
  "Courtyard by Marriott Phuket Town",
  "Renaissance Phuket Resort & Spa",
  "Phuket Marriott Resort and Spa, Nai Yang Beach",
  "Le Méridien Phuket Beach Resort",
  "JW Marriott Phuket Resort & Spa",
  "Four Points by Sheraton Phuket Patong Beach Resort",
  "The Naka Island, a Luxury Collection Resort & Spa, Phuket",
  "Courtyard by Marriott Phuket Chalong Bay Resort",
  "The Naka Phuket, a Member of Design Hotels",
  "Le Méridien Phuket Mai Khao Beach Resort",
  "The Westin Siray Bay Resort & Spa, Phuket",
  "Phuket Marriott Resort & Spa, Merlin Beach",
  "Marriott's Phuket Beach Club",
  "Marriott's Mai Khao Resort - Phuket",
  "Sheraton Hua Hin Pranburi Villas",
  "Rayong Marriott Resort & Spa",
  "Khao Lak Marriott Beach Resort & Spa",
];

export const thailandMarriottProperties: MarriottProperty[] =
  thailandOfficialNames.map((officialName) => ({
    id: propertyId("TH", officialName),
    country: "TH",
    region: "overseas",
    officialName,
    brand: inferBrand(officialName),
    brandGroup: high.brandGroup,
    confidence: high.confidence,
    status: high.status,
    aliases: [],
    reason: `${officialName}은 Marriott Bonvoy 계열 호텔로 확인된 태국 호텔입니다.`,
  }));
