import { high, inferBrand } from "./helpers";
import type { MarriottPropertySeed } from "./types";

// Source: Marriott destination page property codes, July 2026.
const thailandOfficialRows = [
  { id: "BKKAS", officialName: "sala bang pa-in, a Member of Design Hotels™" },
  { id: "BKKLC", officialName: "Sheraton Grande Sukhumvit, a Luxury Collection Hotel, Bangkok" },
  { id: "BKKTS", officialName: "Marriott Executive Apartments, Bangkok Townhall Sukhumvit" },
  { id: "BKKWB", officialName: "W Bangkok" },
  { id: "BKKMR", officialName: "Montien Riverside Hotel Bangkok" },
  { id: "BKKMS", officialName: "Bangkok Marriott Hotel Sukhumvit" },
  { id: "BKKXR", officialName: "The St. Regis Bangkok" },
  { id: "BKKBH", officialName: "Madi Paidi Bangkok, Autograph Collection" },
  { id: "BKKPU", officialName: "Four Points by Sheraton Bangkok Ploenchit Sukhumvit" },
  { id: "BKKBP", officialName: "Marriott Executive Apartments Bangkok, Sukhumvit Thonglor" },
  { id: "BKKAL", officialName: "Aloft by Marriott Bangkok Sukhumvit 11" },
  { id: "BKKEO", officialName: "Marriott Executive Apartments Bangkok, Sukhumvit 101" },
  { id: "BKKHM", officialName: "Hotel Muse Bangkok, Autograph Collection" },
  { id: "BKKEF", officialName: "Marriott Executive Apartments Bangkok, Sukhumvit 50" },
  { id: "BKKRB", officialName: "The Ritz-Carlton, Bangkok" },
  { id: "BKKSP", officialName: "Marriott Executive Apartments Sukhumvit Park, Bangkok" },
  { id: "BKKCT", officialName: "Courtyard by Marriott Bangkok Sukhumvit 20" },
  { id: "BKKFO", officialName: "Four Points by Sheraton Bangkok, Sukhumvit 22" },
  { id: "BKKWI", officialName: "The Westin Grande Sukhumvit, Bangkok" },
  { id: "BKKPH", officialName: "Public House Bangkok, a Member of Design Hotels" },
  { id: "BKKEA", officialName: "Sathorn Vista, Bangkok - Marriott Executive Apartments" },
  { id: "BKKLA", officialName: "The Athenee Hotel, a Luxury Collection Hotel, Bangkok" },
  { id: "BKKWO", officialName: "Bangkok Marriott Hotel The Surawongse" },
  { id: "BKKQP", officialName: "Bangkok Marriott Marquis Queen’s Park" },
  { id: "BKKCY", officialName: "Courtyard by Marriott Bangkok" },
  { id: "BKKOX", officialName: "Moxy Bangkok Ratchaprasong" },
  { id: "BKKBR", officialName: "Renaissance Bangkok Ratchaprasong Hotel" },
  { id: "BKKDM", officialName: "Le Méridien Bangkok" },
  { id: "BKKTM", officialName: "Metropole, Bangkok, a Tribute Portfolio Hotel" },
  { id: "BKKAP", officialName: "Courtyard by Marriott Bangkok Suvarnabhumi Airport" },
  { id: "BKKSI", officialName: "Royal Orchid Sheraton Riverside Hotel Bangkok" },
  { id: "BKKDT", officialName: "JW Marriott Hotel Bangkok" },
  { id: "BKKJR", officialName: "Jubilee Prestige Hotel Ratchadapisek" },
  { id: "CNXMC", officialName: "Chiang Mai Marriott Hotel" },
  { id: "CEIMD", officialName: "Le Méridien Chiang Rai Resort, Thailand" },
  { id: "HHQMR", officialName: "Hua Hin Marriott Resort & Spa" },
  { id: "HHQSI", officialName: "Sheraton Hua Hin Resort & Spa" },
  { id: "HKTDS", officialName: "Casa de La Flora, Khao Lak, Phang Nga, a Member of Design Hotels™" },
  { id: "HKTML", officialName: "Le Méridien Khao Lak Resort & Spa" },
  { id: "USMSS", officialName: "Sheraton Samui Resort" },
  { id: "USMWH", officialName: "W Koh Samui" },
  { id: "USMBR", officialName: "Renaissance Koh Samui Resort & Spa" },
  { id: "USMVL", officialName: "Vana Belle, a Luxury Collection Resort, Koh Samui" },
  { id: "USMRZ", officialName: "The Ritz-Carlton, Koh Samui" },
  { id: "KBVRZ", officialName: "Phulay Bay, a Ritz-Carlton Reserve" },
  { id: "HKTVK", officialName: "Veranda Resort Phuket, Autograph Collection" },
  { id: "HKTCP", officialName: "Courtyard by Marriott Phuket, Patong Beach Resort" },
  { id: "PYXBR", officialName: "Renaissance Pattaya Resort & Spa" },
  { id: "PYXNP", officialName: "Courtyard by Marriott North Pattaya" },
  { id: "UTPJB", officialName: "Pattaya Marriott Resort and Spa" },
  { id: "HKTKV", officialName: "Marriott Vacation Club, Khao Lak Beach Resort" },
  { id: "HKTIB", officialName: "Iniala Beach House, a Member of Design Hotels™" },
  { id: "HKTKL", officialName: "JW Marriott Khao Lak Resort & Spa" },
  { id: "HKTCT", officialName: "Courtyard by Marriott Phuket Town" },
  { id: "HKTBR", officialName: "Renaissance Phuket Resort & Spa" },
  { id: "HKTNB", officialName: "Phuket Marriott Resort and Spa, Nai Yang Beach" },
  { id: "HKTMD", officialName: "Le Méridien Phuket Beach Resort" },
  { id: "HKTJW", officialName: "JW Marriott Phuket Resort & Spa" },
  { id: "HKTFP", officialName: "Four Points by Sheraton Phuket Patong Beach Resort" },
  { id: "PYXLC", officialName: "The Naka Island, a Luxury Collection Resort & Spa, Phuket" },
  { id: "HKTPC", officialName: "Courtyard by Marriott Phuket Chalong Bay Resort" },
  { id: "HKTNP", officialName: "The Naka Phuket, a Member of Design Hotels" },
  { id: "HKTMM", officialName: "Le Méridien Phuket Mai Khao Beach Resort" },
  { id: "HKTWI", officialName: "The Westin Siray Bay Resort & Spa, Phuket" },
  { id: "HKTMB", officialName: "Phuket Marriott Resort & Spa, Merlin Beach" },
  { id: "HKTPB", officialName: "Marriott's Phuket Beach Club" },
  { id: "HKTPA", officialName: "Marriott's Mai Khao Resort - Phuket" },
  { id: "HHQPS", officialName: "Sheraton Hua Hin Pranburi Villas" },
  { id: "BKKRR", officialName: "Rayong Marriott Resort & Spa" },
  { id: "HKTMK", officialName: "Khao Lak Marriott Beach Resort & Spa" },
];

export const thailandMarriottProperties: MarriottPropertySeed[] =
  thailandOfficialRows.map(({ id, officialName }) => ({
    id: `th-${id.toLowerCase()}`,
    country: "TH",
    region: "overseas",
    officialName,
    brand: inferBrand(officialName),
    brandGroup: high.brandGroup,
    confidence: high.confidence,
    status: high.status,
    aliases: [],
    reason: `${officialName}은 Marriott Bonvoy 계열 호텔로 확인된 태국 호텔입니다.`,
  }));
