import { applyCuratedMarriottPropertyAliases } from "../marriottPropertyOverrides";
import { high, inferBrand } from "./helpers";
import type { MarriottPropertySeed } from "./types";

// Source: Marriott hotel sitemap property codes, July 2026.
const turkiyeMarriottOfficialRows = [
  { id: "BJVEB", officialName: "The Bodrum EDITION" },
  { id: "ADBLC", officialName: "Reges, a Luxury Collection Resort & Spa, Cesme" },
  { id: "BJVLC", officialName: "Caresse, a Luxury Collection Resort & Spa, Bodrum" },
  { id: "ESBLC", officialName: "Lugal, a Luxury Collection Hotel, Ankara" },
  { id: "ISTLC", officialName: "Sanasaryan Han, a Luxury Collection Hotel, Istanbul" },
  { id: "ESBJW", officialName: "JW Marriott Hotel Ankara" },
  { id: "ISTJB", officialName: "JW Marriott Istanbul Bosphorus" },
  { id: "ISTMS", officialName: "JW Marriott Hotel Istanbul Marmara Sea" },
  { id: "ISTXR", officialName: "The St. Regis Istanbul" },
  { id: "ISTAR", officialName: "Orientbank Hotel Istanbul, Autograph Collection" },
  { id: "ISTAD", officialName: "Adahan DeCamondo Pera, Autograph Collection" },
  { id: "ISTAO", officialName: "Burdock Hotel Istanbul, Autograph Collection" },
  { id: "ISTAG", officialName: "Orient Occident Hotel Istanbul, Autograph Collection" },
  { id: "NAVAK", officialName: "Fortuna of Cappadocia, Autograph Collection" },
  { id: "YEIUM", officialName: "Ceylan Splend'or Uludag, Autograph Collection" },
  { id: "AYTLD", officialName: "Delta Hotels Antalya Lara" },
  { id: "BJVDE", officialName: "Delta Hotels Bodrum" },
  { id: "ISTDK", officialName: "Delta Hotels Istanbul Kagithane" },
  { id: "ISTLD", officialName: "Delta Hotels Istanbul Levent" },
  { id: "ISTDW", officialName: "Delta Hotels Istanbul West" },
  { id: "ISTKD", officialName: "Delta Hotels Istanbul Karakoy" },
  { id: "ISTDS", officialName: "Gezi Hotel Bosphorus, Istanbul, a Member of Design Hotels™" },
  { id: "ISTVK", officialName: "The Bank Hotel Istanbul, a Member of Design Hotels™" },
  { id: "ISTCF", officialName: "Casa Foscolo Hotel, Istanbul, a Member of Design Hotels™" },
  { id: "BJVMD", officialName: "Le Méridien Bodrum Beach Resort" },
  { id: "ISTMD", officialName: "Le Méridien Istanbul Etiler" },
  { id: "ADBMC", officialName: "Izmir Marriott Hotel" },
  { id: "ISTMC", officialName: "Istanbul Marriott Hotel Asia" },
  { id: "ISTHP", officialName: "Istanbul Marriott Hotel Pendik" },
  { id: "ISTDT", officialName: "Istanbul Marriott Hotel Sisli" },
  { id: "NAVMC", officialName: "Cappadocia Marriott Hotel" },
  { id: "ADBBR", officialName: "Renaissance Izmir Hotel" },
  { id: "ISTRN", officialName: "Renaissance Polat Istanbul Hotel" },
  { id: "ISTBO", officialName: "Renaissance Istanbul Polat Bosphorus Hotel" },
  { id: "ADASI", officialName: "Sheraton Grand Adana" },
  { id: "ESBSI", officialName: "Sheraton Ankara Hotel & Convention Center" },
  { id: "ISTGS", officialName: "Sheraton Grand Istanbul Atasehir" },
  { id: "ISTAS", officialName: "Sheraton Istanbul Ataköy Hotel" },
  { id: "ISTSD", officialName: "Sheraton Istanbul City Center" },
  { id: "ISTSI", officialName: "Sheraton Istanbul Esenyurt" },
  { id: "ISTSL", officialName: "Sheraton Istanbul Levent" },
  { id: "KZRUS", officialName: "Sheraton Uşak Hotel & Thermal Spa" },
  { id: "SZFSI", officialName: "Sheraton Grand Samsun Hotel" },
  { id: "YEISI", officialName: "Sheraton Bursa Hotel" },
  { id: "ISTDC", officialName: "DeCamondo Galata, a Tribute Portfolio Hotel" },
  { id: "ISTTS", officialName: "Lokalist, Istanbul, a Tribute Portfolio Hotel" },
  { id: "ISTNW", officialName: "The Westin Istanbul Nisantasi" },
  { id: "ISTAC", officialName: "AC Hotel Istanbul Macka" },
  { id: "ISTKA", officialName: "Aloft by Marriott Istanbul Karakoy" },
  { id: "YEIAL", officialName: "Aloft by Marriott Bursa Hotel" },
  { id: "ADBFP", officialName: "Four Points by Sheraton Izmir" },
  { id: "EZSFP", officialName: "Four Points by Sheraton Elazig" },
  { id: "ISTFK", officialName: "Four Points by Sheraton Istanbul Kagithane" },
  { id: "ISTPF", officialName: "Four Points by Sheraton Istanbul Pendik" },
  { id: "AYTCF", officialName: "Four Points Flex by Sheraton Antalya Lara" },
  { id: "ESBBU", officialName: "Four Points Flex by Sheraton Ankara Cukurambar" },
  { id: "ISTUT", officialName: "Four Points Flex by Sheraton Istanbul Taksim Square" },
  { id: "YEIBG", officialName: "Four Points Flex by Sheraton Bursa Nilufer" },
  { id: "ISTOX", officialName: "Moxy Istanbul Taksim" },
  { id: "AYTVF", officialName: "Marriott Executive Apartments Antalya" },
  { id: "ISTFE", officialName: "Marriott Executive Apartments Istanbul Fulya" },
  { id: "ISTVV", officialName: "Marriott Executive Apartments Istanbul Investvadi" },
  { id: "ISTTR", officialName: "Marriott Executive Apartments Istanbul Tema World" },
  { id: "AYTRI", officialName: "Residence Inn by Marriott Antalya" },
  { id: "ISTRI", officialName: "Residence Inn by Marriott Istanbul Atasehir" },
  { id: "TZXRI", officialName: "Residence Inn by Marriott Trabzon" },
  { id: "ADBXT", officialName: "Moxy Izmir" },
  { id: "DIYFP", officialName: "Four Points Diyarbakir" },
  // Ritz-Carlton HWS XML property codes, July 2026.
  { id: "ISTRZ", officialName: "The Ritz-Carlton, Istanbul" },
];

export const turkiyeMarriottProperties: MarriottPropertySeed[] =
  turkiyeMarriottOfficialRows.map(({ id, officialName }) =>
    applyCuratedMarriottPropertyAliases({
      id,
      country: "TR",
      region: "overseas",
      officialName,
      brand: inferBrand(officialName),
      ...high,
      aliases: [],
    })
  );
