import { high, inferBrand } from "./helpers";
import type { MarriottPropertySeed } from "./types";

// Source: Marriott hotel sitemap property codes, July 2026.
const southAfricaMarriottOfficialRows = [
  { id: "CPTCK", officialName: "Morea House, Autograph Collection" },
  { id: "JNBMA", officialName: "African Pride Melrose Arch, Autograph Collection®" },
  { id: "SZKAK", officialName: "Leopard Sands, Kruger Park" },
  { id: "JNBDS", officialName: "Ten Bompas Hotel, Johannesburg, a Member of Design Hotels™" },
  { id: "CPTCM", officialName: "Cape Town Marriott Hotel Crystal Towers" },
  { id: "JNBMC", officialName: "Johannesburg Marriott Hotel Melrose Arch" },
  { id: "CPTSW", officialName: "Lord Charles Hotel, Somerset West, a Tribute Portfolio Hotel" },
  { id: "CPTWI", officialName: "The Westin Cape Town" },
  { id: "CPTAR", officialName: "AC Hotel Cape Town Waterfront" },
  { id: "BFNBF", officialName: "Protea Hotel Bloemfontein" },
  { id: "BFNWI", officialName: "Protea Hotel Bloemfontein Willow Lake" },
  { id: "CPTBR", officialName: "Protea Hotel Cape Town Waterfront Breakwater Lodge" },
  { id: "CPTCF", officialName: "Protea Hotel Fire & Ice! Cape Town" },
  { id: "CPTDO", officialName: "Protea Hotel Dorpshuis & Spa Stellenbosch" },
  { id: "CPTDV", officialName: "Protea Hotel Cape Town Durbanville" },
  { id: "CPTFR", officialName: "Protea Hotel Franschhoek" },
  { id: "CPTLA", officialName: "Protea Hotel Cape Town Tyger Valley" },
  { id: "CPTMW", officialName: "Protea Hotel Cape Town Mowbray" },
  { id: "CPTNW", officialName: "Protea Hotel Cape Town North Wharf" },
  { id: "CPTSP", officialName: "Protea Hotel Cape Town Sea Point" },
  { id: "CPTST", officialName: "Protea Hotel Stellenbosch and Conference Centre" },
  { id: "DURKA", officialName: "Protea Hotel Karridene Beach" },
  { id: "DURMO", officialName: "Protea Hotel Harrismith Montrose" },
  { id: "DURUM", officialName: "Protea Hotel Durban Umhlanga" },
  { id: "DURUR", officialName: "Protea Hotel Fire & Ice! Durban Umhlanga Ridge" },
  { id: "FCBCL", officialName: "Protea Hotel Clarens" },
  { id: "GRJKI", officialName: "Protea Hotel George King George" },
  { id: "GRJMO", officialName: "Protea Hotel Mossel Bay" },
  { id: "GRJQU", officialName: "Protea Hotel Knysna Quays" },
  { id: "GRJRI", officialName: "Protea Hotel Oudtshoorn Riempie Estate" },
  { id: "JNBBA", officialName: "Protea Hotel Johannesburg Balalaika Sandton" },
  { id: "JNBKL", officialName: "Protea Hotel Klerksdorp" },
  { id: "JNBMI", officialName: "Protea Hotel Midrand" },
  { id: "JNBMR", officialName: "Protea Hotel Fire & Ice! Johannesburg Melrose Arch" },
  { id: "JNBWA", officialName: "Protea Hotel Johannesburg Wanderers" },
  { id: "JNBOR", officialName: "Protea Hotel O.R. Tambo Airport" },
  { id: "KIMKI", officialName: "Protea Hotel Kimberley" },
  { id: "MBDPR", officialName: "Protea Hotel Mahikeng" },
  { id: "MQPNL", officialName: "Protea Hotel Nelspruit" },
  { id: "PRYLP", officialName: "Protea Hotel Pretoria Loftus Park" },
  { id: "PRYME", officialName: "Protea Hotel Fire & Ice! Pretoria Menlyn" },
  { id: "PTGLA", officialName: "Protea Hotel Polokwane Landmark" },
  { id: "PTGRA", officialName: "Protea Hotel Polokwane Ranch Resort" },
  { id: "PRYHA", officialName: "Protea Hotel Pretoria Hatfield" },
  { id: "RCBUM", officialName: "Protea Hotel Umfolozi River" },
  { id: "UTNUP", officialName: "Protea Hotel Upington" },
  { id: "JNBER", officialName: "Marriott Executive Apartments Johannesburg, Melrose Arch" },
  { id: "CPTEB", officialName: "The Cape Town EDITION" },
] as const;

export const southAfricaMarriottProperties: MarriottPropertySeed[] = southAfricaMarriottOfficialRows.map(
  ({ id, officialName }) => ({
    id,
    country: "ZA",
    region: "overseas",
    officialName,
    brand: inferBrand(officialName),
    ...high,
    aliases: [],
  })
);
